import { ArrowRight, Clock3, Edit3, FileText, RefreshCw } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { api } from '../lib/api';

const statusMap:any={'قيد الإجراء':'warning','مكتملة':'success','مرفوضة':'danger','ملغية':'neutral'};
export function CompanyTransactionDetail(){
 const {companyId='',id=''}=useParams();
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{setData(await api<any>(`/api/workflows/admin/company-transactions/${companyId}/transactions/${id}`));}catch{setError('تعذر تحميل تفاصيل المعاملة.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[companyId,id]);
 if(loading)return <div className="panel-empty">جاري تحميل المعاملة...</div>;
 if(error||!data)return <div className="panel-empty"><h3>{error||'المعاملة غير موجودة'}</h3></div>;
 const tx=data.transaction,wf=data.workflow;
 return <div>
  <div className="page-header"><div><div className="eyebrow">{data.company?.display_name} · {tx.transaction_type_name}</div><h1>المعاملة #{tx.transaction_number}</h1><p>عرض رسمي لسجل المعاملة. هذه الصفحة للمتابعة والاطلاع من بيئة إدارة المنصة.</p></div><div className="header-actions"><Link className="btn secondary" to={`/platform/company-transactions/${companyId}`}><ArrowRight size={16}/>العودة للشركة</Link><Link className="btn secondary" to={`/platform/workflows?typeId=${tx.transaction_type_id}`}><Edit3 size={16}/>تعديل سير العمل</Link><button className="icon-btn" onClick={()=>void load()}><RefreshCw size={16}/></button></div></div>
  <section className="panel transaction-official-header"><div><span>رقم المعاملة</span><strong>#{tx.transaction_number}</strong></div><div><span>النوع</span><strong>{tx.transaction_type_name}</strong></div><div><span>المرحلة الحالية</span><strong>{tx.stage_name||'—'}</strong></div><div><span>الحالة</span><strong><span className={`badge ${statusMap[tx.status]||'neutral'}`}>{tx.status}</span></strong></div></section>
  <div className="workflow-studio-grid"><main>
   <section className="panel"><div className="panel-head"><div><h3>بيانات المعاملة</h3><p>البيانات المسجلة عند إنشاء المعاملة.</p></div><FileText size={19}/></div><div className="data-grid">{Object.entries(tx.data||{}).map(([k,v])=><div className="data-cell" key={k}><span>{wf?.fields?.find((f:any)=>f.field_key===k)?.label_ar||k}</span><strong>{String(v??'—')}</strong></div>)}</div></section>
   <section className="panel" style={{marginTop:16}}><div className="panel-head"><div><h3>الإجابات</h3><p>الأسئلة والإجابات المسجلة خلال الرحلة.</p></div></div>{data.answers.length===0?<div className="empty-soft">لا توجد إجابات مسجلة.</div>:<div className="table-wrap"><table><thead><tr><th>العنصر</th><th>الإجابة</th></tr></thead><tbody>{data.answers.map((a:any)=><tr key={a.id}><td>{a.question_label||a.field_label||'—'}</td><td>{typeof a.value==='object'?JSON.stringify(a.value):String(a.value??'—')}</td></tr>)}</tbody></table></div>}</section>
   <section className="panel" style={{marginTop:16}}><div className="panel-head"><div><h3>سياق كل مرحلة</h3><p>ما كان أمام المسؤول في كل مرحلة وما أُجيب عنه وقت التمرير.</p></div></div><div className="transaction-stage-answers">{(data.actions||[]).filter((a:any)=>['created','next','complete','return'].includes(a.action)).map((a:any,i:number)=>{let m:any={};try{m=a.metadata_json?JSON.parse(a.metadata_json):{}}catch{}const sid=m.stageId||a.from_stage_id;const st=wf?.stages?.find((x:any)=>x.id===sid);if(!st)return null;const snap={...(m.dataSnapshot||{}),...(m.answersSnapshot||{})};const defs=[...(wf?.fields||[]).filter((f:any)=>f.stage_id===sid),...(wf?.questions||[]).filter((q:any)=>q.stage_id===sid)];return <div className="stage-answer-card" key={a.id||i}><div className="stage-answer-head"><strong>المرحلة {st.stage_order} · {st.name_ar}</strong><span>{a.created_at}</span></div>{defs.length===0?<div className="empty-soft">لا توجد أسئلة أو حقول.</div>:<div className="stage-answer-list">{defs.map((x:any)=><div key={x.id}><span>{x.label_ar||x.question_ar}</span><strong>{snap[x.field_key||x.question_key]===undefined?'—':String(snap[x.field_key||x.question_key])}</strong></div>)}</div>}</div>})}</div></section>
  </main><aside className="workflow-quality panel"><div className="panel-head"><div><h3>رحلة المعاملة</h3><p>سجل المراحل كما نُفذت.</p></div><Clock3 size={19}/></div>{data.history.map((h:any,i:number)=><div className="journey-item active" key={h.id}><div className="journey-line"><span className="journey-dot"></span>{i<data.history.length-1&&<i/>}</div><div className="journey-content"><div><strong>{h.stage_name}</strong><span className="journey-status">{h.status}</span></div><small>{h.started_at||'—'}</small></div></div>)}</aside></div>
 </div>;
}
