import { ArrowRight, Edit3, Eye, RefreshCw, Search, Workflow } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';

const statusMap:any={'قيد الإجراء':['warning'],'مكتملة':['success'],'مرفوضة':['danger'],'ملغية':['neutral']};
export function CompanyTransactionsCompany(){
 const {companyId=''}=useParams();
 const [company,setCompany]=useState<any>(null),[types,setTypes]=useState<any[]>([]),[transactions,setTransactions]=useState<any[]>([]),[typeFilter,setTypeFilter]=useState(''),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const [t,r]=await Promise.all([api<any>(`/api/workflows/admin/company-transactions/${companyId}/types`),api<any>(`/api/workflows/admin/company-transactions/${companyId}/list${typeFilter?`?typeId=${encodeURIComponent(typeFilter)}`:''}`)]);setCompany(t.company);setTypes(t.items||[]);setTransactions(r.items||[]);}catch{setError('تعذر تحميل معاملات الشركة.')}finally{setLoading(false)}}
 useEffect(()=>{if(companyId)void load()},[companyId,typeFilter]);
 const filtered=useMemo(()=>transactions.filter(x=>!search||`${x.transaction_number} ${x.transaction_type_name} ${x.employee_name||''}`.includes(search)),[transactions,search]);
 return <div>
  <div className="page-header"><div><div className="eyebrow">معاملات الشركات · {company?.display_name||'الشركة'}</div><h1>{company?.display_name||'الشركة'}</h1><p>{company?.company_identifier||''} · نسخة مستقلة من سير العمل والمعاملات.</p></div><div className="header-actions"><Link className="btn secondary" to="/platform/company-transactions"><ArrowRight size={16}/>الشركات</Link><button className="icon-btn" onClick={()=>void load()}><RefreshCw size={16}/></button></div></div>
  {error&&<div className="login-error page-error">{error}</div>}
  <section className="panel workflow-hero"><div><span className="workflow-kicker">Company Workflow</span><h2>أنواع المعاملات</h2><p>يمكنك فتح سير أي نوع وتعديله للشركة فقط، ثم إنشاء إصدار جديد دون التأثير على بقية الشركات.</p></div><div className="workflow-health"><div><strong>{types.length}</strong><span>أنواع</span></div><div><strong>{types.filter(x=>x.workflow_status==='active').length}</strong><span>مسارات نشطة</span></div><div><strong>{transactions.length}</strong><span>آخر المعاملات</span></div></div></section>
  <section className="panel"><div className="panel-head"><div><h3>أنواع المعاملات المنشورة</h3><p>الإصدار الحالي مستقل عن القالب وعن الشركات الأخرى.</p></div><Workflow size={19}/></div><div className="table-wrap"><table><thead><tr><th>نوع المعاملة</th><th>الحالة</th><th>الإصدار</th><th>عدد المعاملات</th><th>إجراءات</th></tr></thead><tbody>{types.map(x=><tr key={x.id}><td><strong>{x.name_ar}</strong></td><td><span className={`badge ${x.status==='active'?'success':'neutral'}`}>{x.status==='active'?'نشطة':'غير نشطة'}</span></td><td>v{x.workflow_version||'—'}</td><td>{x.transaction_count||0}</td><td><div className="table-actions"><Link className="table-link" to={`/platform/workflows?typeId=${x.id}`}><Edit3 size={14}/>تعديل السير</Link><button className="table-link" onClick={()=>setTypeFilter(x.id)}><Eye size={14}/>عرض المعاملات</button></div></td></tr>)}</tbody></table></div></section>
  <section className="panel" style={{marginTop:16}}><div className="panel-head"><div><h3>المعاملات الفعلية</h3><p>السجلات المرتبطة بهذه الشركة فقط.</p></div><Search size={19}/></div><div className="filter-bar"><div className="search-field"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث برقم المعاملة أو النوع أو الموظف"/></div><div className="filter-select"><span>نوع المعاملة</span><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">كل الأنواع</option>{types.map(x=><option key={x.id} value={x.id}>{x.name_ar}</option>)}</select></div></div>{loading?<div className="panel-empty">جاري التحميل...</div>:filtered.length===0?<div className="panel-empty">لا توجد معاملات مطابقة.</div>:<div className="table-wrap"><table><thead><tr><th>الرقم</th><th>النوع</th><th>الموظف</th><th>المرحلة</th><th>الحالة</th><th>آخر تحديث</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><strong>#{x.transaction_number}</strong></td><td>{x.transaction_type_name}</td><td>{x.employee_name||'—'}</td><td>{x.stage_name||'—'}</td><td><span className={`badge ${statusMap[x.status]?.[0]||'neutral'}`}>{x.status}</span></td><td>{x.updated_at}</td><td><Link className="table-link" to={`/platform/company-transactions/${companyId}/transactions/${x.id}`}><Eye size={14}/>فتح</Link></td></tr>)}</tbody></table></div>}</section>
 </div>;
}
