import { ArrowRight, CheckCircle2, Clock3, FileText, History, RefreshCw, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { api } from '../lib/api';

const statusMap:any={'قيد الإجراء':'warning','مكتملة':'success','مرفوضة':'danger','ملغية':'neutral'};
const stageStatus:any={active:'جارية',completed:'اكتملت',returned:'أُعيدت',rejected:'رُفضت',cancelled:'أُلغيت'};
const valueText=(v:any)=>v===null||v===undefined||v===''?'لم يُجب':typeof v==='boolean'?(v?'نعم':'لا'):Array.isArray(v)?v.join('، '):typeof v==='object'?JSON.stringify(v):String(v);
const timeText=(v:any)=>v?new Date(v).toLocaleString('ar-SA',{dateStyle:'medium',timeStyle:'short'}):'—';
export function CompanyTransactionDetail(){
 const {companyId='',id=''}=useParams();
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{setData(await api<any>(`/api/workflows/admin/company-transactions/${companyId}/transactions/${id}`));}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل تفاصيل المعاملة.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[companyId,id]);
 if(loading)return <div className="panel-empty">جاري تحميل سجل المعاملة…</div>;
 if(error||!data)return <div className="panel-empty"><h3>{error||'المعاملة غير موجودة'}</h3></div>;
 const tx=data.transaction,wf=data.workflow,history=data.history||[],answers=data.answers||[];
 const requestFields=(wf?.fields||[]).filter((f:any)=>!f.stage_id);
 const allData=Object.entries(tx.data||{}).filter(([k])=>!String(k).startsWith('_simulation'));
 return <div className="transaction-record-page">
  <div className="page-header"><div><div className="eyebrow">{data.company?.display_name||'الشركة'} · سجل رسمي</div><h1>{tx.transaction_type_name} <span className="record-number">#{tx.transaction_number}</span></h1><p>هذه نسخة محفوظة للقراءة والتدقيق، وتعرض ما حدث في كل مرحلة كما سُجل.</p></div><div className="header-actions"><Link className="btn secondary" to={`/platform/company-transactions/${companyId}`}><ArrowRight size={16}/>العودة للشركة</Link><Link className="btn secondary" to={`/platform/workflows?typeId=${tx.transaction_type_id}`}><FileText size={16}/>استوديو سير العمل</Link><button className="icon-btn" onClick={()=>void load()} aria-label="تحديث"><RefreshCw size={16}/></button></div></div>
  <section className="record-summary"><div className="record-number-block"><span>رقم المعاملة</span><b>#{tx.transaction_number}</b><small>{timeText(tx.created_at)}</small></div><div className="record-summary-cell"><span>الشركة</span><b>{data.company?.display_name||'—'}</b></div><div className="record-summary-cell"><span>المرحلة الحالية</span><b>{tx.stage_name||'انتهت المعاملة'}</b></div><div className="record-summary-cell"><span>الحالة</span><b><span className={`badge ${statusMap[tx.status]||'neutral'}`}>{tx.status}</span></b></div><div className="record-summary-cell"><span>الموظف</span><b>{tx.employee_name||'—'}</b></div></section>
  <div className="record-content-grid"><main className="record-main-column">
   <section className="panel record-panel"><div className="panel-head"><div><span className="record-eyebrow">01 · الطلب الأصلي</span><h3>عناصر مقدم الطلب</h3><p>البيانات التي بدأ بها الطلب قبل دخوله مراحل المعالجة.</p></div><FileText size={19}/></div>{allData.length===0?<div className="empty-soft">لا توجد بيانات إضافية مسجلة عند الإنشاء.</div>:<div className="record-data-grid">{allData.map(([key,value])=><div className="record-data-cell" key={key}><span>{requestFields.find((f:any)=>f.field_key===key)?.label_ar||key}</span><b>{valueText(value)}</b></div>)}</div>}</section>
   <section className="panel record-panel"><div className="panel-head"><div><span className="record-eyebrow">02 · سجل المراحل</span><h3>رحلة المعاملة من البداية للنهاية</h3><p>كل بطاقة تمثل زيارة فعلية لمرحلة. عند الإرجاع ستظهر زيارة جديدة مع الحفاظ على الزيارة السابقة.</p></div><History size={19}/></div>{history.length===0?<div className="empty-soft">لا يوجد سجل مراحل لهذه المعاملة.</div>:<div className="record-timeline">{history.map((h:any,i:number)=>{const snap=h.stage_snapshot||{};const savedAnswers=h.answers_snapshot||[];const stageName=snap.nameAr||h.stage_name||`المرحلة ${i+1}`;const stageFields=snap.fields||[];const stageQuestions=snap.questions||[];return <article className={`record-stage-card ${h.status==='active'?'is-current':''}`} key={h.id}><div className="record-stage-rail"><span className="record-stage-index">{String(i+1).padStart(2,'0')}</span>{i<history.length-1&&<i/>}</div><div className="record-stage-body"><div className="record-stage-head"><div><span className="record-eyebrow">المرحلة {snap.stageOrder||i+1}</span><h4>{stageName}</h4></div><span className={`record-stage-status ${h.status||'completed'}`}>{stageStatus[h.status]||h.status||'—'}</span></div><div className="record-stage-meta"><span><Clock3 size={14}/>بدأت: {timeText(h.started_at)}</span><span><CheckCircle2 size={14}/>{h.completed_at?`انتهت: ${timeText(h.completed_at)}`:'لم تنتهِ بعد'}</span><span><ShieldCheck size={14}/>المسؤول: {({company_admin:'مدير الشركة',manager:'المدير المباشر',department_manager:'مدير الإدارة',position_holder:'شاغل المنصب',role:'دور وظيفي',permission:'صاحب صلاحية',user:'مستخدم محدد'} as any)[snap.responsibleType]||snap.responsibleType||'—'}</span><span><Clock3 size={14}/>المدة: {snap.durationMinutes?`${snap.durationMinutes} دقيقة`:'بدون مدة'}</span></div>{h.return_reason&&<div className="record-return-reason"><b>سبب الإرجاع</b><span>{h.return_reason}</span></div>}<div className="record-answers-heading">ما الذي عُرض في هذه المرحلة وما الإجابة المسجلة؟</div>{savedAnswers.length===0?<div className="record-no-answers">لا توجد إجابات مسجلة في هذه الزيارة.</div>:<div className="record-answer-grid">{savedAnswers.map((a:any,j:number)=><div className="record-answer-cell" key={`${h.id}-${a.key||j}`}><span>{a.labelAr||a.key||'عنصر'}</span><b>{valueText(a.value)}</b><small>{a.kind==='question'?'سؤال':'حقل'}</small></div>)}</div>}{(stageFields.length+stageQuestions.length)>0&&<div className="record-stage-definition"><b>عناصر المرحلة المحفوظة</b><span>{stageFields.length} حقول · {stageQuestions.length} أسئلة</span></div>}</div></article>})}</div>}</section>
   <section className="panel record-panel"><div className="panel-head"><div><span className="record-eyebrow">03 · الإجابات المسجلة</span><h3>كل الإجابات</h3><p>عرض شامل للإجابات التي احتفظت بها قاعدة البيانات.</p></div></div>{answers.length===0?<div className="empty-soft">لا توجد إجابات مسجلة.</div>:<div className="record-data-grid">{answers.map((a:any)=><div className="record-data-cell" key={a.id}><span>{a.question_label||a.field_label||a.question_key||a.field_key||'عنصر'}</span><b>{valueText(a.value)}</b></div>)}</div>}</section>
   <section className="panel record-panel"><div className="panel-head"><div><span className="record-eyebrow">04 · المرفقات</span><h3>ملفات المعاملة</h3><p>كل ملف مرتبط بالمرحلة التي رُفع فيها.</p></div></div>{(data.attachments||[]).length===0?<div className="empty-soft">لا توجد مرفقات.</div>:<div className="record-data-grid">{data.attachments.map((a:any)=><a className="record-data-cell attachment-download-card" key={a.id} href={`/api/workflows/admin/company-transactions/${companyId}/transactions/${id}/attachments/${a.id}`}><span>{a.file_name}</span><b>{a.content_type||'ملف'} · {a.size_bytes?`${Math.round(a.size_bytes/1024)} KB`:'—'}</b><small>{a.stage_name||'مرحلة غير محددة'} · {timeText(a.created_at)}</small></a>)}</div>}</section>
  </main><aside className="record-side-column"><section className="panel record-side-card"><span className="record-eyebrow">ملخص الحالة</span><h3><span className={`badge ${statusMap[tx.status]||'neutral'}`}>{tx.status}</span></h3><div className="record-side-row"><span>عدد زيارات المراحل</span><b>{history.length}</b></div><div className="record-side-row"><span>عدد الإجابات</span><b>{answers.length}</b></div><div className="record-side-row"><span>آخر تحديث</span><b>{timeText(tx.updated_at)}</b></div><div className="record-side-row"><span>رقم الإصدار</span><b>v{wf?.workflow?.version||'—'}</b></div></section><section className="panel record-side-card"><div className="panel-head"><div><h3>سجل الإجراءات</h3><p>كل تمرير أو إرجاع أو قرار مسجل بالوقت.</p></div></div>{(data.actions||[]).length===0?<div className="record-no-answers">لا توجد إجراءات.</div>:(data.actions||[]).map((a:any)=><div className="record-action-item" key={a.id}><span>{timeText(a.created_at)}</span><b>{{created:'إنشاء المعاملة',next:'تمرير المعاملة',return:'إرجاع',complete:'إكمال',reject:'رفض',cancel:'إلغاء'}[a.action]||a.action}</b>{a.reason&&<p>{a.reason}</p>}</div>)}</section><div className="record-security-note"><ShieldCheck size={17}/><span>السجل للعرض والتدقيق. التعديلات على سير العمل لا تغيّر الإجابات المحفوظة لكل مرحلة.</span></div></aside></div>
 </div>;
}
