import { useEffect,useState } from 'react';
import { ArrowUpLeft, BriefcaseBusiness, CalendarDays, CheckCircle2, Clock3, UsersRound } from 'lucide-react';
import { api } from '../lib/api';
export function Dashboard(){
 const [ctx,setCtx]=useState<any>(null);
 useEffect(()=>{api('/api/context').then(setCtx)},[]);
 const company=ctx?.company, platform=ctx?.session?.platformUserId && !ctx?.session?.activeCompanyId;
 const widgets=[['عدد الموظفين','—',platform?'منصة المنصة':company?'بيانات الشركة ستُفعل في المرحلة التالية':'لا توجد شركة',UsersRound],['الموظفون النشطون','—','نطاق الشركة',CheckCircle2],['الشواغر','—','الهيكل التنظيمي',BriefcaseBusiness],['المعاملات قيد الإجراء','—','محرك المعاملات لاحقاً',Clock3],['المعاملات المتأخرة','—','محرك المعاملات لاحقاً',Clock3],['المعاملات المكتملة','—','محرك المعاملات لاحقاً',CheckCircle2],['الإجازات الحالية','—','محرك الإجازات لاحقاً',CalendarDays],['التنبيهات المهمة',ctx?.notifications?.length??0,'مرتبطة بالحساب والنطاق',ArrowUpLeft]];
 return <div><div className="page-header"><div><div className="eyebrow">{platform?'إدارة المنصة':'نظرة عامة'}</div><h1>{platform?'إدارة الشركات':'الرئيسية'}</h1><p>{platform?'منصة HR Nexus متعددة المستأجرين.':'مساحة تشغيل موحدة ضمن نطاق الشركة الحالي.'}</p></div><div className="header-status"><span className="status-dot"></span>{platform?'مدير المنصة':ctx?.session?.activeCompanyId?company?.displayName:'حساب شركة'}</div></div>
 <section className="hero"><div><span className="hero-kicker">HR NEXUS</span><h2>{platform?'هوية منصة مستقلة عن الشركات':'بيئة مؤسسية معزولة لكل شركة'}</h2><p>{platform?'يمكن لمدير المنصة إدارة المستأجرين وطلب دخول مؤقت ومُدقق إلى بيئات الشركات.':'هوية الحساب مرتبطة بشركة واحدة ولا يمكن تبديل company_id من الواجهة أو الطلب.'}</p></div><div className="hero-side"><div className="hero-line"><span>قاعدة البيانات</span><strong>D1</strong></div><div className="hero-line"><span>النطاق</span><strong>{ctx?.session?.activeCompanyId?'Company Context':'Platform'}</strong></div><div className="hero-line"><span>اللغة</span><strong>العربية · RTL</strong></div></div></section>
 <div className="section-heading"><div><h2>مؤشرات النظام</h2><span>مهيأة للصلاحيات والنطاق المؤسسي</span></div></div><div className="widget-grid">{widgets.map(([label,value,sub,Icon])=><article className="metric" key={String(label)}><div className="metric-top"><span>{label as string}</span><div className="metric-icon"><Icon size={18}/></div></div><strong>{value as string|number}</strong><p>{sub as string}</p></article>)}</div>
 <div className="two-col"><section className="panel"><div className="panel-head"><div><h3>آخر النشاطات</h3><p>سجل النظام سيظهر هنا بعد بدء الاستخدام.</p></div></div><div className="panel-empty">لا توجد نشاطات بعد</div></section><section className="panel"><div className="panel-head"><div><h3>التنبيهات المهمة</h3><p>التنبيهات المرتبطة بحسابك وشركتك.</p></div></div><div className="panel-empty">{ctx?.notifications?.length?`لديك ${ctx.notifications.length} تنبيه`:'لا توجد تنبيهات'}</div></section></div></div>
}
