import { Link, useParams } from 'react-router-dom';
import { ArrowRight, BriefcaseBusiness, Building2, CreditCard, FileText, Landmark, Save, ShieldCheck, UserRound } from 'lucide-react';
import { useEffect,useState } from 'react';
import { api } from '../lib/api';
import { EmptyState, ErrorState, LoadingState } from '../components/State';

const statusMap:any={active:['نشط','success'],suspended:['معلق','warning'],leave:['إجازة','info'],terminated:['إنهاء','danger']};
export function EmployeeProfile(){const {id}=useParams();const [data,setData]=useState<any>(null);const [editing,setEditing]=useState(false);const [draft,setDraft]=useState<any>({});const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [tab,setTab]=useState('overview');const [saving,setSaving]=useState(false);const [salary,setSalary]=useState({basicSalary:'',housingAllowance:'',transportAllowance:'',otherAllowances:'',effectiveDate:''});
 const load=()=>{setLoading(true);api<any>(`/api/employees/${id}`).then(setData).catch(()=>setError(true)).finally(()=>setLoading(false))};useEffect(load,[id]);useEffect(()=>{if(data?.employee)setDraft({...data.employee})},[data]);if(loading)return <LoadingState/>;if(error||!data)return <ErrorState/>;const e=data.employee;
 const saveEmployee=async()=>{setSaving(true);try{await api(`/api/employees/${id}`,{method:'PATCH',body:JSON.stringify({firstName:draft.first_name,fatherName:draft.father_name||null,familyName:draft.family_name||null,nationality:draft.nationality||null,personalPhone:draft.personal_phone||null,personalEmail:draft.personal_email||null,shortAddress:draft.short_address||null,jobTitle:draft.job_title||null,workLocation:draft.work_location||null,status:draft.status})});setEditing(false);load()}catch{}finally{setSaving(false)}};
 const saveSalary=async()=>{setSaving(true);try{await api(`/api/employees/${id}/salary`,{method:'POST',body:JSON.stringify({...salary,basicSalary:Number(salary.basicSalary),housingAllowance:Number(salary.housingAllowance),transportAllowance:Number(salary.transportAllowance),otherAllowances:Number(salary.otherAllowances)})});setSalary({basicSalary:'',housingAllowance:'',transportAllowance:'',otherAllowances:'',effectiveDate:''});load()}catch{}finally{setSaving(false)}};
 const tabs=[['overview','نظرة عامة',UserRound],['employment','البيانات الوظيفية',BriefcaseBusiness],['salary','الراتب والمزايا',CreditCard],['bank','البنك',Landmark],['statutory','GOSI / التأمين',ShieldCheck],['leave','الإجازات',FileText],['career','السجل الوظيفي',FileText]];
 const detail=(k:string,v:any)=><div className="detail"><span>{k}</span><strong>{v||'—'}</strong></div>;
 return <div><div className="page-header"><div><div className="breadcrumbs-inner"><Link to="/employees">الموظفون</Link><ArrowRight size={14}/><span>ملف الموظف</span></div><h1>ملف الموظف</h1><p>السجل الرئيسي للموظف مع البيانات الوظيفية والمالية والحساسة حسب الصلاحيات.</p></div></div><section className="profile-head"><div className="profile-avatar"><UserRound size={30}/></div><div className="profile-main"><h2>{e.full_name}</h2><div className="profile-meta"><span>{e.employee_number}</span><i></i><span>{e.job_title||'—'}</span><i></i><span>{statusMap[e.status]?.[0]||e.status}</span></div></div><span className={`badge ${statusMap[e.status]?.[1]||'neutral'}`}>{statusMap[e.status]?.[0]||e.status}</span>{data.capabilities?.edit&&<button className="btn secondary" onClick={()=>setEditing(v=>!v)}>{editing?'إلغاء':'تعديل'}</button>}</section>{editing&&<section className="panel" style={{marginBottom:14}}><div className="form-grid"><label className="form-field"><span>الاسم الأول</span><input value={draft.first_name||''} onChange={x=>setDraft((v:any)=>({...v,first_name:x.target.value}))}/></label><label className="form-field"><span>اسم الأب</span><input value={draft.father_name||''} onChange={x=>setDraft((v:any)=>({...v,father_name:x.target.value}))}/></label><label className="form-field"><span>اسم العائلة</span><input value={draft.family_name||''} onChange={x=>setDraft((v:any)=>({...v,family_name:x.target.value}))}/></label><label className="form-field"><span>الجنسية</span><input value={draft.nationality||''} onChange={x=>setDraft((v:any)=>({...v,nationality:x.target.value}))}/></label><label className="form-field"><span>الجوال</span><input value={draft.personal_phone||''} onChange={x=>setDraft((v:any)=>({...v,personal_phone:x.target.value}))}/></label><label className="form-field"><span>البريد</span><input value={draft.personal_email||''} onChange={x=>setDraft((v:any)=>({...v,personal_email:x.target.value}))}/></label><label className="form-field"><span>المسمى الوظيفي</span><input value={draft.job_title||''} onChange={x=>setDraft((v:any)=>({...v,job_title:x.target.value}))}/></label><label className="form-field"><span>موقع العمل</span><input value={draft.work_location||''} onChange={x=>setDraft((v:any)=>({...v,work_location:x.target.value}))}/></label><label className="form-field"><span>الحالة</span><select value={draft.status||'active'} onChange={x=>setDraft((v:any)=>({...v,status:x.target.value}))}><option value="active">نشط</option><option value="suspended">معلق</option><option value="leave">إجازة</option><option value="terminated">إنهاء</option></select></label></div><button className="btn primary" onClick={saveEmployee} disabled={saving}><Save size={15}/>حفظ التعديل</button></section>}<div className="profile-layout"><aside className="profile-tabs">{tabs.map(([key,label,Icon]:any)=><button className={tab===key?'active':''} key={key} onClick={()=>setTab(key)}><span><Icon size={15}/>{label}</span></button>)}</aside><section className="profile-content">
 {tab==='overview'&&<><div className="section-heading"><div><h2>البيانات الشخصية</h2><span>المعلومات الأساسية المتاحة حسب الصلاحية</span></div></div><div className="detail-grid">{detail('الاسم الأول',e.first_name)}{detail('اسم الأب',e.father_name)}{detail('اسم العائلة',e.family_name)}{detail('الجنسية',e.nationality)}{detail('رقم الموظف',e.employee_number)}{detail('رقم الهوية',e.national_id)}{detail('تاريخ الميلاد',e.date_of_birth)}{detail('الجوال',e.personal_phone)}{detail('البريد',e.personal_email)}{detail('العنوان المختصر',e.short_address)}{detail('الجواز',e.passport_number)}{detail('جهة إصدار الهوية',e.identity_issuer)}</div></>}
 {tab==='employment'&&<><div className="section-heading"><div><h2>البيانات الوظيفية</h2><span>العلاقة التنظيمية مشتقة من Phase 4</span></div></div><div className="detail-grid">{detail('المسمى الوظيفي',e.job_title)}{detail('الوحدة التنظيمية',e.organization_unit_name)}{detail('المنصب',e.position_title||e.position_id)}{detail('المدير المباشر',e.manager_name||'—')}{detail('موقع العمل',e.work_location)}{detail('نوع التوظيف',e.employment_type)}{detail('نوع العقد',e.contract_type)}{detail('بداية العقد',e.contract_start_date)}{detail('نهاية العقد',e.contract_end_date)}{detail('تاريخ المباشرة الفعلي',e.actual_start_date)}{detail('فترة التجربة',e.probation_days?`${e.probation_days} يوم`:null)}{detail('نتيجة التجربة',e.probation_result==='passed'?'ناجح':e.probation_result==='failed'?'غير مجتاز':e.probation_result)}</div></>}
 {tab==='salary'&&data.capabilities?.viewSalary&&<><div className="section-heading"><div><h2>الراتب والمزايا</h2><span>السجل لا يُستبدل؛ كل تغيير يسجل كتاريخ فعال جديد</span></div></div>{data.salary?<div className="table-wrap"><table><thead><tr><th>تاريخ السريان</th><th>الأساسي</th><th>السكن</th><th>النقل</th><th>أخرى</th></tr></thead><tbody>{data.salary.results.map((x:any)=><tr key={x.id}><td>{x.effective_date}</td><td>{x.basic_salary}</td><td>{x.housing_allowance}</td><td>{x.transport_allowance}</td><td>{x.other_allowances}</td></tr>)}</tbody></table></div>:<EmptyState title="بيانات الراتب غير متاحة" description="لا تملك الصلاحية اللازمة لعرض الراتب."/>}{data.capabilities?.editSalary&&<div className="inline-form"><input placeholder="الأساسي" value={salary.basicSalary} onChange={x=>setSalary(v=>({...v,basicSalary:x.target.value}))}/><input placeholder="السكن" value={salary.housingAllowance} onChange={x=>setSalary(v=>({...v,housingAllowance:x.target.value}))}/><input placeholder="النقل" value={salary.transportAllowance} onChange={x=>setSalary(v=>({...v,transportAllowance:x.target.value}))}/><input placeholder="أخرى" value={salary.otherAllowances} onChange={x=>setSalary(v=>({...v,otherAllowances:x.target.value}))}/><input type="date" value={salary.effectiveDate} onChange={x=>setSalary(v=>({...v,effectiveDate:x.target.value}))}/><button className="btn primary" disabled={saving||!salary.effectiveDate} onClick={saveSalary}><Save size={15}/>إضافة سجل راتب</button></div>}</>}
 {tab==='bank'&&<><div className="section-heading"><div><h2>الحساب البنكي</h2><span>حساب نشط واحد لكل موظف</span></div></div>{data.bank?.results?.map((x:any)=><div className="bank-card" key={x.id}><strong>{x.bank_name}</strong><span>{x.iban}</span><em>{x.active?'نشط':'غير نشط'}</em></div>)||<EmptyState title="لا توجد بيانات بنكية" description="بيانات البنك غير متاحة أو لم تُسجل بعد."/>}</>}
 {tab==='statutory'&&<><div className="section-heading"><div><h2>GOSI / التأمين</h2><span>البيانات النظامية والتأمينية</span></div></div><div className="detail-grid">{detail('رقم التأمينات',data.statutory?.gosi_number||e.gosi_number)}{detail('رقم التأمين',data.statutory?.insurance_number)}{detail('مزود التأمين',data.statutory?.insurance_provider)}{detail('فئة التأمين',data.statutory?.insurance_class||e.insurance_profile)}{detail('مخاطر مهنية',data.statutory?.professional_hazard?'نعم':'لا')}</div></>}
 {tab==='leave'&&<><div className="section-heading"><div><h2>الإجازات</h2><span>أرصدة قابلة للتكامل مع مرحلة الإجازات</span></div></div><div className="table-wrap"><table><thead><tr><th>النوع</th><th>الرصيد</th><th>من</th><th>إلى</th></tr></thead><tbody>{(data.leave?.results||[]).map((x:any)=><tr key={x.id}><td>{x.leave_type}</td><td>{x.balance_days}</td><td>{x.effective_from}</td><td>{x.effective_to||'—'}</td></tr>)}</tbody></table></div></>}
 {tab==='career'&&<><div className="section-heading"><div><h2>السجل الوظيفي</h2><span>يحفظ النقل والترقية وتغيير المنصب والمدير والراتب</span></div></div><div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>التغيير</th><th>المسمى</th><th>الوحدة</th><th>المنصب</th></tr></thead><tbody>{(data.career?.results||[]).map((x:any)=><tr key={x.id}><td>{x.effective_date}</td><td>{x.change_type}</td><td>{x.job_title||'—'}</td><td>{x.organization_unit_name||'—'}</td><td>{x.position_name||'—'}</td></tr>)}</tbody></table></div></>}
 </section></div></div>}
