import { Link } from 'react-router-dom';
import { Filter, Plus, RefreshCw, Search, SlidersHorizontal } from 'lucide-react';
import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { EmptyState, ErrorState, LoadingState } from '../components/State';

type Item={id:string;employee_number:string;name:string;job_title:string|null;department:string|null;manager:string|null;status:string;join_date:string|null};
const statusMap:any={active:['نشط','success'],suspended:['معلق','warning'],leave:['إجازة','info'],terminated:['إنهاء','danger']};
export function Employees(){const [items,setItems]=useState<Item[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [search,setSearch]=useState('');const [status,setStatus]=useState('');const [page,setPage]=useState(1);const [total,setTotal]=useState(0);const load=async()=>{setLoading(true);setError(false);try{const d=await api<{items:Item[];total:number;page:number}>('/api/employees?'+new URLSearchParams({search,status,page:String(page)}));setItems(d.items);setTotal(d.total)}catch{setError(true)}finally{setLoading(false)}};useEffect(()=>{load()},[page,status]);return <div><div className="page-header"><div><div className="eyebrow">الموارد البشرية</div><h1>الموظفون</h1><p>إدارة بيانات الموظفين والوصول إلى ملفاتهم ضمن نطاق الشركة.</p></div><Link className="btn primary" to="/employees/new"><Plus size={18}/>إضافة موظف</Link></div><div className="filter-bar"><div className="search-field"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="ابحث برقم الموظف أو رقم الهوية"/><button onClick={load}>بحث</button></div><div className="filter-select"><SlidersHorizontal size={17}/><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">كل الحالات</option><option value="active">نشط</option><option value="suspended">معلق</option><option value="leave">إجازة</option><option value="terminated">إنهاء</option></select></div><button className="btn secondary" onClick={()=>{setSearch('');setStatus('');setPage(1);setTimeout(load,0)}}><RefreshCw size={17}/>تحديث</button></div><section className="table-card"><div className="table-head"><div><h2>قائمة الموظفين</h2><span>{total} سجل</span></div><button className="icon-btn" title="الفلاتر"><Filter size={18}/></button></div>{loading?<LoadingState/>:error?<ErrorState/>:items.length===0?<EmptyState title="لا توجد سجلات موظفين" description="عند إضافة موظفين ستظهر بياناتهم هنا مع البحث والتصفية والترقيم."/>:<div className="table-wrap"><table><thead><tr><th>رقم الموظف</th><th>الاسم</th><th>المسمى الوظيفي</th><th>الإدارة</th><th>المدير المباشر</th><th>الحالة</th><th>تاريخ المباشرة</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td className="mono">{x.employee_number}</td><td><strong>{x.name}</strong></td><td>{x.job_title||'—'}</td><td>{x.department||'—'}</td><td>{x.manager||'—'}</td><td><span className={`badge ${statusMap[x.status]?.[1]}`}>{statusMap[x.status]?.[0]||x.status}</span></td><td>{x.join_date||'—'}</td><td><Link className="table-link" to={`/employees/${x.id}`}>عرض الملف</Link></td></tr>)}</tbody></table></div>}{total>0&&<div className="pagination"><span>صفحة {page} من {Math.max(1,Math.ceil(total/20))}</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>السابق</button><button disabled={page>=Math.ceil(total/20)} onClick={()=>setPage(p=>p+1)}>التالي</button></div></div>}</section></div>}
