import { FormEvent, useState } from 'react';
import { ArrowLeft, Building2, LockKeyhole, UserRound } from 'lucide-react';
import { api } from '../lib/api';

export function Login(){
  const [companyId,setCompanyId]=useState(''); const [loginIdentifier,setLoginIdentifier]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({companyId,loginIdentifier,password})});window.location.href='/';}catch{setError('بيانات الدخول غير صحيحة أو الحساب غير متاح.')}finally{setBusy(false)}}
  return <div className="login-page"><div className="login-panel"><div className="login-brand"><div className="brand-mark">N</div><div><strong>HR Nexus</strong><span>Enterprise HR Platform</span></div></div><div className="login-copy"><span>تسجيل الدخول</span><h1>مرحباً بعودتك</h1><p>أدخل بيانات حسابك للوصول إلى بيئة الشركة.</p></div><form onSubmit={submit} className="login-form"><label>معرّف الشركة<div className="input-wrap"><Building2 size={17}/><input required value={companyId} onChange={e=>setCompanyId(e.target.value)} placeholder="مثال: A001"/></div></label><label>رقم الهوية / معرف المستخدم<div className="input-wrap"><UserRound size={17}/><input required value={loginIdentifier} onChange={e=>setLoginIdentifier(e.target.value)} placeholder="أدخل رقم الهوية أو معرف المستخدم"/></div></label><label>كلمة المرور<div className="input-wrap"><LockKeyhole size={17}/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="أدخل كلمة المرور"/></div></label>{error&&<div className="login-error">{error}</div>}<button className="login-submit" disabled={busy}>{busy?'جاري التحقق...':<>دخول آمن <ArrowLeft size={17}/></>}</button></form><div className="login-note">الوصول محكوم بنطاق الشركة والصلاحيات المسندة للحساب.</div></div><div className="login-side"><span>HR NEXUS</span><h2>بنية مؤسسية واحدة<br/>لعمليات الموارد البشرية</h2><p>تأسيس متعدد المستأجرين، صلاحيات خادمية، وسجل تدقيق مصمم للتوسع.</p></div></div>
}
