import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, Save, UserPlus } from 'lucide-react';
import { useEffect,useState } from 'react';
import { api } from '../lib/api';

const initial:any={employeeNumber:'',firstName:'',fatherName:'',familyName:'',nationalId:'',nationality:'',gender:'',dateOfBirth:'',personalPhone:'',personalEmail:'',shortAddress:'',jobTitle:'',organizationUnitId:'',positionId:'',workLocation:'',employmentType:'full_time',contractType:'',contractStartDate:'',contractEndDate:'',contractAutoRenew:false,status:'active',joinDate:'',actualStartDate:'',probationDays:180,probationExtensionDays:0,gosiNumber:'',residencyClassification:'',insuranceProfile:'',professionalHazard:false,createAccount:false};
export function NewEmployee(){const [form,setForm]=useState(initial);const [units,setUnits]=useState<any[]>([]);const [positions,setPositions]=useState<any[]>([]);const [contracts,setContracts]=useState<any[]>([]);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const navigate=useNavigate();
 useEffect(()=>{Promise.all([api<any>('/api/organization'),api<any>('/api/employees/contract-types')]).then(([o,c])=>{setUnits(o.units||[]);setPositions(o.positions||[]);setContracts(c.items||[])}).catch(()=>setError('تعذر تحميل بيانات الهيكل وأنواع العقود.'))},[]);
 const children=units.filter(x=>x.active); const field=(name:string,label:string,type='text')=><label className="form-field"><span>{label}</span><input type={type} value={form[name]??''} onChange={e=>setForm((v:any)=>({...v,[name]:e.target.value}))}/></label>;
 const save=async(e:any)=>{e.preventDefault();setSaving(true);setError('');try{const d=await api<any>('/api/employees',{method:'POST',body:JSON.stringify({...form,probationDays:Number(form.probationDays),probationExtensionDays:Number(form.probationExtensionDays),organizationUnitId:form.organizationUnitId||null,positionId:form.positionId||null,contractType:form.contractType||null})});navigate(`/employees/${d.id}`)}catch(err:any){setError(err?.message||'تعذر حفظ الموظف.')}finally{setSaving(false)}};
 return <div><div className="page-header"><div><div className="breadcrumbs-inner"><Link to="/employees">الموظفون</Link><ArrowRight size={14}/><span>إضافة موظف</span></div><h1>إضافة موظف</h1><p>إنشاء سجل موظف حقيقي وربطه بالهيكل التنظيمي دون إنشاء بيانات تجريبية.</p></div></div><form onSubmit={save} className="employee-form"><section className="panel"><div className="section-heading"><div><h2><UserPlus size={18}/> البيانات الأساسية</h2><span>رقم الموظف والهوية والاتصال</span></div></div><div className="form-grid">{field('employeeNumber','رقم الموظف')}{field('firstName','الاسم الأول')}{field('fatherName','اسم الأب')}{field('familyName','اسم العائلة')}{field('nationalId','رقم الهوية / الإقامة')}{field('nationality','الجنسية')}{field('gender','الجنس')}{field('dateOfBirth','تاريخ الميلاد','date')}{field('personalPhone','الجوال')}{field('personalEmail','البريد الإلكتروني','email')}{field('shortAddress','العنوان المختصر')}</div></section>
 <section className="panel"><div className="section-heading"><div><h2>البيانات الوظيفية</h2><span>يرتبط الموظف مباشرة بالهيكل والمناصب في Phase 4</span></div></div><div className="form-grid">{field('jobTitle','المسمى الوظيفي')}{field('workLocation','موقع العمل')}<label className="form-field"><span>الوحدة التنظيمية</span><select value={form.organizationUnitId} onChange={e=>setForm((v:any)=>({...v,organizationUnitId:e.target.value,positionId:''}))}><option value="">اختر الوحدة</option>{children.map(u=><option key={u.id} value={u.id}>{u.name_ar}</option>)}</select></label><label className="form-field"><span>المنصب</span><select value={form.positionId} onChange={e=>setForm((v:any)=>({...v,positionId:e.target.value}))}><option value="">اختر المنصب</option>{positions.filter(p=>!form.organizationUnitId||p.organization_unit_id===form.organizationUnitId).map(p=><option key={p.id} value={p.id}>{p.title_ar}{p.code?` — ${p.code}`:''}</option>)}</select></label><label className="form-field"><span>نوع التوظيف</span><select value={form.employmentType} onChange={e=>setForm((v:any)=>({...v,employmentType:e.target.value}))}><option value="full_time">دوام كامل</option><option value="part_time">دوام جزئي</option><option value="training">تدريب</option><option value="tamheer">تمهير</option></select></label><label className="form-field"><span>نوع العقد</span><select value={form.contractType} onChange={e=>setForm((v:any)=>({...v,contractType:e.target.value}))}><option value="">اختر</option>{contracts.map(x=><option key={x.code} value={x.code}>{x.name_ar}</option>)}</select></label>{field('contractStartDate','بداية العقد','date')}{field('contractEndDate','نهاية العقد','date')}{field('actualStartDate','تاريخ المباشرة الفعلي','date')}{field('joinDate','تاريخ الالتحاق','date')}<label className="check-field"><input type="checkbox" checked={form.contractAutoRenew} onChange={e=>setForm((v:any)=>({...v,contractAutoRenew:e.target.checked}))}/><span>تجديد تلقائي للعقد</span></label></div></section>
 <section className="panel"><div className="section-heading"><div><h2>فترة التجربة</h2><span>الحد الأقصى 180 يومًا وتُحتسب من المباشرة الفعلية</span></div></div><div className="form-grid">{field('probationDays','مدة التجربة بالأيام','number')}{field('probationExtensionDays','تمديد إضافي بالأيام','number')}</div></section>
 <section className="panel"><div className="section-heading"><div><h2>التأمينات والبيانات النظامية</h2><span>بيانات اختيارية حسب الشركة والموظف</span></div></div><div className="form-grid">{field('gosiNumber','رقم التأمينات')}{field('residencyClassification','تصنيف سعودي / غير سعودي')}{field('insuranceProfile','ملف التأمين')}{field('identityType','نوع الهوية')}{field('identityIssueDate','تاريخ إصدار الهوية','date')}{field('identityIssuer','جهة إصدار الهوية')}{field('passportNumber','رقم الجواز')}{field('passportIssueDate','إصدار الجواز','date')}{field('passportExpiryDate','انتهاء الجواز','date')}</div></section>
 <section className="panel"><label className="check-field"><input type="checkbox" checked={form.createAccount} onChange={e=>setForm((v:any)=>({...v,createAccount:e.target.checked}))}/><span>إنشاء حساب دخول للموظف باستخدام رقم الهوية / الإقامة</span></label>{form.createAccount&&<p className="form-note">سيتم إنشاء كلمة مرور مؤقتة مشفرة <strong>Mm123456</strong> مع إجبار تغييرها عند أول دخول.</p>}</section>
 {error&&<div className="form-error">{error}</div>}<div className="form-actions"><Link className="btn secondary" to="/employees">إلغاء</Link><button className="btn primary" disabled={saving}><Save size={17}/>{saving?'جارٍ الحفظ...':'حفظ الموظف'}</button></div></form></div>}
