import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, Save, UserPlus } from 'lucide-react';
import { useEffect,useMemo,useState } from 'react';
import { api } from '../lib/api';

const initial:any={employeeNumber:'',firstName:'',fatherName:'',familyName:'',nationalId:'',nationality:'',gender:'',dateOfBirth:'',personalPhone:'',personalEmail:'',shortAddress:'',jobTitle:'',organizationUnitId:'',positionId:'',workLocation:'',employmentType:'full_time',contractType:'',contractStartDate:'',contractEndDate:'',contractDurationMonths:'',contractAutoRenew:false,status:'active',joinDate:'',actualStartDate:'',probationDays:180,probationExtensionDays:0,gosiNumber:'',insuranceProfile:'',professionalHazard:false,createAccount:false};

const countryCodes=`AF AL DZ AS AD AO AI AQ AG AR AM AW AU AT AZ BS BH BD BB BY BE BZ BJ BM BT BO BQ BA BW BV BR IO BN BG BF BI CV KH CM CA KY CF TD CL CN CX CC CO KM CG CD CK CR CI HR CU CW CY CZ DK DJ DM DO EC EG SV GQ ER EE SZ ET FK FO FJ FI FR GF PF TF GA GM GE DE GH GI GR GL GD GP GU GT GG GN GW GY HT HM VA HN HK HU IS IN ID IR IQ IE IM IL IT JM JP JE JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MO MG MW MY MV ML MT MH MQ MR MU YT MX FM MD MC MN ME MS MA MZ MM NA NR NP NL NC NZ NI NE NG NU NF MK MP NO OM PK PW PS PA PG PY PE PH PN PL PT PR QA RE RO RU RW BL SH KN LC MF PM VC WS SM ST SA SN RS SC SL SG SX SK SI SB SO ZA GS SS ES LK SD SR SJ SE CH SY TW TJ TZ TH TL TG TK TO TT TN TR TM TC TV UG UA AE GB US UM UY UZ VU VE VN VG VI WF EH YE ZM ZW`.split(' ');
const regionNames=new (Intl as any).DisplayNames(['ar'],{type:'region'});
const nationalityOptions=countryCodes.map(code=>({code,name:code==='SA'?'سعودي':(regionNames.of(code)||code)})).sort((a,b)=>a.name.localeCompare(b.name,'ar'));
nationalityOptions.unshift({code:'DISPLACED_TRIBES',name:'قبائل نازحة'});

function addMonths(date:string,months:number){const d=new Date(`${date}T00:00:00Z`);if(Number.isNaN(d.getTime())||!Number.isFinite(months)||months<1)return '';const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+months);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.toISOString().slice(0,10)}

export function NewEmployee(){const [form,setForm]=useState(initial);const [units,setUnits]=useState<any[]>([]);const [positions,setPositions]=useState<any[]>([]);const [contracts,setContracts]=useState<any[]>([]);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const navigate=useNavigate();
 useEffect(()=>{Promise.all([api<any>('/api/organization'),api<any>('/api/employees/contract-types')]).then(([o,c])=>{setUnits(o.units||[]);setPositions(o.positions||[]);setContracts(c.items||[])}).catch(()=>setError('تعذر تحميل بيانات الهيكل وأنواع العقود.'))},[]);
 const children=units.filter(x=>x.active);
 const derivedClassification=useMemo(()=>form.nationality==='SA'?'سعودي':form.nationality?'غير سعودي':'',[form.nationality]);
 useEffect(()=>{if(form.nationality!==''&&form.residencyClassification!==derivedClassification)setForm((v:any)=>({...v,residencyClassification:derivedClassification}))},[form.nationality,derivedClassification]);
 useEffect(()=>{if(form.contractAutoRenew&&form.contractStartDate&&Number(form.contractDurationMonths)>0){const end=addMonths(form.contractStartDate,Number(form.contractDurationMonths));setForm((v:any)=>v.contractEndDate===end?v:{...v,contractEndDate:end})}},[form.contractAutoRenew,form.contractStartDate,form.contractDurationMonths]);
 const field=(name:string,label:string,type='text',disabled=false)=><label className="form-field"><span>{label}</span><input type={type} disabled={disabled} value={form[name]??''} onChange={e=>setForm((v:any)=>({...v,[name]:e.target.value}))}/></label>;
 const save=async(e:any)=>{e.preventDefault();setSaving(true);setError('');try{const d=await api<any>('/api/employees',{method:'POST',body:JSON.stringify({...form,probationDays:Number(form.probationDays),probationExtensionDays:Number(form.probationExtensionDays),contractDurationMonths:form.contractDurationMonths?Number(form.contractDurationMonths):null,organizationUnitId:form.organizationUnitId||null,positionId:form.positionId||null,contractType:form.contractType||null,residencyClassification:derivedClassification||null})});navigate(`/employees/${d.id}`)}catch(err:any){setError(err?.message||'تعذر حفظ الموظف.')}finally{setSaving(false)}};
 return <div><div className="page-header"><div><div className="breadcrumbs-inner"><Link to="/employees">الموظفون</Link><ArrowRight size={14}/><span>إضافة موظف</span></div><h1>إضافة موظف</h1><p>إنشاء سجل موظف حقيقي وربطه بالهيكل التنظيمي دون إنشاء بيانات تجريبية.</p></div></div><form onSubmit={save} className="employee-form"><section className="panel"><div className="section-heading"><div><h2><UserPlus size={18}/> البيانات الأساسية</h2><span>رقم الموظف والهوية والاتصال</span></div></div><div className="form-grid">{field('employeeNumber','رقم الموظف')}{field('firstName','الاسم الأول')}{field('fatherName','اسم الأب')}{field('familyName','اسم العائلة')}{field('nationalId','رقم الهوية / الإقامة')}<label className="form-field"><span>الجنسية</span><select value={form.nationality} onChange={e=>setForm((v:any)=>({...v,nationality:e.target.value}))}><option value="">اختر الجنسية</option>{nationalityOptions.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label><label className="form-field"><span>الجنس</span><select value={form.gender} onChange={e=>setForm((v:any)=>({...v,gender:e.target.value}))}><option value="">اختر الجنس</option><option value="male">ذكر</option><option value="female">أنثى</option></select></label>{field('dateOfBirth','تاريخ الميلاد','date')}{field('personalPhone','الجوال')}{field('personalEmail','البريد الإلكتروني','email')}{field('shortAddress','العنوان المختصر')}</div></section>
 <section className="panel"><div className="section-heading"><div><h2>البيانات الوظيفية</h2><span>يرتبط الموظف مباشرة بالهيكل والمناصب في Phase 4</span></div></div><div className="form-grid">{field('jobTitle','المسمى الوظيفي')}{field('workLocation','موقع العمل')}<label className="form-field"><span>الوحدة التنظيمية</span><select value={form.organizationUnitId} onChange={e=>setForm((v:any)=>({...v,organizationUnitId:e.target.value,positionId:''}))}><option value="">اختر الوحدة</option>{children.map(u=><option key={u.id} value={u.id}>{u.name_ar}</option>)}</select></label><label className="form-field"><span>المنصب</span><select value={form.positionId} onChange={e=>setForm((v:any)=>({...v,positionId:e.target.value}))}><option value="">اختر المنصب</option>{positions.filter(p=>!form.organizationUnitId||p.organization_unit_id===form.organizationUnitId).map(p=><option key={p.id} value={p.id}>{p.title_ar}{p.code?` — ${p.code}`:''}</option>)}</select></label><label className="form-field"><span>نوع التوظيف</span><select value={form.employmentType} onChange={e=>setForm((v:any)=>({...v,employmentType:e.target.value}))}><option value="full_time">دوام كامل</option><option value="part_time">دوام جزئي</option><option value="training">تدريب</option><option value="tamheer">تمهير</option></select></label><label className="form-field"><span>نوع العقد</span><select value={form.contractType} onChange={e=>setForm((v:any)=>({...v,contractType:e.target.value}))}><option value="">اختر</option>{contracts.map(x=><option key={x.code} value={x.code}>{x.name_ar}</option>)}</select></label>{field('contractStartDate','بداية العقد','date')}{field('contractDurationMonths','مدة العقد بالأشهر','number')}{field('contractEndDate','نهاية العقد','date',form.contractAutoRenew)}{field('actualStartDate','تاريخ المباشرة الفعلي','date')}{field('joinDate','تاريخ الالتحاق','date')}<label className="check-field"><input type="checkbox" checked={form.contractAutoRenew} onChange={e=>setForm((v:any)=>({...v,contractAutoRenew:e.target.checked}))}/><span>تجديد تلقائي للعقد</span></label>{form.contractAutoRenew&&<p className="form-note">سيتم احتساب تاريخ نهاية العقد تلقائيًا من بداية العقد ومدة العقد، ولا يمكن تعديله يدويًا.</p>}</div></section>
 <section className="panel"><div className="section-heading"><div><h2>فترة التجربة</h2><span>الحد الأقصى 180 يومًا وتُحتسب من المباشرة الفعلية</span></div></div><div className="form-grid">{field('probationDays','مدة التجربة بالأيام','number')}{field('probationExtensionDays','تمديد إضافي بالأيام','number')}</div></section>
 <section className="panel"><div className="section-heading"><div><h2>التأمينات والبيانات النظامية</h2><span>تصنيف التأمينات يُستنتج تلقائيًا من الجنسية</span></div></div><div className="form-grid">{field('gosiNumber','رقم التأمينات')}<label className="form-field"><span>تصنيف التأمينات</span><input value={derivedClassification||'سيُحدد من الجنسية'} disabled /></label>{field('insuranceProfile','ملف التأمين')}{field('identityType','نوع الهوية')}{field('identityIssueDate','تاريخ إصدار الهوية','date')}{field('identityIssuer','جهة إصدار الهوية')}{field('passportNumber','رقم الجواز')}{field('passportIssueDate','إصدار الجواز','date')}{field('passportExpiryDate','انتهاء الجواز','date')}</div></section>
 <section className="panel"><label className="check-field"><input type="checkbox" checked={form.createAccount} onChange={e=>setForm((v:any)=>({...v,createAccount:e.target.checked}))}/><span>إنشاء حساب دخول للموظف باستخدام رقم الهوية / الإقامة</span></label>{form.createAccount&&<p className="form-note">سيتم إنشاء كلمة مرور مؤقتة مشفرة <strong>Mm123456</strong> مع إجبار تغييرها عند أول دخول.</p>}</section>
 {error&&<div className="form-error">{error}</div>}<div className="form-actions"><Link className="btn secondary" to="/employees">إلغاء</Link><button className="btn primary" disabled={saving}><Save size={17}/>{saving?'جارٍ الحفظ...':'حفظ الموظف'}</button></div></form></div>}
