import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Building2, ChevronDown, Download, Edit3, GitBranch, Plus, Search, UserCog, Users, X, Maximize2, RefreshCw } from 'lucide-react';
import { api } from '../lib/api';

type Unit={id:string;parent_id:string|null;name_ar:string;name_en:string|null;level_name:string|null;code:string|null;active:number;position_count:number;occupied_count:number;vacant_count:number;frozen_count:number};
type Position={id:string;organization_unit_id:string;title_ar:string;title_en:string|null;code:string|null;status:'vacant'|'occupied'|'frozen';manager_position_id:string|null;organization_unit_name:string;manager_title_ar:string|null};
type OrgData={units:Unit[];stats:{unit_count:number;position_count:number;occupied_count:number;vacant_count:number;frozen_count:number}};
type PositionPage={results:Position[];total:number;page:number;pageSize:number};
const statusLabel={vacant:'شاغر',occupied:'مشغول',frozen:'مجمّد'};
const NODE_W=286, NODE_H=158, H_GAP=42, V_GAP=72, ROOT_GAP=82;
type LayoutNode={unit:Unit;x:number;y:number;center:number};
type Layout={nodes:LayoutNode[];edges:{px:number;py:number;cx:number;cy:number}[];width:number;height:number};

export function Organization(){
 const [data,setData]=useState<OrgData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState('');
 const [showUnit,setShowUnit]=useState(false),[showPosition,setShowPosition]=useState(false),[editingUnit,setEditingUnit]=useState<Unit|null>(null),[editingPosition,setEditingPosition]=useState<Position|null>(null),[busy,setBusy]=useState(false);
 const [collapsed,setCollapsed]=useState<Set<string>>(new Set()),[selectedUnitId,setSelectedUnitId]=useState('');
 const [positionPage,setPositionPage]=useState<PositionPage>({results:[],total:0,page:1,pageSize:25}),[positionLoading,setPositionLoading]=useState(false),[positionSearch,setPositionSearch]=useState(''),[positionStatus,setPositionStatus]=useState(''),[positionPageNo,setPositionPageNo]=useState(1),[positionReload,setPositionReload]=useState(0),[managerOptions,setManagerOptions]=useState<Position[]>([]);
 const [unitName,setUnitName]=useState(''),[unitNameEn,setUnitNameEn]=useState(''),[unitLevel,setUnitLevel]=useState(''),[unitCode,setUnitCode]=useState(''),[unitParent,setUnitParent]=useState(''),[unitActive,setUnitActive]=useState(true);
 const [posUnit,setPosUnit]=useState(''),[posTitle,setPosTitle]=useState(''),[posTitleEn,setPosTitleEn]=useState(''),[posCode,setPosCode]=useState(''),[posStatus,setPosStatus]=useState<Position['status']>('vacant'),[posManager,setPosManager]=useState('');
 const load=async()=>{setLoading(true);setError('');try{setData(await api<OrgData>('/api/organization'))}catch(e){setError(e instanceof Error&&e.message==='ORG-010'?'لا تملك صلاحية عرض الهيكل التنظيمي.':'تعذر تحميل الهيكل التنظيمي.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const units=data?.units??[];
 const normalizedSearch=search.trim().toLocaleLowerCase('ar');
 const matches=(text:string)=>!normalizedSearch||text.toLocaleLowerCase('ar').includes(normalizedSearch);
 const roots=useMemo(()=>units.filter(u=>!u.parent_id),[units]);
 const children=useMemo(()=>{const m=new Map<string,Unit[]>();for(const u of units)if(u.parent_id){const a=m.get(u.parent_id)||[];a.push(u);m.set(u.parent_id,a)}return m},[units]);
 const unitMap=useMemo(()=>new Map(units.map(u=>[u.id,u])),[units]);
 function unitHasMatch(u:Unit):boolean{if(matches(`${u.name_ar} ${u.name_en||''} ${u.code||''}`))return true;return (children.get(u.id)||[]).some(unitHasMatch)}
 useEffect(()=>{if(!normalizedSearch)return;const next=new Set<string>();for(const u of units)if(!unitHasMatch(u))next.add(u.id);for(const u of units)if(unitHasMatch(u)&&u.parent_id){let p=u.parent_id;while(p){next.delete(p);p=unitMap.get(p)?.parent_id||''}}setCollapsed(next)},[normalizedSearch,units,unitMap]);
 function toggleUnit(id:string){setCollapsed(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next})}
 function expandAll(){setCollapsed(new Set())}
 function collapseAll(){setCollapsed(new Set(units.filter(u=>(children.get(u.id)||[]).length>0).map(u=>u.id)))}
 function selectUnit(id:string){setSelectedUnitId(id);setPositionPageNo(1);setPositionSearch('');setPositionStatus('');window.setTimeout(()=>document.getElementById('position-explorer')?.scrollIntoView({behavior:'smooth',block:'start'}),30)}
 async function loadPositions(){setPositionLoading(true);try{const qs=new URLSearchParams({page:String(positionPageNo),pageSize:'25'});if(selectedUnitId)qs.set('unitId',selectedUnitId);if(positionSearch.trim())qs.set('q',positionSearch.trim());if(positionStatus)qs.set('status',positionStatus);setPositionPage(await api<PositionPage>(`/api/organization/positions?${qs.toString()}`))}catch(e){setError(errorText(e))}finally{setPositionLoading(false)}}
 useEffect(()=>{void loadPositions()},[selectedUnitId,positionSearch,positionStatus,positionPageNo,positionReload]);
 async function loadManagerOptions(){try{const r=await api<PositionPage>('/api/organization/positions?page=1&pageSize=50');setManagerOptions(r.results)}catch{setManagerOptions([])}}
 function openUnit(unit?:Unit,parentId?:string){setEditingUnit(unit||null);setUnitName(unit?.name_ar||'');setUnitNameEn(unit?.name_en||'');setUnitLevel(unit?.level_name||'');setUnitCode(unit?.code||'');setUnitParent(unit?.parent_id||parentId||'');setUnitActive(unit?Boolean(unit.active):true);setShowUnit(true);setError('')}
 async function openPosition(pos?:Position,unitId?:string){setEditingPosition(pos||null);setPosUnit(pos?.organization_unit_id||unitId||units.find(u=>u.active)?.id||'');setPosTitle(pos?.title_ar||'');setPosTitleEn(pos?.title_en||'');setPosCode(pos?.code||'');setPosStatus(pos?.status||'vacant');setPosManager(pos?.manager_position_id||'');setShowPosition(true);setError('');await loadManagerOptions()}
 async function saveUnit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const body={nameAr:unitName,nameEn:unitNameEn||null,levelName:unitLevel,code:unitCode||null,parentId:unitParent||null,active:unitActive};if(editingUnit)await api(`/api/organization/units/${editingUnit.id}`,{method:'PATCH',body:JSON.stringify(body)});else await api('/api/organization/units',{method:'POST',body:JSON.stringify(body)});setShowUnit(false);await load();setPositionReload(v=>v+1)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function savePosition(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const body={organizationUnitId:posUnit,titleAr:posTitle,titleEn:posTitleEn||null,code:posCode||null,status:posStatus,managerPositionId:posManager||null};if(editingPosition)await api(`/api/organization/positions/${editingPosition.id}`,{method:'PATCH',body:JSON.stringify(body)});else await api('/api/organization/positions',{method:'POST',body:JSON.stringify(body)});setShowPosition(false);await load();setPositionReload(v=>v+1)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function changeManager(p:Position){const manager=window.prompt('معرّف منصب المدير (اتركه فارغًا لإزالة المدير)',p.manager_position_id||'');if(manager===null)return;try{await api(`/api/organization/positions/${p.id}/manager`,{method:'PATCH',body:JSON.stringify({managerPositionId:manager.trim()||null})});setPositionReload(v=>v+1)}catch(e){setError(errorText(e))}}
 const errorText=(e:any)=>{const code=e instanceof Error?e.message:'';const map:any={'ORG-004':'لا يمكن نقل الوحدة إلى نفسها أو أحد فروعها.','ORG-003':'الوحدة الأب غير صالحة.','ORG-007':'لا يمكن إنشاء علاقة إدارية دائرية.','ORG-008':'رمز المنصب مستخدم مسبقًا.','ORG-005':'لا يمكن استخدام سجل من شركة أخرى.','ORG-010':'لا تملك الصلاحية المطلوبة.'};return map[code]||'تعذر حفظ التغيير.'};
 const layout=useMemo<Layout>(()=>{const visible=(u:Unit)=>unitHasMatch(u);const nodes:LayoutNode[]=[];const edges:{px:number;py:number;cx:number;cy:number}[]=[];const subtreeWidth=(u:Unit):number=>{const kids=(children.get(u.id)||[]).filter(visible);if(!kids.length||collapsed.has(u.id))return NODE_W;return Math.max(NODE_W,kids.reduce((sum,k)=>sum+subtreeWidth(k),0)+H_GAP*(kids.length-1))};const place=(u:Unit,x:number,depth:number)=>{const width=subtreeWidth(u);const y=depth*(NODE_H+V_GAP);const center=x+width/2;nodes.push({unit:u,x:center-NODE_W/2,y,center});const kids=(children.get(u.id)||[]).filter(visible);if(kids.length&&!collapsed.has(u.id)){let childX=x;for(const k of kids){const w=subtreeWidth(k);place(k,childX,depth+1);childX+=w+H_GAP}for(const k of kids){const kn=nodes.find(n=>n.unit.id===k.id);if(kn)edges.push({px:center,py:y+NODE_H,cx:kn.center,cy:kn.y})}}return width};let cursor=0;for(const r of roots.filter(visible)){const w=place(r,cursor,0);cursor+=w+ROOT_GAP}const width=Math.max(NODE_W,cursor?cursor-ROOT_GAP:0)+80;const maxY=nodes.reduce((m,n)=>Math.max(m,n.y),0);return {nodes,edges,width,height:maxY+NODE_H+48}},[units,children,collapsed,normalizedSearch]);
 const selectedUnit=unitMap.get(selectedUnitId);const totalPages=Math.max(1,Math.ceil(positionPage.total/positionPage.pageSize));
 return <div>
  <div className="page-header"><div><div className="eyebrow">الهيكل المؤسسي</div><h1>الهيكل التنظيمي</h1><p>الوحدات في الشجرة، والمناصب في مستكشف سريع مصمم للتوسع مع البيانات.</p></div><div className="header-actions"><button className="btn secondary" onClick={()=>window.location.href='/api/organization/export'}><Download size={16}/> تصدير</button><button className="btn secondary" onClick={()=>openUnit()}><Plus size={16}/> وحدة تنظيمية</button><button className="btn primary" onClick={()=>openPosition()} disabled={!units.some(u=>u.active)}><Plus size={16}/> منصب</button></div></div>
  {error&&<div className="login-error page-error">{error}</div>}
  <div className="org-toolbar"><div className="search-field"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث عن وحدة تنظيمية..."/></div><div className="org-toolbar-actions"><button className="org-view-btn" onClick={expandAll}>توسيع الكل</button><button className="org-view-btn" onClick={collapseAll}>طي الكل</button><button className="org-view-btn" onClick={()=>document.getElementById('org-chart')?.requestFullscreen?.()}><Maximize2 size={14}/> ملء الشاشة</button><div className="header-status"><GitBranch size={16}/> {data?.stats.unit_count||0} وحدة · {data?.stats.position_count||0} منصب</div></div></div>
  {loading?<div className="panel-empty">جاري تحميل الهيكل...</div>:<>
   <section id="org-chart" className="panel org-chart-panel phase4-org"><div className="panel-head"><div><h3>شجرة التنظيم</h3><p>الوحدات فقط داخل الشجرة؛ المناصب تُدار من المستكشف أسفلها حتى تظل التجربة سريعة مع مئات المناصب.</p></div><span className="org-chart-caption">مباشر من D1</span></div>{roots.length===0?<div className="state-card"><div className="state-icon"><DatabaseIcon/></div><h3>لا توجد وحدات تنظيمية</h3><p>ابدأ بإنشاء أول وحدة تنظيمية للشركة.</p><button className="btn primary" onClick={()=>openUnit()}><Plus size={16}/> إنشاء وحدة</button></div>:<div className="org-chart-scroll"><div className="org-tree-stage" style={{width:layout.width,height:layout.height}}><svg className="org-tree-svg" width={layout.width} height={layout.height} aria-hidden="true"><g>{layout.edges.map((e,i)=>{const mid=e.py+(e.cy-e.py)/2;return <path key={i} d={Math.abs(e.cx-e.px)<1?`M ${e.px} ${e.py} V ${e.cy}`:`M ${e.px} ${e.py} V ${mid} M ${e.px} ${mid} H ${e.cx} M ${e.cx} ${mid} V ${e.cy}`} />})}</g></svg>{layout.nodes.map(n=>{const unit=n.unit;const kids=(children.get(unit.id)||[]).filter(unitHasMatch);const isCollapsed=collapsed.has(unit.id);const directMatch=matches(`${unit.name_ar} ${unit.name_en||''} ${unit.code||''}`);return <article key={unit.id} className={`org-node-card org-absolute-node ${directMatch&&normalizedSearch?'search-hit':''} ${unit.active?'':'is-inactive'} ${unit.id===roots[0]?.id?'is-root':''} ${selectedUnitId===unit.id?'is-selected':''}`} style={{left:n.x,top:n.y}} onClick={()=>selectUnit(unit.id)}><div className="org-node-topline"><span className="org-node-level">{unit.level_name||'وحدة تنظيمية'}</span><span className="org-node-code">{unit.code||'—'}</span></div><div className="org-node-title-row"><span className="org-node-icon"><Building2 size={17}/></span><div className="org-node-title"><strong>{unit.name_ar}</strong>{unit.name_en&&<small>{unit.name_en}</small>}</div><button className={`org-node-toggle ${isCollapsed?'is-collapsed':''}`} title={isCollapsed?'توسيع':'طي'} onClick={e=>{e.stopPropagation();toggleUnit(unit.id)}} disabled={!kids.length}>{kids.length?<ChevronDown size={16}/>:<span className="org-no-children"/>}</button></div><div className="org-node-metrics"><span><b>{unit.position_count||0}</b> منصب</span><span className="occupied"><b>{unit.occupied_count||0}</b> مشغول</span><span className="vacant"><b>{unit.vacant_count||0}</b> شاغر</span></div><div className="org-node-footer"><span>{kids.length} وحدة فرعية</span><div className="org-node-actions"><button className="icon-btn compact" title="تعديل الوحدة" onClick={e=>{e.stopPropagation();openUnit(unit)}}><Edit3 size={14}/></button><button className="icon-btn compact" title="إضافة وحدة فرعية" onClick={e=>{e.stopPropagation();openUnit(undefined,unit.id)}}><Plus size={14}/></button></div></div></article>})}</div></div>}</section>
   <section id="position-explorer" className="panel position-explorer"><div className="panel-head"><div><h3>مستكشف المناصب</h3><p>{selectedUnit?`عرض المناصب داخل «${selectedUnit.name_ar}»`:'كل المناصب'} · يتم تحميل 25 سجلًا فقط في كل صفحة.</p></div><div className="explorer-actions"><button className="org-view-btn" onClick={()=>setPositionReload(v=>v+1)}><RefreshCw size={14}/> تحديث</button><button className="btn primary" onClick={()=>openPosition(undefined,selectedUnitId||undefined)} disabled={!units.some(u=>u.active)}><Plus size={15}/> إضافة منصب</button></div></div>
    <div className="position-explorer-toolbar"><div className="search-field"><Search size={16}/><input value={positionSearch} onChange={e=>{setPositionSearch(e.target.value);setPositionPageNo(1)}} placeholder="ابحث عن منصب، رمز، أو وحدة..."/></div><select value={positionStatus} onChange={e=>{setPositionStatus(e.target.value);setPositionPageNo(1)}}><option value="">كل الحالات</option><option value="occupied">مشغول</option><option value="vacant">شاغر</option><option value="frozen">مجمّد</option></select><button className="org-view-btn" onClick={()=>{setSelectedUnitId('');setPositionPageNo(1)}} disabled={!selectedUnitId}>كل الوحدات</button></div>
    {positionLoading?<div className="panel-empty">جاري تحميل المناصب...</div>:positionPage.results.length===0?<div className="panel-empty">لا توجد مناصب مطابقة للبحث الحالي.</div>:<><div className="position-table-wrap"><table className="position-table"><thead><tr><th>المنصب</th><th>الوحدة</th><th>الحالة</th><th>المدير المباشر</th><th>الرمز</th><th></th></tr></thead><tbody>{positionPage.results.map(p=><tr key={p.id}><td><strong>{p.title_ar}</strong>{p.title_en&&<small>{p.title_en}</small>}</td><td>{p.organization_unit_name}</td><td><span className={`badge ${p.status==='occupied'?'success':p.status==='frozen'?'danger':'neutral'}`}>{statusLabel[p.status]}</span></td><td>{p.manager_title_ar||'—'}</td><td className="mono">{p.code||'—'}</td><td><div className="table-actions"><button className="icon-btn compact" title="تعديل" onClick={()=>openPosition(p)}><Edit3 size={14}/></button><button className="icon-btn compact" title="تعيين المدير" onClick={()=>void changeManager(p)}><Users size={14}/></button></div></td></tr>)}</tbody></table></div><div className="pagination"><span>عرض {(positionPage.page-1)*positionPage.pageSize+1}–{Math.min(positionPage.page*positionPage.pageSize,positionPage.total)} من {positionPage.total}</span><div><button disabled={positionPage.page<=1} onClick={()=>setPositionPageNo(v=>Math.max(1,v-1))}>السابق</button><span className="page-number">{positionPage.page} / {totalPages}</span><button disabled={positionPage.page>=totalPages} onClick={()=>setPositionPageNo(v=>Math.min(totalPages,v+1))}>التالي</button></div></div></>}
   </section>
   <div className="org-summary"><div><span><Users size={17}/>مشغولة</span><strong>{data?.stats.occupied_count??0}</strong></div><div><span><Building2 size={17}/>شاغرة</span><strong>{data?.stats.vacant_count??0}</strong></div><div><span><ChevronDown size={17}/>مجمّدة</span><strong>{data?.stats.frozen_count??0}</strong></div></div>
  </>}
  {showUnit&&<div className="modal-backdrop"><form className="access-modal wide-modal" onSubmit={saveUnit}><button type="button" className="modal-close" onClick={()=>setShowUnit(false)}><X size={18}/></button><div className="modal-icon pending"><Building2 size={23}/></div><h3>{editingUnit?'تعديل وحدة تنظيمية':'إنشاء وحدة تنظيمية'}</h3><div className="modal-form-grid"><label className="modal-field">اسم الوحدة<input required value={unitName} onChange={e=>setUnitName(e.target.value)}/></label><label className="modal-field">الاسم بالإنجليزية<input value={unitNameEn} onChange={e=>setUnitNameEn(e.target.value)}/></label><label className="modal-field">المستوى التنظيمي<input required value={unitLevel} onChange={e=>setUnitLevel(e.target.value)} placeholder="إدارة / قسم / قطاع..."/></label><label className="modal-field">الرمز<input value={unitCode} onChange={e=>setUnitCode(e.target.value)}/></label><label className="modal-field">الوحدة الأب<select value={unitParent} onChange={e=>setUnitParent(e.target.value)}><option value="">بدون أب (جذر)</option>{units.filter(u=>u.id!==editingUnit?.id&&u.active).map(u=><option key={u.id} value={u.id}>{u.name_ar}</option>)}</select></label>{editingUnit&&<label className="check-row"><input type="checkbox" checked={unitActive} onChange={e=>setUnitActive(e.target.checked)}/><span>الوحدة نشطة</span></label>}</div><div className="form-actions"><button type="button" className="btn secondary" onClick={()=>setShowUnit(false)}>إلغاء</button><button className="btn primary" disabled={busy}>{busy?'جارٍ الحفظ...':'حفظ الوحدة'}</button></div></form></div>}
  {showPosition&&<div className="modal-backdrop"><form className="access-modal wide-modal" onSubmit={savePosition}><button type="button" className="modal-close" onClick={()=>setShowPosition(false)}><X size={18}/></button><div className="modal-icon pending"><UserCog size={23}/></div><h3>{editingPosition?'تعديل منصب':'إنشاء منصب'}</h3><div className="modal-form-grid"><label className="modal-field">الوحدة التنظيمية<select required value={posUnit} onChange={e=>setPosUnit(e.target.value)}><option value="">اختر الوحدة</option>{units.filter(u=>u.active).map(u=><option key={u.id} value={u.id}>{u.name_ar}</option>)}</select></label><label className="modal-field">اسم المنصب<input required value={posTitle} onChange={e=>setPosTitle(e.target.value)}/></label><label className="modal-field">الاسم بالإنجليزية<input value={posTitleEn} onChange={e=>setPosTitleEn(e.target.value)}/></label><label className="modal-field">الرمز<input value={posCode} onChange={e=>setPosCode(e.target.value)}/></label><label className="modal-field">الحالة<select value={posStatus} onChange={e=>setPosStatus(e.target.value as Position['status'])}><option value="vacant">شاغر</option><option value="occupied">مشغول</option><option value="frozen">مجمّد</option></select></label><label className="modal-field">المدير المباشر<select value={posManager} onChange={e=>setPosManager(e.target.value)}><option value="">بدون مدير</option>{managerOptions.filter(p=>p.id!==editingPosition?.id).map(p=><option key={p.id} value={p.id}>{p.title_ar} — {p.organization_unit_name}</option>)}</select></label></div><p className="form-hint">حالة «مشغول» لا تنشئ موظفًا تلقائيًا؛ الربط بالموظف يتم في مرحلة Employee Master.</p><div className="form-actions"><button type="button" className="btn secondary" onClick={()=>setShowPosition(false)}>إلغاء</button><button className="btn primary" disabled={busy}>{busy?'جارٍ الحفظ...':'حفظ المنصب'}</button></div></form></div>}
 </div>
}
function DatabaseIcon(){return <Building2 size={22}/>}
