import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Building2, ChevronDown, Download, Edit3, GitBranch, Plus, Search, UserCog, Users, X } from 'lucide-react';
import { api } from '../lib/api';

type Unit={id:string;parent_id:string|null;name_ar:string;name_en:string|null;level_name:string|null;code:string|null;active:number;position_count:number};
type Position={id:string;organization_unit_id:string;title_ar:string;title_en:string|null;code:string|null;status:'vacant'|'occupied'|'frozen';manager_position_id:string|null;organization_unit_name:string;manager_title_ar:string|null};
type OrgData={units:Unit[];positions:Position[];stats:{unit_count:number;position_count:number;occupied_count:number;vacant_count:number;frozen_count:number}};
const statusLabel={vacant:'شاغر',occupied:'مشغول',frozen:'مجمّد'};

export function Organization(){
 const [data,setData]=useState<OrgData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[showUnit,setShowUnit]=useState(false),[showPosition,setShowPosition]=useState(false),[editingUnit,setEditingUnit]=useState<Unit|null>(null),[editingPosition,setEditingPosition]=useState<Position|null>(null),[busy,setBusy]=useState(false);
 const [collapsed,setCollapsed]=useState<Set<string>>(new Set());
 const [unitName,setUnitName]=useState(''),[unitNameEn,setUnitNameEn]=useState(''),[unitLevel,setUnitLevel]=useState(''),[unitCode,setUnitCode]=useState(''),[unitParent,setUnitParent]=useState(''),[unitActive,setUnitActive]=useState(true);
 const [posUnit,setPosUnit]=useState(''),[posTitle,setPosTitle]=useState(''),[posTitleEn,setPosTitleEn]=useState(''),[posCode,setPosCode]=useState(''),[posStatus,setPosStatus]=useState<Position['status']>('vacant'),[posManager,setPosManager]=useState('');
 const load=async()=>{setLoading(true);setError('');try{setData(await api<OrgData>('/api/organization'))}catch(e){setError(e instanceof Error&&e.message==='ORG-010'?'لا تملك صلاحية عرض الهيكل التنظيمي.':'تعذر تحميل الهيكل التنظيمي.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const units=data?.units??[],positions=data?.positions??[];
 const matches=(text:string)=>!search||text.toLocaleLowerCase('ar').includes(search.toLocaleLowerCase('ar'));
 const roots=useMemo(()=>units.filter(u=>!u.parent_id),[units]);
 const children=useMemo(()=>{const m=new Map<string,Unit[]>();for(const u of units)if(u.parent_id){const a=m.get(u.parent_id)||[];a.push(u);m.set(u.parent_id,a)}return m},[units]);
 const positionsByUnit=useMemo(()=>{const m=new Map<string,Position[]>();for(const p of positions){const a=m.get(p.organization_unit_id)||[];a.push(p);m.set(p.organization_unit_id,a)}return m},[positions]);
 function unitHasMatch(u:Unit):boolean{if(matches(`${u.name_ar} ${u.name_en||''} ${u.code||''}`))return true;return (children.get(u.id)||[]).some(unitHasMatch)}
 function positionHasMatch(p:Position){return matches(`${p.title_ar} ${p.title_en||''} ${p.code||''} ${p.organization_unit_name}`)}
 function collectAncestors(id:string,set:Set<string>){const unit=units.find(u=>u.id===id);if(!unit?.parent_id)return;set.delete(unit.parent_id);collectAncestors(unit.parent_id,set)}
 useEffect(()=>{if(!search)return;const next=new Set(collapsed);for(const u of units){if(unitHasMatch(u))continue;next.add(u.id)};for(const p of positions){if(positionHasMatch(p)){const unit=units.find(u=>u.id===p.organization_unit_id);if(unit)collectAncestors(unit.id,next)}}setCollapsed(next)},[search,units,positions]);
 function toggleUnit(id:string){setCollapsed(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next})}
 function expandAll(){setCollapsed(new Set())}
 function collapseAll(){setCollapsed(new Set(units.filter(u=>(children.get(u.id)||[]).length>0).map(u=>u.id)))}
 function openUnit(unit?:Unit,parentId?:string){setEditingUnit(unit||null);setUnitName(unit?.name_ar||'');setUnitNameEn(unit?.name_en||'');setUnitLevel(unit?.level_name||'');setUnitCode(unit?.code||'');setUnitParent(unit?.parent_id||parentId||'');setUnitActive(unit?Boolean(unit.active):true);setShowUnit(true);setError('')}
 function openPosition(pos?:Position,unitId?:string){setEditingPosition(pos||null);setPosUnit(pos?.organization_unit_id||unitId||units.find(u=>u.active)?.id||'');setPosTitle(pos?.title_ar||'');setPosTitleEn(pos?.title_en||'');setPosCode(pos?.code||'');setPosStatus(pos?.status||'vacant');setPosManager(pos?.manager_position_id||'');setShowPosition(true);setError('')}
 async function saveUnit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const body={nameAr:unitName,nameEn:unitNameEn||null,levelName:unitLevel,code:unitCode||null,parentId:unitParent||null,active:unitActive};if(editingUnit)await api(`/api/organization/units/${editingUnit.id}`,{method:'PATCH',body:JSON.stringify(body)});else await api('/api/organization/units',{method:'POST',body:JSON.stringify(body)});setShowUnit(false);await load()}catch(e){setError(errorText(e));}finally{setBusy(false)}}
 async function savePosition(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const body={organizationUnitId:posUnit,titleAr:posTitle,titleEn:posTitleEn||null,code:posCode||null,status:posStatus,managerPositionId:posManager||null};if(editingPosition)await api(`/api/organization/positions/${editingPosition.id}`,{method:'PATCH',body:JSON.stringify(body)});else await api('/api/organization/positions',{method:'POST',body:JSON.stringify(body)});setShowPosition(false);await load()}catch(e){setError(errorText(e));}finally{setBusy(false)}}
 async function changeManager(p:Position){const manager=window.prompt('معرّف منصب المدير (اتركه فارغًا لإزالة المدير)',p.manager_position_id||'');if(manager===null)return;try{await api(`/api/organization/positions/${p.id}/manager`,{method:'PATCH',body:JSON.stringify({managerPositionId:manager.trim()||null})});await load()}catch(e){setError(errorText(e))}}
 const errorText=(e:any)=>{const code=e instanceof Error?e.message:'';const map:any={'ORG-004':'لا يمكن نقل الوحدة إلى نفسها أو أحد فروعها.','ORG-003':'الوحدة الأب غير صالحة.','ORG-007':'لا يمكن إنشاء علاقة إدارية دائرية.','ORG-008':'رمز المنصب مستخدم مسبقًا.','ORG-005':'لا يمكن استخدام سجل من شركة أخرى.','ORG-010':'لا تملك الصلاحية المطلوبة.'};return map[code]||'تعذر حفظ التغيير.'};
 function Node({unit}:{unit:Unit}){
   const kids=children.get(unit.id)||[], nodePositions=positionsByUnit.get(unit.id)||[], isCollapsed=collapsed.has(unit.id), directMatch=matches(`${unit.name_ar} ${unit.name_en||''} ${unit.code||''}`), visible=unitHasMatch(unit);
   if(!visible)return null;
   return <div className="org-chart-node">
     <article className={`org-node-card ${directMatch&&search?'search-hit':''} ${unit.active?'':'is-inactive'}`}>
       <div className="org-node-topline"><span className="org-node-level">{unit.level_name||'وحدة تنظيمية'}</span><span className="org-node-code">{unit.code||'—'}</span></div>
       <div className="org-node-title-row"><span className="org-node-icon"><Building2 size={17}/></span><div className="org-node-title"><strong>{unit.name_ar}</strong>{unit.name_en&&<small>{unit.name_en}</small>}</div><button className="org-node-toggle" title={isCollapsed?'توسيع':'طي'} onClick={()=>toggleUnit(unit.id)} disabled={!kids.length}>{kids.length?<ChevronDown size={16}/>:<span className="org-no-children"/>}</button></div>
       <div className="org-node-footer"><span>{kids.length} وحدة فرعية</span><span>{unit.position_count} منصب</span><div className="org-node-actions"><button className="icon-btn compact" title="تعديل الوحدة" onClick={()=>openUnit(unit)}><Edit3 size={14}/></button><button className="icon-btn compact" title="إضافة وحدة فرعية" onClick={()=>openUnit(undefined,unit.id)}><Plus size={14}/></button></div></div>
       {nodePositions.length>0&&<div className="org-node-positions">{nodePositions.slice(0,3).map(p=><span key={p.id} className={`org-mini-position ${p.status}`}><UserCog size={12}/>{p.title_ar}</span>)}{nodePositions.length>3&&<span className="org-mini-more">+{nodePositions.length-3}</span>}</div>}
     </article>
     {!isCollapsed&&kids.length>0&&<div className="org-children-grid">{kids.map((k,i)=><div className="org-child-branch" key={k.id}><span className="org-branch-stem"/><Node unit={k}/></div>)}</div>}
   </div>
 }
 return <div><div className="page-header"><div><div className="eyebrow">الهيكل المؤسسي</div><h1>الهيكل التنظيمي</h1><p>هيكل هرمي فعلي من بيانات الشركة، مع وحدات ومناصب وعلاقات إدارية.</p></div><div className="header-actions"><button className="btn secondary" onClick={()=>window.location.href='/api/organization/export'}><Download size={16}/> تصدير</button><button className="btn secondary" onClick={()=>openUnit()}><Plus size={16}/> وحدة تنظيمية</button><button className="btn primary" onClick={()=>openPosition()} disabled={!units.some(u=>u.active)}><Plus size={16}/> منصب</button></div></div>
 {error&&<div className="login-error page-error">{error}</div>}
 <div className="org-toolbar"><div className="search-field"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث عن وحدة أو منصب..."/></div><div className="org-toolbar-actions"><button className="org-view-btn" onClick={expandAll}>توسيع الكل</button><button className="org-view-btn" onClick={collapseAll}>طي الكل</button><div className="header-status"><GitBranch size={16}/> {data?.stats.unit_count||0} وحدة · {data?.stats.position_count||0} منصب</div></div></div>
 {loading?<div className="panel-empty">جاري تحميل الهيكل...</div>:<div className="org-layout phase4-org"><section className="panel org-chart-panel"><div className="panel-head"><div><h3>شجرة التنظيم</h3><p>كل خط يظهر فقط عندما توجد علاقة أب وابن فعلية.</p></div><span className="org-chart-caption">مباشر من D1</span></div>{roots.length===0?<div className="state-card"><div className="state-icon"><DatabaseIcon/></div><h3>لا توجد وحدات تنظيمية</h3><p>ابدأ بإنشاء أول وحدة تنظيمية للشركة.</p><button className="btn primary" onClick={()=>openUnit()}><Plus size={16}/> إنشاء وحدة</button></div>:<div className="org-chart-scroll"><div className="org-chart-canvas">{roots.map(u=><Node key={u.id} unit={u}/>)}</div></div>}</section><section className="panel"><div className="panel-head"><div><h3>المناصب</h3><p>المناصب مستقلة عن سجلات الموظفين، وحالة الإشغال محفوظة فعليًا.</p></div></div>{positions.filter(positionHasMatch).length===0?<div className="panel-empty">لا توجد مناصب مطابقة.</div>:<div className="position-list">{positions.filter(positionHasMatch).map(p=><div className={`position-card ${p.status} ${search&&positionHasMatch(p)?'search-hit':''}`} key={p.id}><div className="position-main"><div className="position-icon"><UserCog size={17}/></div><div><strong>{p.title_ar}</strong><span>{p.organization_unit_name}{p.code?` · ${p.code}`:''}</span><small>{p.manager_title_ar?`المدير: ${p.manager_title_ar}`:'بدون مدير مباشر'}</small></div></div><div className="position-actions"><span className={`badge ${p.status==='occupied'?'success':p.status==='frozen'?'danger':'neutral'}`}>{statusLabel[p.status]}</span><button className="icon-btn compact" title="تعديل" onClick={()=>openPosition(p)}><Edit3 size={14}/></button><button className="icon-btn compact" title="تعيين المدير" onClick={()=>void changeManager(p)}><Users size={14}/></button></div></div>)}</div>}</section></div>}
 <div className="org-summary"><div><span><Users size={17}/>مشغولة</span><strong>{data?.stats.occupied_count??0}</strong></div><div><span><Building2 size={17}/>شاغرة</span><strong>{data?.stats.vacant_count??0}</strong></div><div><span><ChevronDown size={17}/>مجمّدة</span><strong>{data?.stats.frozen_count??0}</strong></div></div>
 {showUnit&&<div className="modal-backdrop"><form className="access-modal wide-modal" onSubmit={saveUnit}><button type="button" className="modal-close" onClick={()=>setShowUnit(false)}><X size={18}/></button><div className="modal-icon pending"><Building2 size={23}/></div><h3>{editingUnit?'تعديل وحدة تنظيمية':'إنشاء وحدة تنظيمية'}</h3><div className="modal-form-grid"><label className="modal-field">اسم الوحدة<input required value={unitName} onChange={e=>setUnitName(e.target.value)}/></label><label className="modal-field">الاسم بالإنجليزية<input value={unitNameEn} onChange={e=>setUnitNameEn(e.target.value)}/></label><label className="modal-field">المستوى التنظيمي<input required value={unitLevel} onChange={e=>setUnitLevel(e.target.value)} placeholder="إدارة / قسم / قطاع..."/></label><label className="modal-field">الرمز<input value={unitCode} onChange={e=>setUnitCode(e.target.value)}/></label><label className="modal-field">الوحدة الأب<select value={unitParent} onChange={e=>setUnitParent(e.target.value)}><option value="">بدون أب (جذر)</option>{units.filter(u=>u.id!==editingUnit?.id&&u.active).map(u=><option key={u.id} value={u.id}>{u.name_ar}</option>)}</select></label>{editingUnit&&<label className="check-row"><input type="checkbox" checked={unitActive} onChange={e=>setUnitActive(e.target.checked)}/><span>الوحدة نشطة</span></label>}</div><div className="form-actions"><button type="button" className="btn secondary" onClick={()=>setShowUnit(false)}>إلغاء</button><button className="btn primary" disabled={busy}>{busy?'جارٍ الحفظ...':'حفظ الوحدة'}</button></div></form></div>}
 {showPosition&&<div className="modal-backdrop"><form className="access-modal wide-modal" onSubmit={savePosition}><button type="button" className="modal-close" onClick={()=>setShowPosition(false)}><X size={18}/></button><div className="modal-icon pending"><UserCog size={23}/></div><h3>{editingPosition?'تعديل منصب':'إنشاء منصب'}</h3><div className="modal-form-grid"><label className="modal-field">الوحدة التنظيمية<select required value={posUnit} onChange={e=>setPosUnit(e.target.value)}><option value="">اختر الوحدة</option>{units.filter(u=>u.active).map(u=><option key={u.id} value={u.id}>{u.name_ar}</option>)}</select></label><label className="modal-field">اسم المنصب<input required value={posTitle} onChange={e=>setPosTitle(e.target.value)}/></label><label className="modal-field">الاسم بالإنجليزية<input value={posTitleEn} onChange={e=>setPosTitleEn(e.target.value)}/></label><label className="modal-field">الرمز<input value={posCode} onChange={e=>setPosCode(e.target.value)}/></label><label className="modal-field">الحالة<select value={posStatus} onChange={e=>setPosStatus(e.target.value as Position['status'])}><option value="vacant">شاغر</option><option value="occupied">مشغول</option><option value="frozen">مجمّد</option></select></label><label className="modal-field">المدير المباشر<select value={posManager} onChange={e=>setPosManager(e.target.value)}><option value="">بدون مدير</option>{positions.filter(p=>p.id!==editingPosition?.id).map(p=><option key={p.id} value={p.id}>{p.title_ar} — {p.organization_unit_name}</option>)}</select></label></div><p className="form-hint">حالة «مشغول» لا تنشئ موظفًا تلقائيًا؛ الربط بالموظف يتم في مرحلة Employee Master.</p><div className="form-actions"><button type="button" className="btn secondary" onClick={()=>setShowPosition(false)}>إلغاء</button><button className="btn primary" disabled={busy}>{busy?'جارٍ الحفظ...':'حفظ المنصب'}</button></div></form></div>}
 </div>
}
function DatabaseIcon(){return <Building2 size={22}/>}
