import { FormEvent, useEffect, useState } from 'react';
import { ArrowRight, Building2, Edit3, ShieldCheck, UserPlus } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../lib/api';

type Company={id:string;company_identifier:string;legal_name:string;display_name:string;management_status:'active'|'inactive';created_at:string;updated_at:string};
type Admin={id:string;username:string;display_name:string|null;employee_id:string|null;status:string}|null;
export function PlatformCompanyDetails(){
  const {id}=useParams();
  const [company,setCompany]=useState<Company|null>(null),[admin,setAdmin]=useState<Admin>(null),[requests,setRequests]=useState<any[]>([]),[edit,setEdit]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [displayName,setDisplayName]=useState(''),[legalName,setLegalName]=useState(''),[identifier,setIdentifier]=useState(''),[status,setStatus]=useState<'active'|'inactive'>('active');
  const [showAdmin,setShowAdmin]=useState(false),[adminUsername,setAdminUsername]=useState(''),[adminDisplayName,setAdminDisplayName]=useState(''),[adminPassword,setAdminPassword]=useState('');
  async function load(){if(!id)return;setLoading(true);try{const r=await api<{company:Company;admin:Admin;recentRequests:any[]}>(`/api/platform/companies/${id}`);setCompany(r.company);setAdmin(r.admin);setRequests(r.recentRequests);setDisplayName(r.company.display_name);setLegalName(r.company.legal_name);setIdentifier(r.company.company_identifier);setStatus(r.company.management_status)}catch{setError('تعذر تحميل بيانات الشركة.')}finally{setLoading(false)}}
  useEffect(()=>{load()},[id]);
  async function save(e:FormEvent){e.preventDefault();setError('');try{await api(`/api/platform/companies/${id}`,{method:'PATCH',body:JSON.stringify({displayName,legalName,companyIdentifier:identifier,managementStatus:status})});setEdit(false);load()}catch(err){setError(err instanceof Error&&err.message==='COMPANY_IDENTIFIER_EXISTS'?'معرّف الشركة مستخدم مسبقًا.':'تعذر تحديث الشركة.')}}
  async function addAdmin(e:FormEvent){e.preventDefault();setError('');try{await api(`/api/platform/companies/${id}/admins`,{method:'POST',body:JSON.stringify({username:adminUsername,displayName:adminDisplayName,password:adminPassword})});setShowAdmin(false);setAdminUsername('');setAdminDisplayName('');setAdminPassword('');load()}catch(err){setError(err instanceof Error&&err.message==='ACTIVE_COMPANY_ADMIN_EXISTS'?'يوجد مدير شركة نشط بالفعل.':err instanceof Error&&err.message==='USERNAME_EXISTS'?'اسم المستخدم مستخدم مسبقًا.':'تعذر إنشاء مدير الشركة.')}}
  if(loading)return <div className="panel-empty">جاري تحميل بيانات الشركة...</div>;
  if(!company)return <div className="state-card"><h3>الشركة غير موجودة</h3><Link className="btn secondary" to="/platform/companies">العودة للشركات</Link></div>;
  return <div>
    <div className="page-header"><div><div className="breadcrumbs-inner"><Link to="/platform/companies">الشركات</Link><ArrowRight size={14}/><span>{company.display_name}</span></div><h1>{company.display_name}</h1><p>{company.legal_name}</p></div><div className="header-actions"><span className={`badge ${company.management_status==='active'?'success':'danger'}`}>{company.management_status==='active'?'نشطة':'غير نشطة'}</span><Link className="btn secondary" to="/platform/companies">العودة</Link></div></div>
    {error&&<div className="login-error page-error">{error}</div>}
    <div className="two-col">
      <section className="panel"><div className="panel-head"><div><h3>بيانات الشركة</h3><p>إدارة الهوية والحالة.</p></div><button className="icon-btn" onClick={()=>setEdit(v=>!v)} title="تعديل"><Edit3 size={16}/></button></div>
        {edit?<form className="form-grid" onSubmit={save}><label>اسم الشركة<input required value={displayName} onChange={e=>setDisplayName(e.target.value)}/></label><label>الاسم النظامي<input required value={legalName} onChange={e=>setLegalName(e.target.value)}/></label><label>المعرّف<input required value={identifier} onChange={e=>setIdentifier(e.target.value)} dir="ltr"/></label><label>الحالة<select value={status} onChange={e=>setStatus(e.target.value as any)}><option value="active">نشطة</option><option value="inactive">غير نشطة</option></select></label><div className="form-actions"><button type="button" className="btn secondary" onClick={()=>setEdit(false)}>إلغاء</button><button className="btn primary">حفظ التعديلات</button></div></form>:<div className="detail-grid"><div className="detail"><span>المعرّف</span><strong>{company.company_identifier}</strong></div><div className="detail"><span>الحالة</span><strong>{company.management_status==='active'?'نشطة':'غير نشطة'}</strong></div><div className="detail"><span>تاريخ الإنشاء</span><strong>{company.created_at}</strong></div><div className="detail"><span>الاسم النظامي</span><strong>{company.legal_name}</strong></div></div>}
      </section>
      <section className="panel"><div className="panel-head"><div><h3>مدير الشركة</h3><p>حساب مرتبط بهذه الشركة فقط.</p></div>{!admin&&!showAdmin&&<button className="btn primary" onClick={()=>setShowAdmin(true)}><UserPlus size={15}/> إضافة مدير</button>}</div>
        {admin?<div className="admin-card"><div className="profile-avatar"><ShieldCheck size={21}/></div><div><strong>{admin.display_name||admin.username}</strong><span>{admin.username} · {admin.status==='active'?'نشط':'غير نشط'}</span></div></div>:showAdmin?<form className="form-grid" onSubmit={addAdmin}><label>اسم المستخدم<input required value={adminUsername} onChange={e=>setAdminUsername(e.target.value)}/></label><label>اسم المدير<input required value={adminDisplayName} onChange={e=>setAdminDisplayName(e.target.value)}/></label><label>كلمة المرور المؤقتة<input required minLength={8} type="password" value={adminPassword} onChange={e=>setAdminPassword(e.target.value)}/></label><div className="form-actions"><button type="button" className="btn secondary" onClick={()=>setShowAdmin(false)}>إلغاء</button><button className="btn primary">إنشاء المدير</button></div></form>:<div className="panel-empty">لا يوجد مدير شركة نشط.</div>}
      </section>
    </div>
    <section className="panel" style={{marginTop:14}}><div className="panel-head"><div><h3>آخر طلبات الدخول</h3><p>سجل مختصر لطلبات الوصول لهذه الشركة.</p></div></div>{requests.length===0?<div className="panel-empty">لا توجد طلبات دخول.</div>:<div className="table-wrap"><table><thead><tr><th>التاريخ</th><th>الحالة</th><th>السبب</th><th>المدة</th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td>{r.requested_at}</td><td><span className="badge neutral">{r.status}</span></td><td>{r.reason}</td><td>{r.expires_at??'—'}</td></tr>)}</tbody></table></div>}</section>
  </div>
}
