import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, Clock3, History, MessageSquare, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../lib/api';
const statusMap:any={'قيد الإجراء':['قيد الإجراء','warning'],'مكتملة':['مكتملة','success'],'ملغية':['ملغية','neutral'],'مرفوضة':['مرفوضة','danger']};
function transitionMatches(t:any,answers:any){const c=t?.condition;if(!c)return true;const source=String(c.source||'');const actual=source.startsWith('question.')?answers[source.slice(9)]:source.startsWith('field.')?answers[source.slice(6)]:undefined;const expected=c.value===true||c.value==='true'?true:c.value===false||c.value==='false'?false:c.value;switch(c.operator){case 'not_equals':return actual!==expected;case 'contains':return String(actual??'').includes(String(expected??''));case 'is_true':return actual===true||actual==='true';case 'is_false':return actual===false||actual==='false';case 'in':return Array.isArray(expected)&&expected.some((x:any)=>JSON.stringify(x)===JSON.stringify(actual));default:return JSON.stringify(actual)===JSON.stringify(expected)}}
const responsibleLabel=(type:string)=>({company_admin:'مدير الشركة',manager:'المدير المباشر',position_holder:'شاغل المنصب',department_manager:'مدير الإدارة',role:'الدور المحدد',user:'المستخدم المحدد',permission:'صاحب الصلاحية'} as any)[type]||type||'—';
const parseMeta=(value:any)=>{try{return value?JSON.parse(value):{}}catch{return {}}};
export function TransactionDetail(){
 const {id}=useParams();const [d,setD]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');const [answers,setAnswers]=useState<any>({});
 async function load(){try{const x=await api<any>(`/api/workflows/transactions/${id}`);setD(x);const initial:any={};for(const a of x.answers||[]){const key=a.question_key||a.field_key;if(key)initial[key]=a.value;}setAnswers(initial);}catch{setError('تعذر تحميل المعاملة.')}}
 useEffect(()=>{void load()},[id]);
 const current=useMemo(()=>d?.workflow?.stages?.find((s:any)=>s.id===d?.transaction?.current_stage_id),[d]);
 const stageFields=useMemo(()=>d?.workflow?.fields?.filter((f:any)=>f.stage_id===current?.id)||[],[d,current]);
 const stageQuestions=useMemo(()=>d?.workflow?.questions?.filter((q:any)=>q.stage_id===current?.id)||[],[d,current]);
 const visibleTransitions=useMemo(()=>{const all=(d?.workflow?.transitions||[]).filter((x:any)=>x.from_stage_id===current?.id&&x.active).sort((a:any,b:any)=>a.sort_order-b.sort_order);return all.filter((x:any)=>transitionMatches(x,answers));},[d,current,answers]);
 const primary=visibleTransitions.find((x:any)=>x.action==='next')||visibleTransitions.find((x:any)=>x.action==='complete');
 const canAct=d?.transaction?.status==='قيد الإجراء';
 async function pass(){if(!primary)return;setBusy(true);setError('');try{await api(`/api/workflows/transactions/${id}/action`,{method:'POST',body:JSON.stringify({action:primary.action,toStageId:primary.to_stage_id||null,answers,reason:reason||null})});setReason('');await load();}catch(e){setError(e instanceof Error&&e.message==='TRANSACTION-004'?'أكمل الحقول والأسئلة المطلوبة أولًا.':e instanceof Error?e.message:'تعذر تمرير المعاملة.')}finally{setBusy(false)}}
 async function feedback(){if(!reason.trim())return;try{await api(`/api/workflows/transactions/${id}/feedback`,{method:'POST',body:JSON.stringify({feedback:reason})});setReason('');await load();}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ الملاحظة.')}}
 if(error&&!d)return <div className="panel-empty">{error}</div>;if(!d)return <div className="panel-empty">جاري تحميل المعاملة...</div>;
 const t=d.transaction;const activeExec=d.history?.find((x:any)=>x.status==='active');const overdue=Boolean(activeExec?.is_overdue);const done=!canAct;
 return <div className="transaction-page">
  <div className="page-header"><div><div className="eyebrow">المعاملات · تفاصيل رسمية</div><h1>#{t.transaction_number} <span className="title-divider">·</span> {t.transaction_type_name}</h1><p>{t.employee_name||'صاحب الطلب غير مرتبط بموظف'} · أنشئت في {t.created_at}</p></div><Link className="btn secondary" to="/transactions"><ArrowRight size={16}/>العودة للمعاملات</Link></div>
  {error&&<div className="login-error page-error">{error}</div>}
  <section className="transaction-command-bar"><div className="command-main"><span className="transaction-number">#{t.transaction_number}</span><div><strong>{t.transaction_type_name}</strong><span>{current?.name_ar||'انتهت المعاملة'}</span></div></div><div className="command-stats"><span><small>الحالة</small><b className={`badge ${statusMap[t.status]?.[1]}`}>{t.status}</b></span><span><small>المسؤول الحالي</small><b>{responsibleLabel(current?.responsible_type)}</b></span><span><small>المدة</small><b className={overdue?'text-danger':''}><Clock3 size={14}/>{overdue?'متأخرة':'ضمن المدة'}</b></span></div></section>
  <div className="transaction-detail-grid polished-transaction-grid">
   <section className="panel transaction-action-panel"><div className="panel-head"><div><span className="section-eyebrow">الخطوة الحالية</span><h3>{done?'تمت معالجة هذه المرحلة':'راجع البيانات ثم مرّر المعاملة'}</h3><p>{done?'هذه المرحلة محفوظة في السجل. يمكنك مراجعة التاريخ أدناه.':'ستُطبّق قواعد سير العمل تلقائيًا وتحدد المرحلة والمسؤول التاليين.'}</p></div><ShieldCheck size={19}/></div>
    {current && (d.history||[]).some((h:any)=>Number(h.execution_order)<Number(activeExec?.execution_order||999)) && <div className="transaction-context-panel"><div className="panel-head"><div><span className="section-eyebrow">السياق السابق</span><h3>ما وصل مع المعاملة إلى هذه المرحلة</h3><p>كل مرحلة لاحقة ترى ما تم إدخاله والإجابة عنه سابقًا، للقراءة فقط.</p></div><History size={18}/></div><div className="previous-stage-context">{(d.actions||[]).filter((a:any)=>['created','next','complete','return'].includes(a.action)).map((a:any,i:number)=>{const m=parseMeta(a.metadata_json);const sid=m.stageId||a.from_stage_id;const st=d.workflow?.stages?.find((x:any)=>x.id===sid);if(!st||Number(st.stage_order)>=Number(current.stage_order))return null;const snap={...(m.dataSnapshot||{}),...(m.answersSnapshot||{})};const defs=[...(d.workflow?.fields||[]).filter((f:any)=>f.stage_id===sid),...(d.workflow?.questions||[]).filter((q:any)=>q.stage_id===sid)];return <div className="previous-stage-block" key={a.id||i}><div><strong>المرحلة {st.stage_order} · {st.name_ar}</strong><span>{a.created_at}</span></div>{defs.length===0?<small>لا توجد أسئلة أو حقول في هذه المرحلة.</small>:defs.map((x:any)=><div className="previous-answer" key={x.id}><span>{x.label_ar||x.question_ar}</span><strong>{snap[x.field_key||x.question_key]===undefined?'—':String(snap[x.field_key||x.question_key])}</strong></div>)}</div>})}</div></div>}
    {canAct&&<>
      {stageFields.length>0&&<div className="transaction-form-block"><div className="block-label">البيانات المطلوبة</div><div className="form-grid">{stageFields.map((f:any)=><label className="form-field" key={f.id}><span>{f.label_ar}{f.required?' *':''}</span>{f.field_type==='textarea'?<textarea rows={4} value={answers[f.field_key]??''} onChange={e=>setAnswers({...answers,[f.field_key]:e.target.value})}/>:f.field_type==='boolean'?<select value={answers[f.field_key]===undefined?'':String(answers[f.field_key])} onChange={e=>setAnswers({...answers,[f.field_key]:e.target.value==='true'})}><option value="">اختر</option><option value="true">نعم</option><option value="false">لا</option></select>:f.field_type==='select'?<select value={answers[f.field_key]??''} onChange={e=>setAnswers({...answers,[f.field_key]:e.target.value})}><option value="">اختر</option>{(f.options||[]).map((o:any)=><option key={String(o)} value={String(o)}>{String(o)}</option>)}</select>:<input type={f.field_type==='date'?'date':f.field_type==='number'?'number':'text'} value={answers[f.field_key]??''} onChange={e=>setAnswers({...answers,[f.field_key]:f.field_type==='number'?Number(e.target.value):e.target.value})}/>}</label>)}</div></div>}
      {stageQuestions.length>0&&<div className="transaction-form-block"><div className="block-label">الأسئلة والقرار</div>{stageQuestions.map((q:any)=><label className="decision-question" key={q.id}><span>{q.question_ar}{q.required?' *':''}</span>{q.question_type==='yes_no'?<div className="segmented"><button type="button" className={answers[q.question_key]===true?'selected':''} onClick={()=>setAnswers({...answers,[q.question_key]:true})}>نعم</button><button type="button" className={answers[q.question_key]===false?'selected':''} onClick={()=>setAnswers({...answers,[q.question_key]:false})}>لا</button></div>:q.question_type==='select'?<select value={answers[q.question_key]??''} onChange={e=>setAnswers({...answers,[q.question_key]:e.target.value})}><option value="">اختر</option>{(q.options||[]).map((o:any)=><option key={String(o)} value={String(o)}>{String(o)}</option>)}</select>:<textarea rows={3} value={answers[q.question_key]??''} onChange={e=>setAnswers({...answers,[q.question_key]:e.target.value})}/>}</label>)}</div>}
      <label className="form-field transaction-note-field"><span>ملاحظة إضافية <small>(اختياري)</small></span><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="أضف توضيحًا إذا احتاجت المعاملة سياقًا إضافيًا..."/></label>
      <div className="pass-action"><div><strong>جاهز للتمرير؟</strong><span>المحرك سيحدد المسار التالي تلقائيًا وفق إجاباتك.</span></div><button className="btn primary pass-button" disabled={busy||!primary} onClick={()=>void pass()}><Check size={18}/>{busy?'جارٍ التمرير...':'تمرير المعاملة'}</button></div>
      {!primary&&<div className="action-warning">لا يوجد مسار «تمرير» صالح لهذه المرحلة. يجب على مسؤول الـWorkflow إضافة وجهة أو إكمال المسار.</div>}
    </>}
    {done&&<div className="completed-state"><Check size={25}/><div><strong>لا يوجد إجراء مطلوب منك الآن</strong><span>تم حفظ قرار هذه المرحلة ضمن السجل غير القابل للاستبدال.</span></div></div>}
   </section>
   <aside className="transaction-side-stack">
    <section className="panel"><div className="panel-head"><div><h3>ملخص الطلب</h3><p>البيانات التي أُنشئت بها المعاملة.</p></div></div>{Object.entries(t.data||{}).map(([k,v])=><div className="transaction-data-row" key={k}><span>{k}</span><strong>{typeof v==='object'?JSON.stringify(v):String(v)}</strong></div>)}</section>
    <section className="panel current-stage-card"><span className="section-eyebrow">المرحلة الحالية</span><h3>{current?.name_ar||'مكتملة'}</h3><div className="stage-responsible"><span>المسؤول</span><strong>{responsibleLabel(current?.responsible_type)}</strong></div><div className="stage-responsible"><span>الاستحقاق</span><strong className={overdue?'text-danger':''}>{activeExec?.due_at||'غير محدد'}</strong></div></section>
   </aside>
  </div>
  <section className="panel transaction-history-panel"><div className="panel-head"><div><span className="section-eyebrow">سجل غير قابل للاستبدال</span><h3>رحلة المعاملة</h3><p>كل مرحلة وقرار وإجراء محفوظ، بما في ذلك الإرجاعات وإعادة المرور.</p></div><History size={19}/></div><div className="transaction-journey">{d.history.map((x:any,i:number)=><div className={`journey-item ${x.status==='active'?'active':''}`} key={x.id}><div className="journey-line"><span className="journey-dot"></span>{i<d.history.length-1&&<i/>}</div><div className="journey-content"><div><strong>{x.stage_name}</strong><span className="journey-status">{x.status}</span></div><p>{x.started_at}{x.completed_at?` → ${x.completed_at}`:''}</p>{x.is_overdue&&<small className="text-danger">تجاوزت المدة المحددة</small>}{x.return_reason&&<small>سبب الإرجاع: {x.return_reason}</small>}</div></div>)}</div></section>
  <section className="panel transaction-history-panel"><div className="panel-head"><div><span className="section-eyebrow">إجابة كل مرحلة</span><h3>ماذا سُئل؟ وماذا أُجيب؟</h3><p>يُعرض لكل مرحلة ما أُرسل عند تمريرها، حتى تبقى صورة المعاملة كما كانت وقت المعالجة.</p></div><History size={19}/></div><div className="transaction-stage-answers">{(d.actions||[]).filter((a:any)=>['created','next','complete','reject','cancel','return'].includes(a.action)).map((a:any,i:number)=>{const m=parseMeta(a.metadata_json);const stage=d.workflow?.stages?.find((st:any)=>st.id===(m.stageId||a.from_stage_id||a.to_stage_id));const snap={...(m.dataSnapshot||{}),...(m.answersSnapshot||{})};const relevant=[...(d.workflow?.fields||[]).filter((f:any)=>f.stage_id===stage?.id),...(d.workflow?.questions||[]).filter((q:any)=>q.stage_id===stage?.id)];return <div className="stage-answer-card" key={a.id||i}><div className="stage-answer-head"><strong>{stage?.name_ar||'مرحلة'}</strong><span>{a.created_at}</span></div>{relevant.length?<div className="stage-answer-list">{relevant.map((x:any)=><div key={x.id}><span>{x.label_ar||x.question_ar}</span><strong>{snap[x.field_key||x.question_key]===undefined?'—':String(snap[x.field_key||x.question_key])}</strong></div>)}</div>:<div className="empty-soft">لا توجد أسئلة أو حقول في هذه المرحلة.</div>}</div>})}</div></section>
  <section className="panel transaction-history-panel"><div className="panel-head"><div><span className="section-eyebrow">المرفقات</span><h3>ملفات المعاملة</h3><p>المرفقات مرتبطة بالمعاملة وبالمرحلة التي أضيفت فيها.</p></div></div>{(d.attachments||[]).length===0?<div className="empty-soft">لا توجد مرفقات محفوظة لهذه المعاملة.</div>:<div className="action-audit-grid">{d.attachments.map((a:any)=><div className="audit-card" key={a.id}><strong>{a.file_name}</strong><span>{a.content_type||'ملف'} · {a.size_bytes?`${Math.round(a.size_bytes/1024)} KB`:'—'}</span><small>{a.created_at}</small></div>)}</div>}</section>
  <section className="panel transaction-history-panel"><div className="panel-head"><div><span className="section-eyebrow">التدقيق</span><h3>سجل الإجراءات</h3><p>منفذ الإجراء ووقته والسبب إن وجد.</p></div></div><div className="action-audit-grid">{d.actions.map((x:any)=><div className="audit-card" key={x.id}><span>{x.created_at}</span><strong>{x.action}</strong>{x.reason&&<p>{x.reason}</p>}</div>)}</div></section>
  {current?.config?.employeeFeedback&&<section className="panel transaction-history-panel"><div className="panel-head"><div><h3>ملاحظات الموظف</h3><p>ملاحظات فرعية لا تغيّر الحالة الرئيسية للمعاملة.</p></div><MessageSquare size={18}/></div><label className="form-field" style={{marginTop:12}}><span>إضافة ملاحظة</span><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="btn secondary" onClick={()=>void feedback()}>حفظ الملاحظة</button>{d.feedback.map((x:any)=><div className="feedback-item" key={x.id}><strong>{x.feedback}</strong><span>{x.created_at}</span></div>)}</section>}
 </div>;
}
