import { useEffect, useState } from 'react';
import { ArrowRight, Check, CornerUpRight, MessageSquare, XCircle } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../lib/api';
const statusMap:any={'قيد الإجراء':['قيد الإجراء','warning'],'مكتملة':['مكتملة','success'],'ملغية':['ملغية','neutral'],'مرفوضة':['مرفوضة','danger']};
function transitionMatches(t:any,answers:any){const c=t?.condition;if(!c)return true;const source=String(c.source||'');const actual=source.startsWith('question.')?answers[source.slice(9)]:source.startsWith('field.')?answers[source.slice(6)]:undefined;const expected=c.value===true||c.value==='true'?true:c.value===false||c.value==='false'?false:c.value;switch(c.operator){case 'not_equals':return actual!==expected;case 'contains':return String(actual??'').includes(String(expected??''));case 'is_true':return actual===true||actual==='true';case 'is_false':return actual===false||actual==='false';case 'in':return Array.isArray(expected)&&expected.some((x:any)=>JSON.stringify(x)===JSON.stringify(actual));default:return JSON.stringify(actual)===JSON.stringify(expected)}}

export function TransactionDetail(){
 const {id}=useParams();const [d,setD]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');const [answers,setAnswers]=useState<any>({});
 async function load(){try{const x=await api<any>(`/api/workflows/transactions/${id}`);setD(x);const initial:any={};for(const a of x.answers||[]){const key=a.question_key||a.field_key;if(key)initial[key]=a.value;}setAnswers(initial);}catch{setError('تعذر تحميل المعاملة.')}}
 useEffect(()=>{void load()},[id]);
 async function action(a:string,toStageId?:string|null){setBusy(true);setError('');try{await api(`/api/workflows/transactions/${id}/action`,{method:'POST',body:JSON.stringify({action:a,reason:reason||null,toStageId,answers})});setReason('');await load();}catch(e){setError(e instanceof Error?e.message:'تعذر تنفيذ الإجراء.')}finally{setBusy(false);}}
 async function feedback(){if(!reason.trim())return;try{await api(`/api/workflows/transactions/${id}/feedback`,{method:'POST',body:JSON.stringify({feedback:reason})});setReason('');await load();}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ الملاحظة.')}}
 if(error&&!d)return <div className="panel-empty">{error}</div>;if(!d)return <div className="panel-empty">جاري التحميل...</div>;
 const t=d.transaction;const current=d.workflow?.stages?.find((s:any)=>s.id===t.current_stage_id);const canAct=t.status==='قيد الإجراء';const stageFields=(d.workflow?.fields||[]).filter((f:any)=>f.stage_id===current?.id);const stageQuestions=(d.workflow?.questions||[]).filter((q:any)=>q.stage_id===current?.id);const configuredTransitions=(d.workflow?.transitions||[]).filter((x:any)=>x.from_stage_id===current?.id&&x.active).sort((a:any,b:any)=>a.sort_order-b.sort_order);const visibleTransitions=configuredTransitions.filter((x:any)=>transitionMatches(x,answers));
 return <div>
  <div className="page-header"><div><div className="eyebrow">تفاصيل المعاملة</div><h1>#{t.transaction_number} — {t.transaction_type_name}</h1><p>{t.employee_name||'بدون موظف'} · {t.created_at}</p></div><Link className="btn secondary" to="/transactions"><ArrowRight size={16}/>المعاملات</Link></div>
  {error&&<div className="login-error page-error">{error}</div>}
  <section className="transaction-summary"><div><span>الحالة</span><strong className={`badge ${statusMap[t.status]?.[1]}`}>{t.status}</strong></div><div><span>المرحلة الحالية</span><strong>{current?.name_ar||'—'}</strong></div><div><span>المسؤول</span><strong>{current?.responsible_type||'—'}</strong></div><div><span>الاستحقاق</span><strong>{d.history?.find((x:any)=>x.status==='active')?.is_overdue?'متأخرة':'ضمن المدة'}</strong></div></section>
  <div className="transaction-detail-grid">
   <section className="panel"><div className="panel-head"><div><h3>إجراءات المرحلة</h3><p>الإرجاع لا يغيّر الحالة الرسمية؛ يتم حفظه ضمن سجل المرحلة.</p></div></div>
    {canAct&&<>
     {stageFields.length>0&&<div className="form-grid" style={{marginTop:14}}>{stageFields.map((f:any)=><label className="form-field" key={f.id}><span>{f.label_ar}{f.required?' *':''}</span>{f.field_type==='textarea'?<textarea rows={3} value={answers[f.field_key]??''} onChange={e=>setAnswers({...answers,[f.field_key]:e.target.value})}/>:<input type={f.field_type==='date'?'date':f.field_type==='number'?'number':'text'} value={answers[f.field_key]??''} onChange={e=>setAnswers({...answers,[f.field_key]:f.field_type==='number'?Number(e.target.value):e.target.value})}/>}</label>)}</div>}
     {stageQuestions.length>0&&<div className="panel" style={{marginTop:14,background:'#fafbfd'}}>{stageQuestions.map((q:any)=><label className="form-field" style={{marginTop:10}} key={q.id}><span>{q.question_ar}{q.required?' *':''}</span>{q.question_type==='yes_no'?<select value={answers[q.question_key]===undefined?'':String(answers[q.question_key])} onChange={e=>setAnswers({...answers,[q.question_key]:e.target.value==='true'})}><option value="">اختر</option><option value="true">نعم</option><option value="false">لا</option></select>:<textarea rows={3} value={answers[q.question_key]??''} onChange={e=>setAnswers({...answers,[q.question_key]:e.target.value})}/>}</label>)}</div>}
     <div className="transaction-actions">{visibleTransitions.map((tr:any)=>{const cls=tr.action==='reject'?'btn danger':tr.action==='next'||tr.action==='complete'?'btn primary':'btn secondary';const icon=tr.action==='reject'?<XCircle size={15}/>:tr.action==='return'?<CornerUpRight size={15}/>:tr.action==='next'||tr.action==='complete'?<Check size={15}/>:null;return <button key={tr.id} className={cls} disabled={busy} onClick={()=>void action(tr.action,tr.to_stage_id||null)}>{icon}{tr.label_ar}</button>})}{visibleTransitions.length===0&&<span className="form-note">لا يوجد إجراء متاح لهذه المرحلة وفق إعدادات الـ Workflow الحالية.</span>}</div>
     <label className="form-field"><span>سبب/ملاحظة الإجراء</span><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label>
    </>}
   </section>
   <section className="panel"><div className="panel-head"><div><h3>بيانات المعاملة</h3><p>البيانات محفوظة كجزء من سجل المعاملة.</p></div></div>{Object.entries(t.data||{}).map(([k,v])=><div className="transaction-data-row" key={k}><span>{k}</span><strong>{typeof v==='object'?JSON.stringify(v):String(v)}</strong></div>)}</section>
  </div>
  <section className="panel" style={{marginTop:16}}><div className="panel-head"><div><h3>سجل المراحل</h3><p>السجل غير قابل للاستبدال؛ كل إعادة تنفيذ تظهر كسجل مستقل.</p></div></div><div className="timeline">{d.history.map((x:any)=><div className="timeline-item" key={x.id}><div className="timeline-dot"></div><div><strong>{x.stage_name}</strong><span>{x.status} · {x.started_at}{x.completed_at?` → ${x.completed_at}`:''}</span>{x.is_overdue&&<small>المرحلة متأخرة</small>}{x.return_reason&&<small>سبب الإرجاع: {x.return_reason}</small>}</div></div>)}</div></section>
  <section className="panel" style={{marginTop:16}}><div className="panel-head"><div><h3>سجل الإجراءات والتدقيق</h3><p>كل إجراء محفوظ مع منفذه ووقته.</p></div></div><div className="timeline">{d.actions.map((x:any)=><div className="timeline-item" key={x.id}><div className="timeline-dot"></div><div><strong>{x.action}</strong><span>{x.created_at}</span>{x.reason&&<small>{x.reason}</small>}</div></div>)}</div></section>
  {current?.config?.employeeFeedback&&<section className="panel" style={{marginTop:16}}><div className="panel-head"><div><h3>ملاحظات الموظف</h3><p>الملاحظات إجراء فرعي وليست حالة رئيسية.</p></div><MessageSquare size={18}/></div><label className="form-field" style={{marginTop:12}}><span>إضافة ملاحظة</span><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)} /></label><button className="btn secondary" onClick={()=>void feedback()}>حفظ الملاحظة</button>{d.feedback.map((x:any)=><div className="feedback-item" key={x.id}><strong>{x.feedback}</strong><span>{x.created_at}</span></div>)}</section>}
 </div>;
}
