import { useEffect,useMemo,useState } from 'react';
import { useNavigate,useParams } from 'react-router-dom';
import { api } from '../lib/api';
import { ArrowRight, CheckCircle2, Clock3, FilePlus2, GitBranch, Search, UserRound, XCircle } from '../components/Icons';

type Item=any;
const statusLabel=(s:string)=>s==='مكتملة'?'مكتملة':s==='مرفوضة'?'مرفوضة':s==='ملغية'?'ملغية':'قيد الإجراء';
const actionLabel=(s:string)=>({create:'إنشاء الطلب',next:'تمرير',return:'إرجاع',reject:'رفض',cancel:'إلغاء'} as any)[s]||s;

export function Transactions(){
 const {id}=useParams(); const nav=useNavigate();
 const [items,setItems]=useState<Item[]>([]),[available,setAvailable]=useState<Item[]>([]),[detail,setDetail]=useState<Item|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [creating,setCreating]=useState(false),[typeId,setTypeId]=useState(''),[targetId,setTargetId]=useState(''),[targets,setTargets]=useState<Item[]>([]),[search,setSearch]=useState(''),[answers,setAnswers]=useState<Record<string,any>>({}),[form,setForm]=useState<Item|null>(null),[delegateId,setDelegateId]=useState(''),[delegateEmployees,setDelegateEmployees]=useState<Item[]>([]);
 useEffect(()=>{ if(id){void loadDetail(id);} else {void loadList();void loadAvailable();}},[id]);
 async function loadList(){setLoading(true);try{const r=await api<any>('/api/transactions/mine');setItems(r.items||[]);}catch(e:any){setError(e.message||'تعذر تحميل الطلبات.');}finally{setLoading(false);}}
 async function loadAvailable(){try{const r=await api<any>('/api/transactions/available');setAvailable(r.items||[]);}catch(e:any){setError(e.message||'تعذر تحميل المعاملات المتاحة.');}}
 async function loadDetail(x:string){setLoading(true);try{setDetail(await api<any>(`/api/transactions/${x}`));}catch(e:any){setError(e.message||'تعذر تحميل الطلب.');}finally{setLoading(false);}}
 async function start(t:any){setTypeId(t.id);setCreating(true);setError('');try{const r=await api<any>(`/api/transactions/available/${t.id}`);setForm(r);setTargets([]);setTargetId('');setAnswers(Object.fromEntries((r.fields||[]).map((f:any)=>[f.id,f.field_type==='boolean'?false:''])));}catch(e:any){setError(e.message||'تعذر تحميل نموذج المعاملة.');}}
 async function searchTargets(){if(!search.trim())return;try{const r=await api<any>(`/api/transactions/employees?search=${encodeURIComponent(search)}`);setTargets(r.items||[]);}catch(e:any){setError(e.message||'تعذر البحث.');}}
 async function submit(){setError('');try{const r=await api<any>('/api/transactions',{method:'POST',body:JSON.stringify({transactionTypeId:typeId,targetEmployeeId:targetId||null,answers:Object.entries(answers).map(([fieldId,value])=>({fieldId,value}))})});nav(`/transactions/${r.id}`);}catch(e:any){setError(e.message||'تعذر إرسال الطلب.');}}
 async function loadDelegateEmployees(){try{const r=await api<any>('/api/transactions/employees?search=');setDelegateEmployees(r.items||[]);}catch{setDelegateEmployees([]);}}
 async function act(action:string,toStageId?:string|null,delegateEmployeeId?:string|null){if(!detail)return;setError('');try{await api(`/api/transactions/${detail.transaction.id}/action`,{method:'POST',body:JSON.stringify({action,toStageId:toStageId||null,delegateEmployeeId:delegateEmployeeId||null,answers:[]})});await loadDetail(detail.transaction.id);}catch(e:any){setError(e.message||'تعذر تنفيذ الإجراء.');}}
 if(id){
  if(loading)return <div className="panel-empty">جاري تحميل الطلب...</div>;
  if(!detail)return <div className="panel-empty"><h3>تعذر العثور على الطلب</h3><p>{error}</p></div>;
  const tx=detail.transaction;
  return <div className="page-section tx-page">
   <div className="page-header"><div><span className="eyebrow">سير العمل</span><h1>{tx.type_name}</h1><p>المعاملة رقم <b>#{tx.transaction_number}</b></p></div><button className="secondary-btn" onClick={()=>nav('/transactions')}><ArrowRight size={16}/> قائمة الطلبات</button></div>
   {error&&<div className="error-banner">{error}</div>}
   <div className="tx-detail-grid">
    <section className="tx-card"><div className="tx-card-head"><div><span>البيانات الأساسية</span><h3>مقدم الطلب والموظف المعني</h3></div><UserRound size={22}/></div><div className="tx-meta-grid"><div><small>مقدم الطلب</small><b>{detail.requesterEmployee?.employee_number||'—'}</b></div><div><small>الموظف المعني</small><b>{detail.employee?.employee_number||'—'}</b></div><div><small>المسمى الوظيفي</small><b>{detail.employee?.job_title||'—'}</b></div><div><small>الحالة</small><b>{statusLabel(tx.status)}</b></div></div></section>
    <section className="tx-card"><div className="tx-card-head"><div><span>مسار المعاملة</span><h3>من البداية إلى الحالة الحالية</h3></div><GitBranch size={22}/></div><div className="tx-timeline">{(detail.workflowStages||[]).map((ws:any)=>{const executed=detail.stages.filter((x:any)=>x.stage_id===ws.id);const active=ws.id===tx.current_stage_id;return <div className={`tx-step ${active?'active':''} ${executed.length?'done':''}`} key={ws.id}><div className="tx-dot">{active?<Clock3 size={15}/>:<CheckCircle2 size={15}/>}</div><div><strong>{ws.name_ar}</strong><small>{active?'المرحلة الحالية':executed.length?`تم تنفيذها ${executed.length} مرة`:'بانتظار الوصول'}</small></div></div>})}</div></section>
    <section className="tx-card tx-wide"><div className="tx-card-head"><div><span>الأسئلة والإجابات</span><h3>السجل الكامل دون استبدال الإجابات السابقة</h3></div></div><div className="tx-answers">{detail.fields.map((f:any)=><div className="tx-answer" key={f.id}><span>{f.label_ar}</span><b>{(detail.answers.filter((a:any)=>a.field_id===f.id).map((a:any)=>a.value)).join(' ← ')||'—'}</b></div>)}</div></section>
    <section className="tx-card tx-wide"><div className="tx-card-head"><div><span>سجل الإجراءات</span><h3>كل إجراء وقرار محفوظ مستقلًا</h3></div></div><div className="tx-actions-log">{detail.actions.map((a:any)=><div key={a.id}><b>{actionLabel(a.action)}</b><span>{new Date(a.created_at).toLocaleString('ar-SA')}</span>{a.reason&&<p>{a.reason}</p>}</div>)}</div></section>
    {detail.canAct&&tx.status==='قيد الإجراء'&&<section className="tx-card tx-wide tx-action-bar"><div><strong>إجراء المرحلة الحالية</strong><span>تنفيذ الإجراء سيُسجل كنسخة مستقلة في تاريخ المعاملة.</span></div><div className="tx-action-buttons"><button className="primary-btn" onClick={()=>act('next')}>تمرير للمرحلة التالية</button>{detail.currentStage?.config?.delegate?.enabled&&<><select className="tx-return-select" value={delegateId} onFocus={()=>{if(!delegateEmployees.length)void loadDelegateEmployees();}} onChange={e=>setDelegateId(e.target.value)}><option value="">اختيار موظف للتفويض…</option>{delegateEmployees.map((e:any)=><option key={e.id} value={e.id}>{e.fullName} · {e.employee_number}</option>)}</select><button className="secondary-btn" disabled={!delegateId} onClick={()=>{void act('delegate',null,delegateId);setDelegateId('');}}>تفويض مؤقت</button></>}{(detail.workflowStages||[]).filter((s:any)=>s.id!==tx.current_stage_id).length>0&&<select className="tx-return-select" defaultValue="" onChange={e=>e.target.value&&act('return',e.target.value)}><option value="">إرجاع إلى مرحلة…</option>{(detail.workflowStages||[]).filter((s:any)=>s.id!==tx.current_stage_id).map((s:any)=><option key={s.id} value={s.id}>{s.name_ar}</option>)}</select>}<button className="secondary-btn" onClick={()=>act('reject')}><XCircle size={16}/> رفض</button><button className="secondary-btn" onClick={()=>act('cancel')}>إلغاء</button></div></section>}
   </div>
  </div>
 }
 return <div className="page-section tx-page">
  <div className="page-header"><div><span className="eyebrow">المعاملات</span><h1>قائمة الطلبات</h1><p>طلباتك والمعاملات التي تتطلب منك إجراءً.</p></div><button className="primary-btn" onClick={()=>setCreating(true)}><FilePlus2 size={17}/> طلب جديد</button></div>
  {error&&<div className="error-banner">{error}</div>}
  {creating&&<div className="tx-modal-wrap"><div className="tx-modal"><div className="page-header"><div><span className="eyebrow">طلب جديد</span><h2>{typeId?'بيانات المعاملة':'اختر المعاملة'}</h2></div><button className="icon-btn" onClick={()=>setCreating(false)}>×</button></div>{!typeId?<div className="tx-template-grid">{available.map(t=><button key={t.id} className="tx-template" onClick={()=>start(t)}><strong>{t.nameAr}</strong><span>{t.description||'بدء معاملة جديدة'}</span></button>)}</div>:<div>{form?.targetEmployeeEnabled&&<div className="tx-form-section"><label>الموظف المعني {form.targetEmployeeRequired?'(مطلوب)':'(اختياري)'}</label><div className="tx-search"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث بالرقم الوظيفي أو الاسم"/><button className="secondary-btn" onClick={searchTargets}><Search size={15}/> بحث</button></div>{targets.map(t=><button className={`tx-target ${targetId===t.id?'selected':''}`} key={t.id} onClick={()=>setTargetId(t.id)}><UserRound size={16}/><span><b>{t.fullName}</b><small>{t.employee_number} · {t.job_title||'—'}</small></span></button>)}</div>}<div className="tx-form-section"><label>بيانات الطلب</label>{(form?.fields||[]).map((f:any)=><label className="tx-field" key={f.id}><span>{f.label_ar}{f.required&&' *'}</span>{f.field_type==='textarea'||f.field_type==='text'?<textarea rows={f.field_type==='textarea'?4:2} value={answers[f.id]??''} onChange={e=>setAnswers((v:any)=>({...v,[f.id]:e.target.value}))}/>:f.field_type==='number'?<input type="number" value={answers[f.id]??''} onChange={e=>setAnswers((v:any)=>({...v,[f.id]:e.target.value}))}/>:f.field_type==='date'||f.field_type==='datetime'?<input type={f.field_type==='date'?'date':'datetime-local'} value={answers[f.id]??''} onChange={e=>setAnswers((v:any)=>({...v,[f.id]:e.target.value}))}/>:f.field_type==='boolean'?<select value={answers[f.id]?'true':'false'} onChange={e=>setAnswers((v:any)=>({...v,[f.id]:e.target.value==='true'}))}><option value="true">نعم</option><option value="false">لا</option></select>:<select value={answers[f.id]??''} onChange={e=>setAnswers((v:any)=>({...v,[f.id]:e.target.value}))}><option value="">اختر</option>{(f.options||[]).map((o:any)=><option key={o} value={o}>{o}</option>)}</select>}</label>)}</div><div className="tx-form-actions"><button className="secondary-btn" onClick={()=>{setTypeId('');setAnswers({});setForm(null);setTargetId('');}}>رجوع</button><button className="primary-btn" onClick={submit}>إرسال الطلب</button></div></div>}</div></div>}
  <div className="tx-list-card">{loading?<div className="panel-empty">جاري تحميل الطلبات...</div>:items.length===0?<div className="panel-empty"><h3>لا توجد طلبات</h3><p>ابدأ طلبًا جديدًا من الزر أعلاه.</p></div>:items.map(t=><button className="tx-list-row" key={t.id} onClick={()=>nav(`/transactions/${t.id}`)}><div><strong>{t.type_name}</strong><span>#{t.transaction_number} · {new Date(t.updated_at).toLocaleString('ar-SA')}</span></div><div className={`tx-status ${t.status==='مكتملة'?'success':t.status==='مرفوضة'?'danger':'pending'}`}>{t.status}</div><ArrowRight size={17}/></button>)}</div>
 </div>
}
