import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, Clock3, History, MessageSquare, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../lib/api';
const statusMap:any={'قيد الإجراء':['قيد الإجراء','warning'],'مكتملة':['مكتملة','success'],'ملغية':['ملغية','neutral'],'مرفوضة':['مرفوضة','danger']};
function transitionMatches(t:any,answers:any){const c=t?.condition;if(!c)return true;const source=String(c.source||'');const actual=source.startsWith('question.')?answers[source.slice(9)]:source.startsWith('field.')?answers[source.slice(6)]:undefined;const expected=c.value===true||c.value==='true'?true:c.value===false||c.value==='false'?false:c.value;switch(c.operator){case 'not_equals':return actual!==expected;case 'contains':return String(actual??'').includes(String(expected??''));case 'is_true':return actual===true||actual==='true';case 'is_false':return actual===false||actual==='false';case 'in':return Array.isArray(expected)&&expected.some((x:any)=>JSON.stringify(x)===JSON.stringify(actual));default:return JSON.stringify(actual)===JSON.stringify(expected)}}
const responsibleLabel=(type:string)=>({company_admin:'مدير الشركة',manager:'المدير المباشر',position_holder:'شاغل المنصب',department_manager:'مدير الإدارة',role:'الدور المحدد',user:'المستخدم المحدد',permission:'صاحب الصلاحية'} as any)[type]||type||'—';
const parseMeta=(value:any)=>{try{return value?JSON.parse(value):{}}catch{return {}}};
export function TransactionDetail(){
 const {id}=useParams();const [d,setD]=useState<any>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');const [answers,setAnswers]=useState<any>({});const [uploading,setUploading]=useState(false);
 async function load(){try{const x=await api<any>(`/api/workflows/transactions/${id}`);setD(x);const initial:any={};for(const a of x.answers||[]){const key=a.question_key||a.field_key;if(key)initial[key]=a.value;}setAnswers(initial);}catch{setError('تعذر تحميل المعاملة.')}}
 useEffect(()=>{void load()},[id]);
 const current=useMemo(()=>d?.workflow?.stages?.find((s:any)=>s.id===d?.transaction?.current_stage_id),[d]);
 const stageFields=useMemo(()=>d?.workflow?.fields?.filter((f:any)=>f.stage_id===current?.id)||[],[d,current]);
 const stageQuestions=useMemo(()=>d?.workflow?.questions?.filter((q:any)=>q.stage_id===current?.id)||[],[d,current]);
 const visibleTransitions=useMemo(()=>{const all=(d?.workflow?.transitions||[]).filter((x:any)=>x.from_stage_id===current?.id&&x.active).sort((a:any,b:any)=>a.sort_order-b.sort_order);return all.filter((x:any)=>transitionMatches(x,answers));},[d,current,answers]);
 const primary=visibleTransitions.find((x:any)=>x.action==='next')||visibleTransitions.find((x:any)=>x.action==='complete');
 const canAct=d?.transaction?.status==='قيد الإجراء';
 async function pass(){if(!primary)return;setBusy(true);setError('');try{await api(`/api/workflows/transactions/${id}/action`,{method:'POST',body:JSON.stringify({action:primary.action,toStageId:primary.to_stage_id||null,answers,reason:reason||null})});setReason('');await load();}catch(e){setError(e instanceof Error&&e.message==='TRANSACTION-004'?'أكمل الحقول والأسئلة المطلوبة أولًا.':e instanceof Error?e.message:'تعذر تمرير المعاملة.')}finally{setBusy(false)}}
 async function feedback(){if(!reason.trim())return;try{await api(`/api/workflows/transactions/${id}/feedback`,{method:'POST',body:JSON.stringify({feedback:reason})});setReason('');await load();}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ الملاحظة.')}}
 async function uploadAttachment(file:File){setUploading(true);setError('');try{const form=new FormData();form.append('file',file);const response=await fetch(`/api/workflows/transactions/${id}/attachments`,{method:'POST',body:form,credentials:'include'});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.message||result.error||'تعذر رفع المرفق.');await load();}catch(e){setError(e instanceof Error?e.message:'تعذر رفع المرفق.')}finally{setUploading(false)}}
 if(error&&!d)return <div className="panel-empty">{error}</div>;if(!d)return <div className="panel-empty">جاري تحميل المعاملة...</div>;
 const t=d.transaction;const activeExec=d.history?.find((x:any)=>x.status==='active');const overdue=Boolean(activeExec?.is_overdue);const done=!canAct;
 return <div className="transaction-page">
  <div className="page-header"><div><div className="eyebrow">المعاملات · تفاصيل رسمية</div><h1>#{t.transaction_number} <span className="title-divider">·</span> {t.transaction_type_name}</h1><p>{t.employee_name||'صاحب الطلب غير مرتبط بموظف'} · أنشئت في {t.created_at}</p></div><Link className="btn secondary" to="/transactions"><ArrowRight size={16}/>العودة للمعاملات</Link></div>
  {error&&<div className="login-error page-error">{error}</div>}
  <section className="transaction-command-bar"><div className="command-main"><span className="transaction-number">#{t.transaction_number}</span><div><strong>{t.transaction_type_name}</strong><span>{current?.name_ar||'انتهت المعاملة'}</span></div></div><div className="command-stats"><span><small>الحالة</small><b className={`badge ${statusMap[t.status]?.[1]}`}>{t.status}</b></span><span><small>المسؤول الحالي</small><b>{responsibleLabel(current?.responsible_type)}</b></span><span><small>المدة</small><b className={overdue?'text-danger':''}><Clock3 size={14}/>{activeExec?.due_at?(overdue?'متأخرة':'ضمن المدة'):'بدون مدة'}</b></span></div></section>
  <div className="transaction-detail-grid polished-transaction-grid">
   <section className="panel transaction-action-panel"><div className="panel-head"><div><span className="section-eyebrow">الخطوة الحالية</span><h3>{done?'تمت معالجة هذه المرحلة':'راجع البيانات ثم مرّر المعاملة'}</h3><p>{done?'هذه المرحلة محفوظة في السجل. يمكنك مراجعة التاريخ أدناه.':'ستُطبّق قواعد سير العمل تلقائيًا وتحدد المرحلة والمسؤول التاليين.'}</p></div><ShieldCheck size={19}/></div>
    {canAct&&<>
      {d.history.filter((h:any)=>h.id!==activeExec?.id&&h.answers_snapshot?.length).length>0&&<div className="transaction-form-block prior-stage-review"><div className="block-label">مراجعة ما سبق في المعاملة</div><p className="prior-stage-help">قبل اتخاذ القرار، راجع ما شاهده المسؤولون السابقون وما سجلوه من إجابات. هذا السجل للقراءة فقط.</p>{d.history.filter((h:any)=>h.id!==activeExec?.id&&h.answers_snapshot?.length).map((h:any)=>{const snap=h.stage_snapshot||{};return <section className="prior-stage-card" key={h.id}><div className="prior-stage-card-head"><strong>{snap.nameAr||h.stage_name}</strong><span>{h.completed_at?new Date(h.completed_at).toLocaleString('ar-SA'):'زيارة سابقة'}</span></div><div className="record-answer-grid">{(h.answers_snapshot||[]).map((a:any,j:number)=><div className="record-answer-cell" key={`${h.id}-${j}`}><span>{a.labelAr||a.key}</span><b>{a.value===true?'نعم':a.value===false?'لا':a.value===null||a.value===undefined||a.value===''?'لم يُجب':typeof a.value==='object'?JSON.stringify(a.value):String(a.value)}</b><small>{a.kind==='question'?'سؤال':'حقل'}</small></div>)}</div></section>})}</div>}
      {stageFields.length>0&&<div className="transaction-form-block"><div className="block-label">البيانات المطلوبة</div><div className="form-grid">{stageFields.map((f:any)=><label className="form-field" key={f.id}><span>{f.label_ar}{f.required?' *':''}</span>{f.field_type==='textarea'?<textarea rows={4} value={answers[f.field_key]??''} onChange={e=>setAnswers({...answers,[f.field_key]:e.target.value})}/>:f.field_type==='boolean'?<select value={answers[f.field_key]===undefined?'':String(answers[f.field_key])} onChange={e=>setAnswers({...answers,[f.field_key]:e.target.value==='true'})}><option value="">اختر</option><option value="true">نعم</option><option value="false">لا</option></select>:f.field_type==='select'?<select value={answers[f.field_key]??''} onChange={e=>setAnswers({...answers,[f.field_key]:e.target.value})}><option value="">اختر</option>{(f.options||[]).map((o:any)=><option key={String(o)} value={String(o)}>{String(o)}</option>)}</select>:<input type={f.field_type==='date'?'date':f.field_type==='number'?'number':'text'} value={answers[f.field_key]??''} onChange={e=>setAnswers({...answers,[f.field_key]:f.field_type==='number'?Number(e.target.value):e.target.value})}/>}</label>)}</div></div>}
      {stageQuestions.length>0&&<div className="transaction-form-block"><div className="block-label">الأسئلة والقرار</div>{stageQuestions.map((q:any)=><label className="decision-question" key={q.id}><span>{q.question_ar}{q.required?' *':''}</span>{q.question_type==='yes_no'?<div className="segmented"><button type="button" className={answers[q.question_key]===true?'selected':''} onClick={()=>setAnswers({...answers,[q.question_key]:true})}>نعم</button><button type="button" className={answers[q.question_key]===false?'selected':''} onClick={()=>setAnswers({...answers,[q.question_key]:false})}>لا</button></div>:q.question_type==='select'?<select value={answers[q.question_key]??''} onChange={e=>setAnswers({...answers,[q.question_key]:e.target.value})}><option value="">اختر</option>{(q.options||[]).map((o:any)=><option key={String(o)} value={String(o)}>{String(o)}</option>)}</select>:<textarea rows={3} value={answers[q.question_key]??''} onChange={e=>setAnswers({...answers,[q.question_key]:e.target.value})}/>}</label>)}</div>}
      {current?.config?.allowAttachments&&<div className="transaction-form-block transaction-attachments-block"><div className="block-label">مرفقات هذه المرحلة</div><p className="prior-stage-help">يمكنك إرفاق ملفات حتى 15 ميجابايت للملف الواحد. تحفظ الملفات على تخزين المعاملات.</p><label className="transaction-file-picker"><input type="file" disabled={uploading||busy} onChange={e=>{const f=e.target.files?.[0];if(f)void uploadAttachment(f);e.currentTarget.value='';}}/><span>{uploading?'جارٍ رفع الملف…':'اختيار ملف لإرفاقه'}</span><small>PDF، صور، Word وغيرها</small></label></div>}
      <label className="form-field transaction-note-field"><span>ملاحظة إضافية <small>(اختياري)</small></span><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="أضف توضيحًا إذا احتاجت المعاملة سياقًا إضافيًا..."/></label>
      <div className="pass-action"><div><strong>جاهز للتمرير؟</strong><span>المحرك سيحدد المسار التالي تلقائيًا وفق إجاباتك.</span></div><button className="btn primary pass-button" disabled={busy||!primary} onClick={()=>void pass()}><Check size={18}/>{busy?'جارٍ التمرير...':'تمرير المعاملة'}</button></div>
      {!primary&&<div className="action-warning">لا يوجد مسار «تمرير» صالح لهذه المرحلة. يجب على مسؤول الـWorkflow إضافة وجهة أو إكمال المسار.</div>}
    </>}
    {done&&<div className="completed-state"><Check size={25}/><div><strong>لا يوجد إجراء مطلوب منك الآن</strong><span>تم حفظ قرار هذه المرحلة ضمن السجل غير القابل للاستبدال.</span></div></div>}
   </section>
   <aside className="transaction-side-stack">
    <section className="panel"><div className="panel-head"><div><h3>ملخص الطلب</h3><p>البيانات التي أُنشئت بها المعاملة.</p></div></div>{Object.entries(t.data||{}).filter(([k])=>!String(k).startsWith('_simulation')).map(([k,v])=><div className="transaction-data-row" key={k}><span>{d.workflow?.fields?.find((f:any)=>f.field_key===k)?.label_ar||k}</span><strong>{typeof v==='object'?JSON.stringify(v):String(v)}</strong></div>)}</section>
    <section className="panel current-stage-card"><span className="section-eyebrow">المرحلة الحالية</span><h3>{current?.name_ar||'مكتملة'}</h3><div className="stage-responsible"><span>المسؤول</span><strong>{responsibleLabel(current?.responsible_type)}</strong></div><div className="stage-responsible"><span>الاستحقاق</span><strong className={overdue?'text-danger':''}>{activeExec?.due_at||'بدون مدة'}</strong></div></section>
   </aside>
  </div>
  <section className="panel transaction-history-panel record-timeline-panel"><div className="panel-head"><div><span className="section-eyebrow">سجل المراحل المحفوظ</span><h3>رحلة المعاملة: ماذا سُئل؟ وماذا أُجيب؟</h3><p>كل زيارة مرحلة تحفظ اسمها وحقولها وأسئلتها وإجاباتها وقت المعالجة.</p></div><History size={19}/></div><div className="record-timeline">{d.history.map((x:any,i:number)=>{const snap=x.stage_snapshot||{};const saved=x.answers_snapshot||[];const fields=snap.fields||[];const qs=snap.questions||[];return <article className={`record-stage-card ${x.status==='active'?'is-current':''}`} key={x.id}><div className="record-stage-rail"><span className="record-stage-index">{String(i+1).padStart(2,'0')}</span>{i<d.history.length-1&&<i/>}</div><div className="record-stage-body"><div className="record-stage-head"><div><span className="record-eyebrow">المرحلة {snap.stageOrder||i+1}</span><h4>{snap.nameAr||x.stage_name||'مرحلة'}</h4></div><span className={`record-stage-status ${x.status}`}>{{active:'جارية',completed:'اكتملت',returned:'أُعيدت',rejected:'رُفضت',cancelled:'أُلغيت'}[x.status]||x.status}</span></div><div className="record-stage-meta"><span><Clock3 size={14}/>بدأت: {x.started_at?new Date(x.started_at).toLocaleString('ar-SA'):'—'}</span><span><Check size={14}/>{x.completed_at?`انتهت: ${new Date(x.completed_at).toLocaleString('ar-SA')}`:'لم تنتهِ بعد'}</span><span><Clock3 size={14}/>المدة: {snap.durationMinutes?`${snap.durationMinutes} دقيقة`:'بدون مدة'}</span></div>{x.return_reason&&<div className="record-return-reason"><b>سبب الإرجاع</b><span>{x.return_reason}</span></div>}<div className="record-answers-heading">الحقول والأسئلة وإجاباتها وقت هذه المرحلة</div>{saved.length?<div className="record-answer-grid">{saved.map((a:any,j:number)=><div className="record-answer-cell" key={`${x.id}-${j}`}><span>{a.labelAr||a.key}</span><b>{a.value===true?'نعم':a.value===false?'لا':a.value===null||a.value===undefined||a.value===''?'لم يُجب':typeof a.value==='object'?JSON.stringify(a.value):String(a.value)}</b><small>{a.kind==='question'?'سؤال':'حقل'}</small></div>)}</div>:<div className="record-no-answers">لا توجد إجابات محفوظة لهذه الزيارة.</div>}<div className="record-stage-definition"><b>تعريف المرحلة وقت الحفظ</b><span>{fields.length} حقول · {qs.length} أسئلة · {snap.config?.allowAttachments?'المرفقات مسموحة':'المرفقات غير مفعلة'}</span></div></div></article>})}</div></section>
  <section className="panel transaction-history-panel"><div className="panel-head"><div><span className="section-eyebrow">المرفقات</span><h3>ملفات المعاملة</h3><p>المرفقات مرتبطة بالمعاملة وبالمرحلة التي أضيفت فيها.</p></div></div>{(d.attachments||[]).length===0?<div className="empty-soft">لا توجد مرفقات محفوظة لهذه المعاملة.</div>:<div className="action-audit-grid">{d.attachments.map((a:any)=><a className="audit-card attachment-download-card" key={a.id} href={`/api/workflows/transactions/${id}/attachments/${a.id}`}><strong>{a.file_name}</strong><span>{a.content_type||'ملف'} · {a.size_bytes?`${Math.round(a.size_bytes/1024)} KB`:'—'}</span><small>{a.stage_name||'مرحلة غير محددة'} · {a.created_at}</small></a>)}</div>}</section>
  <section className="panel transaction-history-panel"><div className="panel-head"><div><span className="section-eyebrow">التدقيق</span><h3>سجل الإجراءات</h3><p>منفذ الإجراء ووقته والسبب إن وجد.</p></div></div><div className="action-audit-grid">{d.actions.map((x:any)=><div className="audit-card" key={x.id}><span>{x.created_at}</span><strong>{x.action}</strong>{x.reason&&<p>{x.reason}</p>}</div>)}</div></section>
  {current?.config?.employeeFeedback&&<section className="panel transaction-history-panel"><div className="panel-head"><div><h3>ملاحظات الموظف</h3><p>ملاحظات فرعية لا تغيّر الحالة الرئيسية للمعاملة.</p></div><MessageSquare size={18}/></div><label className="form-field" style={{marginTop:12}}><span>إضافة ملاحظة</span><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="btn secondary" onClick={()=>void feedback()}>حفظ الملاحظة</button>{d.feedback.map((x:any)=><div className="feedback-item" key={x.id}><strong>{x.feedback}</strong><span>{x.created_at}</span></div>)}</section>}
 </div>;
}
