import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Clock3, Eye, FileText, GitBranch, ShieldCheck, UserRound, UsersRound, Workflow as WorkflowIcon } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../lib/api';

const responsibility: Record<string,string>={direct_manager:'المدير المباشر للموظف المعني',position_holder:'شاغل المنصب المرتبط',department_manager:'مدير الإدارة',role:'دور وظيفي',permission:'حامل صلاحية',company_admin:'مدير الشركة',employee_owner:'الموظف المعني'};
const fieldTypes: Record<string,string>={text:'نص',textarea:'ملاحظات',boolean:'نعم / لا',select:'قائمة اختيار',number:'رقم',date:'تاريخ'};
const sampleValue=(key:string)=>({employee_number:'EMP-0015',full_name:'محمد أحمد',job_title:'أخصائي موارد بشرية',organization_unit:'الموارد البشرية',position:'أخصائي موارد بشرية',direct_manager:'المدير المباشر',actual_start_date:'12 يناير 2026',join_date:'12 يناير 2026',basic_salary:'حسب صلاحية العرض',housing_allowance:'حسب صلاحية العرض',transport_allowance:'حسب صلاحية العرض',work_location:'المقر الرئيسي'} as Record<string,string>)[key]||'قيمة من النظام';

export function WorkflowPreview(){
 const {typeId}=useParams<{typeId?:string}>(); const [data,setData]=useState<any>(null); const [error,setError]=useState('');
 useEffect(()=>{if(typeId)api<any>(`/api/workflows/admin/types/${typeId}`).then(setData).catch((e:any)=>setError(e.message||'تعذر تحميل المعاينة.'));},[typeId]);
 if(!data)return <div className="workflow-studio premium-studio wow-studio"><div className="wf-card wf-template-empty"><div><Eye size={28}/></div><h3>{error||'جارٍ تجهيز المعاينة…'}</h3><p>المعاينة للعرض فقط ولا تنشئ أي بيانات تشغيلية.</p></div></div>;
 const w=data.workflow; const stages=w.stages||[]; const fields=w.fields||[]; const system=w.systemFields||[]; const requester=system.filter((x:any)=>x.scope==='requester').sort((a:any,b:any)=>a.sort_order-b.sort_order); const target=system.filter((x:any)=>x.scope==='target').sort((a:any,b:any)=>a.sort_order-b.sort_order);
 return <div className="workflow-studio premium-studio wow-studio">
  <section className="wf-hero compact"><div className="wf-hero-copy"><div className="wf-crumb"><Link to="/workflow-studio">استوديو سير العمل</Link><ArrowLeft size={13}/><span>معاينة</span></div><div className="wf-hero-title-row"><span className="wf-hero-symbol"><Eye size={27}/></span><div><div className="wf-kicker">WORKFLOW PREVIEW</div><h1>{data.type.name_ar}</h1><p>هذا عرض بصري لما سيشاهده المستخدم النهائي. لا توجد إجراءات تشغيلية ولا يتم إنشاء معاملة فعلية.</p></div></div></div><div className="wf-hero-actions"><span className="wf-status draft"><span/>معاينة فقط</span><Link className="wf-ghost" to={`/workflow-studio/${data.type.id}`}><ArrowLeft size={15}/>العودة للمصمم</Link></div></section>
  <div className="wf-quick-nav"><span className="wf-preview-pill">01 · مقدم الطلب</span><span className="wf-preview-pill">02 · بيانات الطلب</span>{stages.map((s:any,i:number)=><span className="wf-preview-pill" key={s.id}>{String(i+1).padStart(2,'0')} · {s.name_ar}</span>)}</div>
  <section className="wf-card wf-section-card"><div className="wf-section-title"><div className="wf-title-number">01</div><div className="wf-title-copy"><span className="wf-kicker soft">REQUESTER DATA</span><h2>بيانات مقدم الطلب</h2><p>هذه القيم مستدعاة تلقائيًا من ملف الموظف، ولا يكتبها المستخدم يدويًا.</p></div><span className="wf-status-pill active"><span/>من النظام</span></div><div className="wf-preview-data-grid">{requester.length?requester.map((x:any)=><div className="wf-preview-data" key={x.id||x.source_key}><span>{x.label_ar}</span><strong>{sampleValue(x.source_key)}</strong></div>):<div className="wf-profile-empty">لم يختر المصمم أي بيانات نظامية لمقدم الطلب.</div>}</div>{(target.length||w.requestSettings?.targetEmployeeEnabled)&&<div className="wf-preview-target"><div><UsersRound size={16}/><div><strong>الموظف المعني</strong><span>{w.requestSettings?.targetEmployeeRequired?'اختياره مطلوب':'اختياري'}</span></div></div><b>{target.length} بيانات نظامية</b></div>}</section>
  <section className="wf-card wf-section-card"><div className="wf-section-title"><div className="wf-title-number">02</div><div className="wf-title-copy"><span className="wf-kicker soft">REQUEST DATA</span><h2>أسئلة / بيانات الطلب</h2><p>يظهر هنا فقط ما أنشأه مصمم القالب.</p></div></div>{fields.filter((f:any)=>!f.stage_id).length?<div className="wf-preview-question-grid">{fields.filter((f:any)=>!f.stage_id).map((f:any)=><PreviewField key={f.id} field={f}/>)}</div>:<div className="wf-empty-question"><div><FileText size={18}/></div><section><strong>لا توجد أسئلة في أساس المعاملة</strong><span>المصمم لم يضف أي عنصر في هذه الخطوة.</span></section></div>}</section>
  {stages.map((s:any,i:number)=>{const sf=fields.filter((f:any)=>f.stage_id===s.id);const routeCount=(w.transitions||[]).filter((r:any)=>r.from_stage_id===s.id).length;return <section className="wf-stage-card wf-preview-stage" key={s.id}><div className="wf-stage-top"><div className="wf-stage-heading"><span className="wf-stage-number">{i+1}</span><div><span className="wf-stage-kicker">STAGE {String(i+1).padStart(2,'0')}</span><h2>{s.name_ar}</h2><small><ShieldCheck size={12}/>{responsibility[s.responsible_type]||'مسؤول المرحلة'}{s.duration_minutes?` · ${s.duration_minutes} دقيقة`:''}</small></div></div>{i===stages.length-1?<span className="wf-status-pill active"><span/>نهاية المسار</span>:<span className="wf-status-pill"><span/>مرحلة فعلية</span>}</div><div className="wf-stage-preview-body">{sf.length?<div className="wf-preview-question-grid">{sf.map((f:any)=><PreviewField key={f.id} field={f}/>)}</div>:<div className="wf-stage-locked">لا توجد عناصر صممها المسؤول لهذه المرحلة.</div>}<div className="wf-preview-route"><GitBranch size={14}/><span>{routeCount?'تم تكوين مسارات خاصة لهذه المرحلة.':'بدون شرط خاص؛ الانتقال الافتراضي للمرحلة التالية.'}</span></div>{i===stages.length-1&&<div className="wf-complete-note"><CheckCircle2 size={17}/><span><b>بعد نجاح هذه المرحلة تصبح المعاملة مكتملة</b> — لا توجد خطوة إضافية مخفية بعد نجاح هذه المرحلة.</span></div>}</div></section>})}
 </div>;
}
function PreviewField({field}:{field:any}){return <div className="wf-preview-field"><div><strong>{field.label_ar||'عنصر'}</strong><span>{fieldTypes[field.field_type]||'عنصر'}</span></div><span className={`wf-preview-tag ${field.config?.displayOnly?'readonly':field.required?'required':'optional'}`}>{field.config?.displayOnly?'عرض فقط':field.required?'مطلوب':'اختياري'}</span></div>;}
