import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Eye, GitBranch, ShieldCheck, UserRound, UsersRound } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../lib/api';

export function WorkflowPreview(){
 const {typeId}=useParams<{typeId:string}>();
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!typeId)return;api<any>(`/api/workflows/admin/types/${typeId}`).then(setData).catch((e:any)=>setError(e?.message||'تعذر تحميل المعاينة.')).finally(()=>setLoading(false));},[typeId]);
 if(loading)return <div className="wf-empty-state compact"><div className="wf-empty-icon"><Eye size={23}/></div><h3>جاري تجهيز المعاينة…</h3></div>;
 if(error||!data?.workflow)return <div className="wf-alert danger"><ShieldCheck size={18}/>{error||'لا توجد مسودة للمعاينة.'}</div>;
 const w=data.workflow;const fields=w.fields||[];const requester=fields.filter((f:any)=>!f.stage_id&&f.config?.owner==='requester');const subject=fields.filter((f:any)=>!f.stage_id&&f.config?.owner==='subject');const requestFields=fields.filter((f:any)=>!f.stage_id&&!f.config?.systemSource);const stages=w.stages||[];
 return <div className="wf-preview-page wf-studio-page"><div className="wf-builder-top"><div className="wf-back-row"><Link className="wf-back" to={`/workflow-studio/${typeId}`}><ArrowLeft size={17}/>العودة للمصمم</Link><span>/</span><strong>معاينة القالب</strong></div><div className="wf-builder-actions"><Link className="btn" to={`/workflow-studio/test/${typeId}`}><ShieldCheck size={15}/>اختبار A → Z</Link></div></div>
  <section className="wf-preview-hero"><div><div className="wf-hero-kicker"><Eye size={15}/> معاينة بصرية</div><h1>{data.type.name_ar}</h1><p>{w.workflow.description||'هذه المعاينة تُظهر ما سيراه المستخدم داخل المعاملة. لا توجد محاكاة تشغيلية ولا كتابة في D1.'}</p></div><span className="badge warning">مسودة</span></section>
  <section className="wf-preview-card"><div className="wf-preview-card-head"><div><span className="eyebrow">بيانات البداية</span><h2>بيانات النظام التي اختارها المصمم</h2></div><span className="badge info">تلقائية</span></div><div className="wf-preview-dual"><PreviewSystemSection icon={<UserRound size={16}/>} title="مقدم الطلب" fields={requester}/><PreviewSystemSection icon={<UsersRound size={16}/>} title="الموظف المعني" fields={subject}/></div>{w.settings?.subject_mode==='different_employee'&&<div className="wf-preview-note"><UsersRound size={15}/> يسمح القالب باختيار موظف معني مختلف عن مقدم الطلب.</div>}</section>
  {requestFields.length>0&&<section className="wf-preview-card"><div className="wf-preview-card-head"><div><span className="eyebrow">أساس المعاملة</span><h2>أسئلة / بيانات الطلب</h2></div></div><div className="wf-preview-question-grid">{requestFields.map((f:any)=><PreviewField key={f.id} field={f}/>)}</div></section>}
  <section className="wf-preview-card"><div className="wf-preview-card-head"><div><span className="eyebrow">مسار المعاملة</span><h2>المراحل كما ستظهر للمستخدم</h2></div><span>{stages.length} مراحل</span></div><div className="wf-preview-stage-flow"><div className="preview-flow-start"><UserRound size={15}/><span>بيانات مقدم الطلب</span></div>{stages.map((s:any,i:number)=><div className="preview-stage-block" key={s.id}><div className="preview-flow-line"><span></span></div><div className="preview-stage-number">{i+1}</div><div className="preview-stage-info"><strong>{s.name_ar}</strong><span>{responsibilityLabel(s.responsible_type)} · {s.duration_minutes?`${s.duration_minutes} دقيقة`:'بدون مدة محددة'}</span><div className="preview-stage-fields">{fields.filter((f:any)=>f.stage_id===s.id).map((f:any)=><span key={f.id}>{f.label_ar}{f.required?' · مطلوب':''}</span>)}</div></div>{i<stages.length-1&&<div className="preview-stage-next"><CheckCircle2 size={14}/><span>المرحلة التالية تلقائيًا ما لم يوجد شرط</span></div>}</div>)}<div className="preview-complete"><CheckCircle2 size={17}/><span>مكتملة</span><small>بعد تمرير آخر مرحلة فعلية</small></div></div></section>
 </div>;
}
function responsibilityLabel(v:string){const m:any={direct_manager:'المدير المباشر',position_holder:'شاغل المنصب',department_manager:'مدير الإدارة',role:'دور وظيفي',permission:'صلاحية محددة',company_admin:'مدير الشركة',employee_owner:'الموظف المعني'};return m[v]||'مسؤول غير محدد';}
function PreviewSystemSection({icon,title,fields}:{icon:any;title:string;fields:any[]}){return <div className="preview-system-card"><div className="preview-system-head">{icon}<div><strong>{title}</strong><span>{fields.length} عناصر مختارة</span></div></div>{fields.length?<div className="preview-system-list">{fields.map(f=><div key={f.id}><span>{f.label_ar}</span><em>{f.config?.sensitive?'بيانات حساسة · حسب الصلاحية':'من النظام'}</em></div>)}</div>:<div className="wf-inline-empty">لم يحدد المصمم بيانات للعرض.</div>}</div>}
function PreviewField({field:f}:{field:any}){return <div className="preview-question"><div><strong>{f.label_ar||'عنصر غير مسمى'}</strong><span>{typeLabel(f.field_type)}{f.required?' · مطلوب':''}{f.config?.displayOnly?' · عرض فقط':''}</span></div><div className="preview-control">{f.field_type==='boolean'?'نعم / لا':f.field_type==='select'?'اختيار من قائمة':f.field_type==='textarea'?'حقل ملاحظات':f.field_type==='date'?'تاريخ':'إدخال نص'}</div></div>}
function typeLabel(t:string){const m:any={text:'نص',textarea:'ملاحظات',number:'رقم',date:'تاريخ',datetime:'تاريخ ووقت',boolean:'نعم / لا',select:'قائمة اختيار',multiselect:'اختيارات متعددة'};return m[t]||t;}
