import { useEffect, useMemo, useRef, useState } from 'react';
import {
  ArrowDown, ArrowUp, Check, CheckCircle2, ChevronLeft, CircleAlert, Clock3,
  Eye, GitBranch, LayoutTemplate, Plus, RotateCcw, Save, Settings2,
  ShieldCheck, Trash2, UserRound, UsersRound, Workflow as WorkflowIcon, X
} from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '../lib/api';
import { ErrorState, LoadingState } from '../components/State';

type Field={
  id:string; stageId:string|null; fieldKey:string; labelAr:string; fieldType:string;
  required:boolean; displayOnly:boolean; options:string[]; sortOrder:number;
  config?:{displayOnly?:boolean;systemSource?:string;owner?:'requester'|'subject';sensitive?:boolean;group?:string};
};
type Stage={id:string;nameAr:string;responsibleType:string;responsibleValue:string;durationMinutes:number|null;stageOrder:number};
type Route={id:string;fromStageId:string;toStageId:string|null;action:string;labelAr:string;condition:any;sortOrder:number;active:boolean};
type Template={id:string;name_ar:string;description:string|null;status:string;latest_version:number|null;draft_id:string|null;stage_count:number};
type SystemField={key:string;label:string;type:string;group:string;sensitive?:boolean};

const fieldTypes:any={text:'نص قصير',textarea:'ملاحظات',number:'رقم',date:'تاريخ',datetime:'تاريخ ووقت',boolean:'نعم / لا',select:'اختيار واحد',multiselect:'اختيارات متعددة'};
const responsibility:any={direct_manager:'المدير المباشر',position_holder:'شاغل المنصب',department_manager:'مدير الإدارة',role:'دور وظيفي',permission:'صلاحية محددة',company_admin:'مدير الشركة',employee_owner:'الموظف المعني'};
const submitterOptions=[
  {value:'self',label:'الموظف نفسه',description:'الموظف يسجل الطلب لنفسه'},
  {value:'direct_manager',label:'المدير المباشر',description:'المدير يقدّم نيابة عن الموظف'},
  {value:'company_admin',label:'مدير الشركة',description:'المستخدم الإداري للشركة'},
  {value:'permission',label:'مستخدمون بصلاحية المعالجة',description:'بحسب صلاحيات النظام'}
];
const uid=()=>crypto.randomUUID();
const blankStage=(n:number):Stage=>({id:uid(),nameAr:`المرحلة ${n}`,responsibleType:'',responsibleValue:'',durationMinutes:null,stageOrder:n});
const blankField=(stageId:string|null,n:number):Field=>({id:uid(),stageId,fieldKey:`field_${n}`,labelAr:'',fieldType:'text',required:false,displayOnly:false,options:[],sortOrder:n,config:{}});

function errorText(e:any,fallback:string){
  const issues=Array.isArray(e?.issues)?e.issues:[];
  const issueText=issues.slice(0,3).map((x:any)=>x.message).filter(Boolean).join(' • ');
  return [e?.message||fallback,issueText,e?.code?`رمز الخطأ: ${e.code}`:'',e?.referenceId?`رقم المرجع: ${e.referenceId}`:''].filter(Boolean).join(' — ');
}
function statusLabel(status:string){return status==='active'?'نشط':status==='draft'?'مسودة':'غير نشط';}
function statusClass(status:string){return status==='active'?'success':status==='draft'?'warning':'neutral';}
function systemFieldKey(owner:'requester'|'subject',key:string){return `${owner}_${key.replace(/\./g,'_')}`;}

export function WorkflowAdmin(){
 const {typeId}=useParams<{typeId?:string}>();
 if(typeId==='new')return <CreateTemplate/>;
 if(!typeId)return <TemplateList/>;
 return <WorkflowBuilder typeId={typeId}/>;
}

function TemplateList(){
 const nav=useNavigate();
 const [templates,setTemplates]=useState<Template[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[resetting,setResetting]=useState(false),[notice,setNotice]=useState('');
 async function load(){setLoading(true);try{setTemplates((await api<any>('/api/workflows/admin/types')).items||[]);}catch(e){setError(errorText(e,'تعذر تحميل قوالب سير العمل.'));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function resetAll(){
  const ok=window.confirm('سيتم حذف جميع بيانات Phase 6 من قاعدة البيانات: قوالب المعاملات، إصداراتها، مراحلها، الأسئلة، العناصر، الشروط، المسارات، المعاملات ونتائج الاختبار وسجلاتها المرتبطة. لن يتم حذف الشركات أو الموظفين أو المستخدمين أو الهيكل التنظيمي أو صلاحيات Phase 1–5. هل تريد متابعة التصفير الكامل؟');
  if(!ok)return;
  setResetting(true);setError('');setNotice('');
  try{await api('/api/workflows/admin/transactions/cleanup',{method:'POST'});setNotice('تم تنظيف طبقة المعاملات وسير العمل بالكامل. يمكنك البدء من الصفر.');await load();}
  catch(e){setError(errorText(e,'تعذر تنظيف بيانات Phase 6.'));}finally{setResetting(false);}
 }
 const active=templates.filter(x=>x.status==='active').length,drafts=templates.filter(x=>x.status==='draft').length;
 return <div className="wf-studio-page">
  <section className="wf-hero">
   <div className="wf-hero-copy"><div className="wf-hero-kicker"><WorkflowIcon size={15}/> استوديو سير العمل</div><h1>صمّم المعاملة مرة واحدة<br/>ودع النظام يدير مسارها.</h1><p>أنشئ قالبًا مؤسسيًا، اربطه ببيانات الموظف الحقيقية، ثم عرّف المراحل والقرارات دون كتابة أي مفاتيح تقنية.</p><div className="wf-hero-actions"><button className="btn primary wf-btn-light" onClick={()=>nav('/workflow-studio/new')}><Plus size={17}/>إنشاء قالب</button><button className="wf-text-action" onClick={()=>nav('/workflow-studio/test')}><Eye size={16}/>بيئة الاختبار</button></div></div>
   <div className="wf-hero-orbit"><div className="orbit-card"><span>قالب نشط</span><strong>{active}</strong></div><div className="orbit-card"><span>مسودات</span><strong>{drafts}</strong></div><div className="orbit-flow"><b>بيانات النظام</b><span>→</span><b>المراحل</b><span>→</span><b>القرار</b></div></div>
  </section>
  {(error||notice)&&<div className={`wf-alert ${error?'danger':'success'}`}>{error?<CircleAlert size={18}/>:<CheckCircle2 size={18}/>}<span>{error||notice}</span>{notice&&<button onClick={()=>setNotice('')} aria-label="إغلاق"><X size={15}/></button>}</div>}
  <section className="wf-toolbar"><div><div className="eyebrow">Workflow Studio</div><h2>قوالب المعاملات</h2><p>كل قالب يبدأ كمسودة ويمكن فحصه واختباره قبل اعتماده.</p></div><div className="wf-toolbar-actions"><button className="btn" onClick={()=>nav('/workflow-studio/test')}><PlayIcon/>اختبار قالب</button><button className="btn danger-ghost" onClick={resetAll} disabled={resetting}><RotateCcw size={15}/>{resetting?'جارٍ التنظيف…':'تنظيف بيانات Phase 6'}</button></div></section>
  {loading?<LoadingState/>:(templates.length===0?<EmptyTemplates onCreate={()=>nav('/workflow-studio/new')}/>:<div className="wf-template-grid">{templates.map(t=><TemplateCard key={t.id} template={t} onOpen={()=>nav(`/workflow-studio/${t.id}`)}/>)}</div>)}
 </div>;
}
function PlayIcon(){return <span className="wf-play-dot">▶</span>}
function EmptyTemplates({onCreate}:{onCreate:()=>void}){return <div className="wf-empty-state"><div className="wf-empty-icon"><LayoutTemplate size={27}/></div><h3>لا توجد قوالب بعد</h3><p>ابدأ بتعريف معاملة، ثم اختر بيانات النظام التي تريد عرضها والأسئلة والمراحل التي ستسير عليها.</p><button className="btn primary" onClick={onCreate}><Plus size={16}/>إنشاء أول قالب</button></div>}
function TemplateCard({template:t,onOpen}:{template:Template;onOpen:()=>void}){return <article className="wf-template-card" onClick={onOpen}>
 <div className="wf-card-top"><div className="wf-template-icon"><WorkflowIcon size={18}/></div><span className={`badge ${statusClass(t.status)}`}>{statusLabel(t.status)}</span></div>
 <h3>{t.name_ar}</h3><p>{t.description||'لا يوجد وصف مضاف لهذا القالب.'}</p>
 <div className="wf-card-meta"><span><LayoutTemplate size={14}/>{t.stage_count||0} مراحل</span><span><Clock3 size={14}/>{t.latest_version?`الإصدار ${t.latest_version}`:'مسودة جديدة'}</span></div>
 <div className="wf-card-footer"><span>{t.status==='active'?'قالب معتمد':'يحتاج إعداد وفحص'}</span><ChevronLeft size={17}/></div>
 </article>}

function CreateTemplate(){
 const nav=useNavigate();
 const [name,setName]=useState(''),[description,setDescription]=useState(''),[submitters,setSubmitters]=useState<string[]>(['self']),[saving,setSaving]=useState(false),[error,setError]=useState('');
 function toggleSubmitter(value:string){setSubmitters(v=>v.includes(value)?v.filter(x=>x!==value):[...v,value]);}
 async function create(){
  setError('');
  if(!name.trim()){setError('اسم المعاملة مطلوب قبل إنشاء القالب.');return;}
  if(!submitters.length){setError('حدد من يستطيع تقديم المعاملة.');return;}
  setSaving(true);
  try{const r=await api<any>('/api/workflows/admin/types',{method:'POST',body:JSON.stringify({nameAr:name.trim(),description:description.trim()||null,allowedSubmitters:submitters})});nav(`/workflow-studio/${r.id}`);}
  catch(e){setError(errorText(e,'تعذر إنشاء قالب المعاملة.'));}finally{setSaving(false);}
 }
 return <div className="wf-studio-page">
  <div className="wf-back-row"><button className="wf-back" onClick={()=>nav('/workflow-studio')}><ChevronLeft size={18}/>قوالب المعاملات</button><span>إنشاء قالب جديد</span></div>
  <div className="wf-create-layout"><section className="wf-create-main"><div className="wf-step-kicker"><span>01</span> أساس المعاملة</div><h1>أنشئ قالبًا يستوعب أي نوع من المعاملات</h1><p className="wf-lead">ابدأ بالمعلومات الأساسية فقط. بعد الحفظ ينشأ القالب كمسودة وتفتح لك مباشرة شاشة تصميم البيانات والمراحل.</p>
   {error&&<div className="wf-alert danger"><CircleAlert size={17}/><span>{error}</span></div>}
   <div className="wf-form-section"><label className="wf-big-label">اسم المعاملة<span>اسم واضح يظهر للموظفين لاحقًا</span><input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="مثال: طلب نقل موظف"/></label>
    <label className="wf-big-label">الوصف <em>اختياري</em><textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="اكتب الهدف من المعاملة أو متى تستخدم…"/></label></div>
   <div className="wf-form-section"><div className="wf-big-label"><span className="wf-section-title">من يستطيع تقديم المعاملة؟</span><small>يمكنك اختيار أكثر من فئة، وسيطبق النظام الصلاحيات الفعلية عند التشغيل.</small></div><div className="wf-submitters">{submitterOptions.map(o=><button type="button" key={o.value} className={`wf-select-card ${submitters.includes(o.value)?'selected':''}`} onClick={()=>toggleSubmitter(o.value)}><span className="select-check">{submitters.includes(o.value)&&<Check size={14}/>}</span><strong>{o.label}</strong><small>{o.description}</small></button>)}</div></div>
   <div className="wf-create-footer"><button className="btn" onClick={()=>nav('/workflow-studio')}>إلغاء</button><button className="btn primary" onClick={create} disabled={saving}>{saving?'جارٍ إنشاء المسودة…':<>حفظ وبدء التصميم <ChevronLeft size={16}/></>}</button></div>
  </section><aside className="wf-create-aside"><div className="wf-side-illustration"><div className="mini-flow"><span>بيانات الطلب</span><i></i><span>المرحلة 1</span><i></i><span>المرحلة 2</span><i></i><span>مكتملة</span></div></div><h3>ما الذي سيحدث بعد الحفظ؟</h3><div className="wf-explain"><b>1</b><p>ينشأ <strong>Draft</strong> بدون نشر أي شيء.</p></div><div className="wf-explain"><b>2</b><p>تختار بيانات الموظف التي تريد إظهارها.</p></div><div className="wf-explain"><b>3</b><p>تضيف الأسئلة والمراحل والمسارات الشرطية.</p></div><div className="wf-explain"><b>4</b><p>تفحص القالب ثم تختبره من البداية للنهاية.</p></div></aside></div>
 </div>;
}

function WorkflowBuilder({typeId}:{typeId:string}){
 const nav=useNavigate(); const [templates,setTemplates]=useState<Template[]>([]),[loading,setLoading]=useState(true),[type,setType]=useState<any>(null),[workflow,setWorkflow]=useState<any>(null),[stages,setStages]=useState<Stage[]>([]),[fields,setFields]=useState<Field[]>([]),[routes,setRoutes]=useState<Route[]>([]),[systemFields,setSystemFields]=useState<SystemField[]>([]);
 const [name,setName]=useState(''),[description,setDescription]=useState(''),[submitters,setSubmitters]=useState<string[]>(['self']),[subjectMode,setSubjectMode]=useState<'requester'|'different_employee'>('requester');
 const [selectedStage,setSelectedStage]=useState(''),[saving,setSaving]=useState(false),[validation,setValidation]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [systemOpen,setSystemOpen]=useState<'requester'|'subject'|null>('requester'),[searchSystem,setSearchSystem]=useState(''); const stageRefs=useRef<Record<string,HTMLDivElement|null>>({});
 async function load(){setLoading(true);setError('');try{const [t,w,s]=await Promise.all([api<any>(`/api/workflows/admin/types/${typeId}`),api<any>(`/api/workflows/admin/system-fields`),api<any>('/api/workflows/admin/types')]);const typeData=t.type;let wf=t.workflow;if(!wf||wf.workflow.status!=='draft'){const d=await api<any>(`/api/workflows/admin/types/${typeId}/new-draft`,{method:'POST'});wf=(await api<any>(`/api/workflows/admin/types/${typeId}?workflowId=${d.id}`)).workflow;}hydrate(typeData,wf,s.items||[]);setTemplates(w.items||[]);}catch(e){setError(errorText(e,'تعذر فتح مصمم القالب.'));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[typeId]);
 function hydrate(t:any,w:any,sf:SystemField[]){setType(t);setWorkflow(w.workflow);setName(t.name_ar||'');setDescription(w.workflow.description||t.description||'');setSubmitters(w.workflow.allowed_submitters||['self']);setSubjectMode(w.settings?.subject_mode==='different_employee'?'different_employee':'requester');const ss=(w.stages||[]).map((x:any,i:number)=>({id:x.id,nameAr:x.name_ar,responsibleType:x.responsible_type||'',responsibleValue:x.responsible_value||'',durationMinutes:x.duration_minutes===null?null:Number(x.duration_minutes),stageOrder:i+1}));setStages(ss);setSelectedStage(ss[0]?.id||'');setFields((w.fields||[]).map((x:any)=>({id:x.id,stageId:x.stage_id||null,fieldKey:x.field_key,labelAr:x.label_ar,fieldType:x.field_type,required:Boolean(x.required),displayOnly:Boolean(x.config?.displayOnly),options:x.options||[],sortOrder:Number(x.sort_order||0),config:x.config||{}})));setRoutes((w.transitions||[]).map((x:any)=>({id:x.id,fromStageId:x.from_stage_id,toStageId:x.to_stage_id||'',action:x.action,labelAr:x.label_ar,condition:x.condition||null,sortOrder:Number(x.sort_order||0),active:Boolean(x.active)})));setSystemFields(sf);setValidation(null);setNotice('');}
 const requestSystem=useMemo(()=>selectedSystem('requester'),[fields]); const subjectSystem=useMemo(()=>selectedSystem('subject'),[fields]);
 function selectedSystem(owner:'requester'|'subject'){return fields.filter(f=>f.stageId===null&&f.config?.owner===owner&&f.config?.systemSource).sort((a,b)=>a.sortOrder-b.sortOrder);}
 const filteredSystem=useMemo(()=>systemFields.filter(f=>!searchSystem||f.label.includes(searchSystem)||f.group.includes(searchSystem)),[systemFields,searchSystem]);
 function hasSystem(owner:'requester'|'subject',key:string){return fields.some(f=>f.stageId===null&&f.config?.owner===owner&&f.config?.systemSource===`${owner}.${key}`);}
 function toggleSystem(owner:'requester'|'subject',sf:SystemField){const source=`${owner}.${sf.key}`;setFields(prev=>{const existing=prev.find(f=>f.config?.owner===owner&&f.config?.systemSource===source);if(existing)return prev.filter(f=>f.id!==existing.id);const sameOwner=prev.filter(f=>f.config?.owner===owner&&f.stageId===null).length;return [...prev,{id:uid(),stageId:null,fieldKey:systemFieldKey(owner,sf.key),labelAr:sf.label,fieldType:sf.type,required:false,displayOnly:true,options:[],sortOrder:Math.max(0,...prev.map(f=>f.sortOrder+1)),config:{displayOnly:true,systemSource:source,owner,sensitive:Boolean(sf.sensitive),group:sf.group}}]});}
 function addField(stageId:string|null){setFields(prev=>[...prev,blankField(stageId,prev.length+1)]);}
 function removeField(id:string){setFields(prev=>prev.filter(f=>f.id!==id));setRoutes(prev=>prev.map(r=>r.condition?.fieldId===id?{...r,condition:null}:r));}
 function updateField(id:string,patch:Partial<Field>){setFields(prev=>prev.map(f=>f.id===id?{...f,...patch}:f));}
 function addStage(){const s=blankStage(stages.length+1);setStages(prev=>[...prev,s]);setSelectedStage(s.id);requestAnimationFrame(()=>stageRefs.current[s.id]?.scrollIntoView({behavior:'smooth',block:'center'}));}
 function removeStage(id:string){if(stages.length===1){setError('يجب أن يحتوي القالب على مرحلة واحدة على الأقل.');return;}const remaining=stages.filter(s=>s.id!==id).map((s,i)=>({...s,stageOrder:i+1}));setStages(remaining);setFields(prev=>prev.map(f=>f.stageId===id?{...f,stageId:null}:f));setRoutes(prev=>prev.filter(r=>r.fromStageId!==id&&r.toStageId!==id));setSelectedStage(remaining[0]?.id||'');}
 function moveStage(index:number,dir:number){const j=index+dir;if(j<0||j>=stages.length)return;const a=[...stages];[a[index],a[j]]=[a[j],a[index]];setStages(a.map((s,i)=>({...s,stageOrder:i+1})))}
 function addBranch(stageId:string){const idx=stages.findIndex(s=>s.id===stageId);const next=stages[idx+1]?.id||'';const candidate=fields.filter(f=>{const sid=f.stageId;return !!f.config?.systemSource||sid===null||sid===stageId||sid!==null&&stages.findIndex(x=>x.id===sid)<=idx});if(!next){setError('هذه آخر مرحلة فعلية، ولا تحتاج مسارًا يدويًا للإنهاء.');return;}const source=candidate.find(f=>!f.config?.systemSource&&f.fieldType==='boolean')||candidate.find(f=>!f.config?.systemSource);setRoutes(prev=>[...prev,{id:uid(),fromStageId:stageId,toStageId:next,action:'next',labelAr:'تمرير المعاملة',condition:source?{fieldId:source.id,operator:'equals',values:['نعم']}:null,sortOrder:prev.filter(r=>r.fromStageId===stageId).length,active:true}]);}
 function updateRoute(id:string,patch:Partial<Route>){setRoutes(prev=>prev.map(r=>r.id===id?{...r,...patch}:r));}
 function scrollStage(id:string){setSelectedStage(id);stageRefs.current[id]?.scrollIntoView({behavior:'smooth',block:'start'});}
 async function save(runValidate=false){if(!workflow)return;setSaving(true);setError('');setNotice('');try{const r=await api<any>(`/api/workflows/admin/workflows/${workflow.id}`,{method:'PUT',body:JSON.stringify({transactionTypeId:type.id,nameAr:name,description,allowedSubmitters:submitters,subjectMode,stages,fields,transitions:routes})});setValidation(r.validation);setNotice('تم حفظ المسودة.');if(runValidate){const v=await api<any>(`/api/workflows/admin/workflows/${workflow.id}/validate`,{method:'POST'});setValidation(v);}await load();}catch(e){setError(errorText(e,'تعذر حفظ المسودة.'));}finally{setSaving(false);}}
 async function publish(){if(!workflow)return;setSaving(true);setError('');setNotice('');try{const v=await api<any>(`/api/workflows/admin/workflows/${workflow.id}/validate`,{method:'POST'});setValidation(v);if(!v.valid){setError('أصلح أخطاء التحقق الموضحة أدناه قبل الاعتماد.');return;}await api(`/api/workflows/admin/workflows/${workflow.id}/publish`,{method:'POST'});setNotice('تم اعتماد القالب بنجاح.');await load();}catch(e){setError(errorText(e,'تعذر اعتماد القالب.'));}finally{setSaving(false);}}
 if(loading&&!type)return <LoadingState/>;if(!type||!workflow)return <>{error?<div className="wf-alert danger">{error}</div>:<ErrorState/>}</>;
 const selectedCount=requestSystem.length+subjectSystem.length, fieldCount=fields.filter(f=>f.stageId).length;
 return <div className="wf-studio-page wf-builder">
   <div className="wf-builder-top"><div className="wf-back-row"><button className="wf-back" onClick={()=>nav('/workflow-studio')}><ChevronLeft size={18}/>قوالب المعاملات</button><span>/</span><strong>{name||type.name_ar}</strong><span className="wf-draft-pill"><i></i>{workflow.status==='draft'?'مسودة':'معتمد'}</span></div><div className="wf-builder-actions"><button className="btn" onClick={()=>nav(`/workflow-studio/${typeId}/preview`)}><Eye size={16}/>معاينة</button><button className="btn" onClick={()=>nav(`/workflow-studio/test/${typeId}`)}><PlayIcon/>اختبار A → Z</button><button className="btn" onClick={()=>save(false)} disabled={saving}><Save size={16}/>{saving?'جارٍ الحفظ…':'حفظ المسودة'}</button><button className="btn primary" onClick={publish} disabled={saving}><ShieldCheck size={16}/>فحص واعتماد</button></div></div>
   <div className="wf-builder-title"><div><div className="eyebrow">استوديو سير العمل</div><h1>{name||type.name_ar}</h1><p>{description||'صمّم البيانات والمراحل والمسارات من شاشة واحدة.'}</p></div><div className="wf-progress"><span className="active">1 الأساس</span><span>2 المراحل</span><span>3 الشروط</span><span>4 التحقق</span></div></div>
   {(error||notice)&&<div className={`wf-alert ${error?'danger':'success'}`}>{error?<CircleAlert size={18}/>:<CheckCircle2 size={18}/>}<span>{error||notice}</span>{error&&<button className="wf-alert-close" onClick={()=>setError('')}><X size={15}/></button>}</div>}
   <div className="wf-builder-body">
    <aside className="wf-builder-rail"><div className="wf-rail-card"><span className="wf-rail-label">نظرة القالب</span><div className="wf-rail-metric"><strong>{stages.length}</strong><span>مراحل</span></div><div className="wf-rail-metric"><strong>{selectedCount}</strong><span>بيانات نظام</span></div><div className="wf-rail-metric"><strong>{fieldCount}</strong><span>أسئلة وعناصر</span></div><div className="wf-rail-separator"/><button className="wf-rail-link active">أساس المعاملة</button>{stages.map((s,i)=><button key={s.id} className={`wf-rail-link ${selectedStage===s.id?'stage-active':''}`} onClick={()=>scrollStage(s.id)}><b>{i+1}</b>{s.nameAr}</button>)}<button className="wf-add-stage" onClick={addStage}><Plus size={15}/>إضافة مرحلة</button></div></aside>
    <main className="wf-canvas">
      <section className="wf-card wf-base-card"><div className="wf-card-header"><div className="wf-number">01</div><div><h2>أساس المعاملة</h2><p>حدد ما سيراه مقدم الطلب وما يريده النظام أن يعرفه تلقائيًا.</p></div></div>
       <div className="wf-base-grid"><div className="wf-base-column"><div className="wf-subheading"><UserRound size={17}/><div><strong>بيانات مقدم الطلب</strong><span>تُستدعى تلقائيًا من ملف الموظف الحالي</span></div></div><SystemFieldPicker owner="requester" open={systemOpen==='requester'} onToggle={()=>setSystemOpen(systemOpen==='requester'?null:'requester')} fields={filteredSystem} selected={requestSystem} has={key=>hasSystem('requester',key)} toggle={sf=>toggleSystem('requester',sf)} search={searchSystem} setSearch={setSearchSystem}/></div>
       <div className="wf-base-column"><div className="wf-subheading"><UsersRound size={17}/><div><strong>الموظف المعني</strong><span>{subjectMode==='requester'?'الافتراضي هو مقدم الطلب.':'يمكن اختيار موظف آخر أثناء إنشاء المعاملة.'}</span></div></div><div className="wf-subject-mode"><button className={subjectMode==='requester'?'selected':''} onClick={()=>setSubjectMode('requester')}><CheckCircle2 size={16}/><div><strong>نفس مقدم الطلب</strong><small>المعاملة تخص الموظف الذي قدمها</small></div></button><button className={subjectMode==='different_employee'?'selected':''} onClick={()=>setSubjectMode('different_employee')}><UsersRound size={16}/><div><strong>السماح بموظف آخر</strong><small>مثال: مدير يقدّم طلبًا لموظف</small></div></button></div><SystemFieldPicker owner="subject" open={systemOpen==='subject'} onToggle={()=>setSystemOpen(systemOpen==='subject'?null:'subject')} fields={filteredSystem} selected={subjectSystem} has={key=>hasSystem('subject',key)} toggle={sf=>toggleSystem('subject',sf)} search={searchSystem} setSearch={setSearchSystem}/></div></div>
       <div className="wf-selected-strip"><span><Check size={14}/>{selectedCount} عناصر من النظام مختارة</span><span>لن تظهر أي بيانات تلقائيًا ما لم يحددها المصمم.</span></div>
       <div className="wf-request-fields"><div className="wf-subheading"><LayoutTemplate size={17}/><div><strong>أسئلة / بيانات الطلب</strong><span>عناصر ينشئها المصمم بنفسه. لا توجد حقول تلقائية إضافية.</span></div><button className="btn" onClick={()=>addField(null)}><Plus size={15}/>إضافة عنصر</button></div>{fields.filter(f=>f.stageId===null&&!f.config?.systemSource).length===0?<div className="wf-inline-empty">أضف سؤالًا أو بيانات طلب يحتاجها نوع المعاملة.</div>:<div className="wf-field-list">{fields.filter(f=>f.stageId===null&&!f.config?.systemSource).map(f=><FieldEditor key={f.id} field={f} systemFields={systemFields} onChange={updateField} onRemove={removeField}/>)}</div>}</div>
      </section>
      <div className="wf-section-banner"><div><span>02</span><div><strong>المراحل</strong><small>كل مرحلة مستقلة ومسؤولة عن تنفيذ جزء محدد من المعاملة.</small></div></div><button className="btn primary" onClick={addStage}><Plus size={16}/>إضافة مرحلة</button></div>
      {stages.map((stage,i)=><StageCard key={stage.id} stage={stage} index={i} stages={stages} fields={fields} routes={routes} selected={selectedStage===stage.id} stageRef={el=>stageRefs.current[stage.id]=el} onFocus={()=>setSelectedStage(stage.id)} onStageChange={(p)=>setStages(prev=>prev.map(s=>s.id===stage.id?{...s,...p}:s))} onRemove={()=>removeStage(stage.id)} onMove={dir=>moveStage(i,dir)} onFieldAdd={()=>addField(stage.id)} onFieldChange={updateField} onFieldRemove={removeField} onRouteAdd={()=>addBranch(stage.id)} onRouteChange={updateRoute} onRouteRemove={id=>setRoutes(prev=>prev.filter(r=>r.id!==id))}/>) }
      {validation&&<ValidationPanel validation={validation} onJump={(stageId)=>stageId&&scrollStage(stageId)}/>} 
      <div className="wf-bottom-save"><div><strong>{saving?'جارٍ الحفظ…':'آخر مسودة محفوظة عند آخر حفظ'}</strong><span>احفظ المسودة في أي وقت؛ الاعتماد يمر بفحص مستقل.</span></div><div><button className="btn" onClick={()=>save(true)} disabled={saving}>فحص المسودة</button><button className="btn primary" onClick={publish} disabled={saving}>اعتماد القالب</button></div></div>
    </main>
   </div>
 </div>;
}

function SystemFieldPicker({owner,open,onToggle,fields,selected,has,toggle,search,setSearch}:{owner:'requester'|'subject';open:boolean;onToggle:()=>void;fields:SystemField[];selected:Field[];has:(key:string)=>boolean;toggle:(f:SystemField)=>void;search:string;setSearch:(s:string)=>void}){
 const groups=Array.from(new Set(fields.map(f=>f.group)));
 return <div className={`wf-system-picker ${open?'open':''}`}><button className="wf-picker-summary" onClick={onToggle}><span><b>{selected.length}</b> بيانات مختارة</span><span>{open?'إخفاء':'تعديل الاختيار'}<ChevronLeft size={15} className={open?'rotated':''}/></span></button>{open&&<div className="wf-picker-body"><div className="wf-picker-intro"><div><strong>ما البيانات التي تريد ظهورها؟</strong><span>هذه البيانات مرتبطة مباشرة ببيانات Phase 5 عند تشغيل المعاملة.</span></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث في بيانات الموظف…"/></div>{groups.map(group=><div className="wf-system-group" key={group}><div className="wf-system-group-title">{group}</div><div className="wf-system-grid">{fields.filter(f=>f.group===group).map(sf=><button type="button" key={sf.key} className={`wf-system-item ${has(sf.key)?'selected':''}`} onClick={()=>toggle(sf)}><span className="wf-system-check">{has(sf.key)&&<Check size={13}/>}</span><div><strong>{sf.label}</strong>{sf.sensitive&&<small>بيانات حساسة · تحكم الصلاحيات عند التشغيل</small>}</div></button>)}</div></div>)}</div>}</div>;
}

function FieldEditor({field:f,onChange,onRemove}:{field:Field;systemFields:SystemField[];onChange:(id:string,p:Partial<Field>)=>void;onRemove:(id:string)=>void}){return <div className="wf-field-editor"><div className="wf-field-main"><input value={f.labelAr} onChange={e=>onChange(f.id,{labelAr:e.target.value})} placeholder="اكتب السؤال أو اسم البيانات"/><select value={f.fieldType} onChange={e=>onChange(f.id,{fieldType:e.target.value})}>{Object.entries(fieldTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="wf-field-options"><label><input type="checkbox" checked={f.required} onChange={e=>onChange(f.id,{required:e.target.checked})}/> مطلوب</label><label><input type="checkbox" checked={f.displayOnly} onChange={e=>onChange(f.id,{displayOnly:e.target.checked,required:e.target.checked?false:f.required})}/> للعرض فقط</label><span className="wf-field-key">يُنشئ النظام المعرف تلقائيًا</span><button className="icon-btn" onClick={()=>onRemove(f.id)} aria-label="حذف العنصر"><Trash2 size={14}/></button></div>{(['select','multiselect'].includes(f.fieldType))&&<input className="wf-options-input" value={f.options.join('، ')} onChange={e=>onChange(f.id,{options:e.target.value.split(/[,،]/).map(x=>x.trim()).filter(Boolean)})} placeholder="اكتب الخيارات: نعم، لا، ..."/>}</div>}

function StageCard({stage,index,stages,fields,routes,selected,stageRef,onFocus,onStageChange,onRemove,onMove,onFieldAdd,onFieldChange,onFieldRemove,onRouteAdd,onRouteChange,onRouteRemove}:{stage:Stage;index:number;stages:Stage[];fields:Field[];routes:Route[];selected:boolean;stageRef:(el:HTMLDivElement|null)=>void;onFocus:()=>void;onStageChange:(p:Partial<Stage>)=>void;onRemove:()=>void;onMove:(dir:number)=>void;onFieldAdd:()=>void;onFieldChange:(id:string,p:Partial<Field>)=>void;onFieldRemove:(id:string)=>void;onRouteAdd:()=>void;onRouteChange:(id:string,p:Partial<Route>)=>void;onRouteRemove:(id:string)=>void}){
 const stageFields=fields.filter(f=>f.stageId===stage.id).sort((a,b)=>a.sortOrder-b.sortOrder); const routeRows=routes.filter(r=>r.fromStageId===stage.id).sort((a,b)=>a.sortOrder-b.sortOrder); const priorOrCurrent=fields.filter(f=>{if(f.stageId===null)return true;const si=stages.findIndex(s=>s.id===f.stageId);return si>=0&&si<=index;});
 return <section ref={stageRef} className={`wf-stage wf-card ${selected?'focus':''}`} onFocus={onFocus}><div className="wf-stage-head"><div className="wf-stage-index">{index+1}</div><div className="wf-stage-title"><input value={stage.nameAr} onChange={e=>onStageChange({nameAr:e.target.value})}/><small>المرحلة {index+1} · الاسم الذي سيظهر للمسؤول والموظف</small></div><div className="wf-stage-tools"><button className="icon-btn" onClick={()=>onMove(-1)} disabled={index===0} title="أعلى"><ArrowUp size={15}/></button><button className="icon-btn" onClick={()=>onMove(1)} disabled={index===stages.length-1} title="أسفل"><ArrowDown size={15}/></button><button className="icon-btn" onClick={onRemove} disabled={stages.length===1} title="حذف"><Trash2 size={15}/></button></div></div>
  <div className="wf-stage-config"><label><span>المسؤول</span><select value={stage.responsibleType} onChange={e=>onStageChange({responsibleType:e.target.value,responsibleValue:e.target.value==='role'||e.target.value==='permission'?stage.responsibleValue:''})}><option value="">اختر المسؤول…</option>{Object.entries(responsibility).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label><span>مدة المرحلة</span><div className="wf-duration"><input type="number" min={1} value={stage.durationMinutes??''} onChange={e=>onStageChange({durationMinutes:e.target.value?Number(e.target.value):null})} placeholder="بدون مدة"/><em>دقيقة</em></div></label>{['role','permission'].includes(stage.responsibleType)?<label><span>{stage.responsibleType==='role'?'اسم الدور':'الصلاحية'}</span><input value={stage.responsibleValue} onChange={e=>onStageChange({responsibleValue:e.target.value})} placeholder={stage.responsibleType==='role'?'مثال: الموارد البشرية':'مثال: معالجة المعاملات'}/></label>:<div className="wf-responsible-note"><ShieldCheck size={16}/><span>{stage.responsibleType?`سيحدد المحرك الشخص المناسب اعتمادًا على ${responsibility[stage.responsibleType]}.`:'حدد المسؤول قبل اعتماد القالب.'}</span></div>}</div>
  <div className="wf-stage-section"><div className="wf-section-head"><div><strong>عناصر المرحلة</strong><span>{stageFields.length} عناصر</span></div><button className="btn" onClick={onFieldAdd}><Plus size={15}/>إضافة سؤال</button></div>{stageFields.length===0?<div className="wf-inline-empty">لا توجد عناصر في هذه المرحلة. أضف فقط ما يحتاجه المسؤول لتنفيذها.</div>:<div className="wf-field-list">{stageFields.map(f=><FieldEditor key={f.id} field={f} systemFields={[]} onChange={onFieldChange} onRemove={onFieldRemove}/>)}</div>}</div>
  {index<stages.length-1&&<div className="wf-logic-section"><div className="wf-section-head"><div><strong><GitBranch size={15}/>مسارات خاصة</strong><span>الانتقال العادي إلى المرحلة التالية يحدث تلقائيًا.</span></div><button className="btn" onClick={onRouteAdd}><Plus size={15}/>إضافة شرط</button></div>{routeRows.length===0?<div className="wf-default-route"><span className="wf-route-arrow">↓</span><div><strong>المسار الافتراضي</strong><p>تمرير المعاملة ينتقل تلقائيًا إلى <b>{stages[index+1]?.nameAr}</b> ما لم تضف شرطًا خاصًا.</p></div></div>:<div className="wf-routes-list">{routeRows.map(r=><RouteEditor key={r.id} route={r} stage={stage} index={index} stages={stages} fields={priorOrCurrent} onChange={onRouteChange} onRemove={onRouteRemove}/>)}</div>}</div>}
  {index===stages.length-1&&<div className="wf-complete-state"><CheckCircle2 size={18}/><div><strong>بعد تمرير هذه المرحلة</strong><span>لأنها آخر مرحلة فعلية في القالب، تنتقل المعاملة إلى حالة <b>مكتملة</b>.</span></div></div>}
 </section>;
}
function RouteEditor({route:r,stage,index,stages,fields,onChange,onRemove}:{route:Route;stage:Stage;index:number;stages:Stage[];fields:Field[];onChange:(id:string,p:Partial<Route>)=>void;onRemove:(id:string)=>void}){const targetOptions=stages.filter((s,i)=>i>index);const condition=r.condition||{fieldId:'',operator:'equals',values:['نعم']};return <div className="wf-route-editor"><div className="wf-route-badge"><GitBranch size={15}/></div><div className="wf-route-content"><div className="wf-route-line"><span>إذا</span><select value={condition.fieldId} onChange={e=>onChange(r.id,{condition:{...condition,fieldId:e.target.value}})}><option value="">اختر السؤال…</option>{fields.map(f=><option value={f.id} key={f.id}>{f.labelAr}</option>)}</select><select value={condition.operator} onChange={e=>onChange(r.id,{condition:{...condition,operator:e.target.value}})}><option value="equals">يساوي</option><option value="not_equals">لا يساوي</option><option value="contains">يحتوي</option></select><input value={condition.values?.join('، ')||''} onChange={e=>onChange(r.id,{condition:{...condition,values:e.target.value.split(/[,،]/).map(x=>x.trim()).filter(Boolean)}})} placeholder="القيمة"/><span>← اذهب إلى</span><select value={r.toStageId||''} onChange={e=>onChange(r.id,{toStageId:e.target.value})}><option value="">اختر المرحلة…</option>{targetOptions.map(s=><option key={s.id} value={s.id}>{s.nameAr}</option>)}</select></div><div className="wf-route-sub"><span>عنوان الإجراء</span><input value={r.labelAr} onChange={e=>onChange(r.id,{labelAr:e.target.value})}/><button className="icon-btn" onClick={()=>onRemove(r.id)}><Trash2 size={14}/></button></div></div></div>}

function ValidationPanel({validation,onJump}:{validation:any;onJump:(stageId:string)=>void}){const errs=validation.errors||[],warnings=validation.warnings||[];return <section className={`wf-validation-panel ${validation.valid?'valid':''}`}><div className="wf-validation-head"><div className="wf-validation-icon">{validation.valid?<CheckCircle2 size={20}/>:<CircleAlert size={20}/>}</div><div><h2>{validation.valid?'القالب جاهز للاعتماد':'نحتاج بعض الإصلاحات قبل الاعتماد'}</h2><p>{validation.valid?'لم نجد أخطاء تمنع تشغيل القالب.':'كل مشكلة أدناه قابلة للوصول المباشر إلى مكانها داخل المصمم.'}</p></div><span className={validation.valid?'badge success':'badge danger'}>{validation.valid?'صحيح':`${errs.length} أخطاء`}</span></div>{errs.length>0&&<div className="wf-validation-list">{errs.map((e:any,i:number)=><button key={i} onClick={()=>onJump(e.stageId||'')}><strong>{e.message}</strong><span>{e.code}</span><ChevronLeft size={15}/></button>)}</div>}{warnings.length>0&&<div className="wf-warning-list">{warnings.map((w:any,i:number)=><div key={i}><span>!</span>{w.message}</div>)}</div>}</section>}
