import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Eye, FileText, Layers3, Paperclip, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../lib/api';

export function WorkflowPreview(){
 const {typeId=''}=useParams();const [type,setType]=useState<any>(null),[workflow,setWorkflow]=useState<any>(null),[fields,setFields]=useState<any[]>([]),[questions,setQuestions]=useState<any[]>([]),[stages,setStages]=useState<any[]>([]),[stageId,setStageId]=useState(''),[mode,setMode]=useState<'requester'|'stage'>('requester'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let alive=true;async function load(){setLoading(true);setError('');try{const meta=await api<any>(`/api/workflows/admin/types/${typeId}`);const w=(meta.workflow||[]).slice().sort((a:any,b:any)=>Number(b.version)-Number(a.version));const selected=w.find((x:any)=>x.status==='draft')||w.find((x:any)=>x.status==='active')||w[0];if(!selected)throw new Error('لا توجد مسودة أو نسخة منشورة للمعاينة.');const d=await api<any>(`/api/workflows/admin/workflows/${selected.id}`);if(!alive)return;setType(meta.type);setWorkflow(d.workflow);const ss=(d.stages||[]).slice().sort((a:any,b:any)=>a.stage_order-b.stage_order);setStages(ss);setStageId(ss[0]?.id||'');setFields(d.fields||[]);setQuestions(d.questions||[]);}catch(e){if(alive)setError(e instanceof Error?e.message:'تعذر تحميل المعاينة.')}finally{if(alive)setLoading(false)}}void load();return()=>{alive=false}},[typeId]);
 const stage=stages.find(s=>s.id===stageId)||stages[0];const visibleFields=useMemo(()=>mode==='requester'?fields.filter(f=>!f.stage_id):fields.filter(f=>f.stage_id===stage?.id||(!f.stage_id&&stage?.stage_order===1)),[fields,mode,stage]);const visibleQuestions=questions.filter(q=>q.stage_id===stage?.id);
 if(loading)return <div className="panel-empty">جاري تجهيز معاينة المعاملة…</div>;
 if(error||!workflow)return <div className="panel-empty">{error||'لا توجد نسخة للمعاينة.'}</div>;
 return <div className="studio-page" dir="rtl"><div className="studio-topbar"><div className="studio-brand"><span className="studio-brand-icon"><Eye size={22}/></span><div><span>HR NEXUS · READ-ONLY PREVIEW</span><h1>معاينة: {type?.name_ar}</h1><p>عرض شكل واجهة مقدم الطلب أو المرحلة دون حفظ أي بيانات أو إنشاء معاملة.</p></div></div><div className="studio-top-actions"><Link className="studio-btn secondary" to={`/platform/workflows?typeId=${typeId}`}><ArrowRight size={16}/>العودة للاستوديو</Link><Link className="studio-btn primary" to={`/platform/workflows/test/${typeId}`}><ShieldCheck size={16}/>اختبار سير العمل</Link></div></div>
 <div className="studio-preview-notice"><Eye size={17}/><span>هذه معاينة بصرية فقط. لا تُحفظ إجابات، ولا تُنشأ معاملات حقيقية. استخدم بيئة الاختبار للتحقق من انتقال المراحل والشروط.</span></div>
 <div className="studio-stepper"><button className={`studio-step preview-step ${mode==='requester'?'active':'done'}`} onClick={()=>setMode('requester')}><span>1</span><div><b>عناصر مقدم الطلب</b><small>واجهة إنشاء الطلب</small></div></button><div className="studio-step-line"/><button className={`studio-step preview-step ${mode==='stage'?'active':'pending'}`} onClick={()=>setMode('stage')}><span>2</span><div><b>معاينة المراحل</b><small>{stages.length} مراحل</small></div></button></div>
 <div className="studio-preview-layout">{mode==='stage'&&<aside className="studio-stage-rail"><div className="studio-rail-head"><div><span className="studio-eyebrow">معاينة فقط</span><h3>المراحل</h3></div><span>{stages.length}</span></div><div className="studio-stage-list">{stages.map((s:any,i:number)=><button key={s.id} className={`studio-stage-nav ${s.id===stage?.id?'selected':''}`} onClick={()=>setStageId(s.id)}><span className="stage-number">{String(i+1).padStart(2,'0')}</span><span className="stage-nav-text"><b>{s.name_ar}</b><small>{s.responsible_type==='company_admin'?'مدير الشركة':s.responsible_type}</small></span></button>)}</div></aside>}
 <main className="studio-preview-main"><section className="studio-preview-form"><div className="studio-preview-form-head"><span className="studio-eyebrow">{mode==='requester'?'نموذج مقدم الطلب':`المرحلة ${stage?.stage_order||1}`}</span><h2>{mode==='requester'?'بيانات الطلب':stage?.name_ar||'المرحلة'}</h2><p>{mode==='requester'?'هذه الحقول ستظهر قبل بدء سير المعالجة.':'هذه الحقول والأسئلة تظهر للمسؤول في هذه المرحلة فقط.'}</p></div>{mode==='stage'&&<div className="studio-preview-stage-meta"><span><Layers3 size={14}/>{stage?.responsible_type==='company_admin'?'مدير الشركة':stage?.responsible_type||'المسؤول'}</span><span>{stage?.duration_minutes?`المدة ${stage.duration_minutes} دقيقة`:'بدون مدة'}</span>{stage?.config?.allowAttachments&&<span><Paperclip size={14}/>المرفقات مسموحة</span>}</div>}
 {visibleFields.length===0&&visibleQuestions.length===0?<div className="studio-empty compact"><FileText size={20}/><span>لا توجد عناصر معرفة في هذا القسم بعد.</span></div>:<div className="studio-preview-fields">{visibleFields.map((f:any)=><label className="studio-label" key={f.id}>{f.label_ar}{f.required?' *':''}{f.field_type==='textarea'?<textarea disabled rows={3} placeholder="معاينة حقل نصي طويل"/>:f.field_type==='boolean'?<select disabled defaultValue=""><option value="">اختر</option><option>نعم</option><option>لا</option></select>:f.field_type==='select'||f.field_type==='multiselect'?<select disabled defaultValue=""><option value="">اختر من القائمة</option>{(f.options||[]).map((o:any,i:number)=><option key={i}>{String(o?.label_ar||o?.label||o?.value||o)}</option>)}</select>:<input disabled type={f.field_type==='date'?'date':f.field_type==='number'?'number':'text'} placeholder={f.field_type==='number'?'0':`أدخل ${f.label_ar}`}/>}</label>)}{visibleQuestions.map((q:any)=><div className="studio-preview-question" key={q.id}><b>{q.question_ar}{q.required?' *':''}</b>{q.question_type==='yes_no'?<div className="studio-preview-choice"><button disabled>نعم</button><button disabled>لا</button></div>:q.question_type==='select'?<select disabled defaultValue=""><option value="">اختر الإجابة</option>{(q.options||[]).map((o:any,i:number)=><option key={i}>{String(o?.label_ar||o?.label||o?.value||o)}</option>)}</select>:<textarea disabled rows={3} placeholder="الإجابة هنا"/>}</div>)}</div>}
 <div className="studio-preview-footer"><span>معاينة غير قابلة للحفظ</span><button className="studio-btn primary" disabled>تمرير المعاملة</button></div></section></main></div></div>;
}
